### ISSUE TITLE
Focus state is not visual consistent

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1167]
The attached image is from "Clay list" in Chrome, but its happen in a different way in different browsers, so I think maybe the best solution is forcing a global style for focus state

List:
![image](https://user-images.githubusercontent.com/7963804/45022376-612e1c80-b034-11e8-9aef-4e9507732a2d.png)

Management bar state 2:
![image](https://user-images.githubusercontent.com/7963804/45022493-b36f3d80-b034-11e8-8a9b-54ed5cfdb917.png)

**Comment by pat270** [comment]
Hey @marcoscv-work,

For this specific case, if you want the focus state to match the button and want it to always be visible on click add `btn btn-unstyled` to the anchor tag. Otherwise this behavior is intentional. Chrome, FF, Safari, IE/Edge all handle focus states on anchor tags in their own way. We shouldn't disrupt the default behavior for people using those respective browsers. Focus behavior on button tags are very similar across all the major browsers, which is why they have focus styles. 

For example in Chrome and IE/Edge, clicking an anchor tag that opens a dropdown won't show the focus border. Safari will show the focus border. Firefox will only show the focus border if you have previously tabbed through any of the elements.

If we add focus styles on anchor tags it will always be visible on click no matter what browser and is a big headache to undo. I still don't know how to revert back to the default behavior in IE/Edge (If anyone knows please let me know). The focus style on an anchor tag not matching the focus style on a button doesn't make it any less accessible. There is still a clear visual indication that the element is focused. The only problem with the browser default is if the `background-color` is very similar to the focus ring color. I really don't think we should touch this.

**Comment by pat270** [comment]
Duplicates https://github.com/liferay/clay/issues/1616
