### ISSUE TITLE
Clay Dropdown does not show items when it is opened in a Modal

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#1184]
When a dropdown is rendered in a Clay Modal, items are not displayed (check z-index attribute)

<img width="1122" alt="clay dropdown in clay modal" src="https://user-images.githubusercontent.com/8373764/45618367-b6771e80-ba75-11e8-994e-95f0aac0b745.png">

**Comment by matuzalemsteles** [comment]
hey @pat270 can this be a css problem? Can you take a look when you have a chance and say what you think?

**Comment by pat270** [comment]
@matuzalemsteles depends how you look at it. I believe the reason it's not showing is because Clay Dropdown is inserting the `dropdown-menu` markup either at the top or bottom of `body`. There's no `z-index` rule I can make up to make it work in all situations.

If the `dropdown-menu` markup was inserted inside the modal, it would show. If that's the issue I think it would be nice to have Clay Dropdown render the markup wherever the dropdown is and add an option to render it outside (e.g., in tables).

**Comment by jbalsas** [comment]
When used inside a modal, it can be expected that the Dropdown is retargeted to a different `portalElement`. Keep in mind that opting out of using a portal for these elements opens up the possibility of endless cropping combinations, where a container with `overflow: hidden` will simply cut off the element.

**Comment by kresimir-coko** [comment]
This might be similar to #3185 @ambrinchaudhary is this still an issue?

**Comment by matuzalemsteles** [comment]
@kresimir-coko I think this issue is related to version 2.x

**Comment by kresimir-coko** [comment]
What can we do about this if it's related to 2.x? Do we fix the old version somehow, or do we close this issue?

**Comment by kresimir-coko** [comment]
@matuzalemsteles see comment above

**Comment by matuzalemsteles** [comment]
@kresimir-coko issues related to 2.x, for now, are not prioritized, so we haven't worked on them yet, but if there are more problems related to it, we can go back and fix and cut a new version. 2.x is in maintenance mode only, so we will only work when critical issues arise, I believe that this was resolved in another way in DXP. We just have to make sure it doesn't happen in 3.x.

**Comment by kresimir-coko** [comment]
Alright, closing due to lack of confirmation. @ambrinchaudhary If I'm wrong we can reopen it with provided more information.
