### ISSUE TITLE
API consistency between clay-charts and clay-charts-react

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#1299]
Opening this in regards to [this comment](https://github.com/liferay/clay/pull/1294#issuecomment-437365530).

The first question we should probably ask is "is it important to keep the same API across both packages?"

Personally, I don't really know. Part of me thinks we should keep it consistent but then another part of me thinks that we shouldn't worry about it because soy and react have very different paradigms in implementation and application architecture. It seems likely that one API will work better in soy's case, and a very different API would make more sense for React.

Anyways, just wanted to start the discussion here. In this post.

@matuzalemsteles what made you think of keeping the API consistent across both? Do you think its important to do so?

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus, First of all thanks for opening this issue so we can discuss in order to reach consensus and be able to evolve our components, I really like it 😁.

I just want to leave some points about my vision.

- I like the idea of maintaining API consistency, so it will be easier for people to migrate from Soy Charts to React Charts.
- I realized a lot that the developers took a while to understand the ClayCharts APIs and try to reconcile with the Billboard (Maybe because we did not have good documentation to expose.), Then adding another difference could cause confusion.
- Maintaining consistency makes it easy for us to talk about Clay Charts and to disclose that it can be used in both React and Metal without any difficulties.
- It also helps us keep documentation more transparent and easy to maintain. It would be a bit tricky to put this information in a transparent way for developers if we do not go along that line, maybe.

I also like to go with a different API, React is totally different, I agree with you. Maybe we can improve our Charts APIs so we can come up with a harmony that is good for both sides.

**Comment by bryceosterhaus** [comment]
Great thoughts, @matuzalemsteles!

In response to your points
> I like the idea of maintaining API consistency, so it will be easier for people to migrate from Soy Charts to React Charts.

I don't think we need to worry about this since going from soy to react isn't simply a migration, it is more of a rewrite because the logic flow in the components is very different.

> I realized a lot that the developers took a while to understand the ClayCharts APIs and try to reconcile with the Billboard (Maybe because we did not have good documentation to expose.), Then adding another difference could cause confusion.

As someone who had to consume the API as a user before ever contributing back to charts, I think the issue here was lack of documentation on how to use the charts.

>Maintaining consistency makes it easy for us to talk about Clay Charts and to disclose that it can be used in both React and Metal without any difficulties.

This makes a lot of sense, I hadn't thought of it this way before.

> It also helps us keep documentation more transparent and easy to maintain. It would be a bit tricky to put this information in a transparent way for developers if we do not go along that line, maybe.

This makes sense as well. One way to avoid the confusion would be to avoid co-locating the documentation for the soy and react version. I see `clay-charts` more as a wrapper for billboard with added sugar on top, so I think it makes sense to see react vs soy as two different implementations of a billboard wrapper.

Overall, I would advocate that they do not need to be consistent but rather they need to be easily understood and useful APIs within their context(soy, react). If we focus on making the APIs consistent, both use cases will likely have to make sacrifices for one another and I think it would be healthier for each package to be able to make its own API choices that fall in line with billboard.

**Comment by jbalsas** [comment]
Hey everyone, I think we could keep them separate for now to prevent additional overhead and see where that takes us.

**Comment by julien** [comment]
@jbalsas sounds good to me.

**Comment by matuzalemsteles** [comment]
I'm closing this, since we're already moving with the Charts migration #2046
