### ISSUE TITLE
Malware in a dependency

### ISSUE THREAD

**Issue by sbaechler** [liferay/clay#1333]
Clay has a transitive dependency through 'event-stream' to a node-module called 'flatmap-stream'.

The version of 'event-stream' that is effected is 3.3.6.

You should lock the version to 3.3.4 until 3.3.7 is released, or upgrade to 4.0.

The malware searches a user's computer for Bitcoin wallets and empties them.

https://github.com/dominictarr/event-stream/issues/115

**Comment by matuzalemsteles** [comment]
hey @sbaechler, This is safer for sure, but since the affected version has been removed from NPM, we will have no issues with that for now. Until they retrieve the owner of the repository in NPM. But we will be going with your solution, you could send a PR just correcting this so that we can go with it and rebase in the latest PR to be able to continue.

**Comment by sbaechler** [comment]
The dependency still exists in event-stream. NPM just pulled the bad repo. Yarn has a local cache. It somehow made it to my system anyway. On CI the build failed because it could not find the dependency. Either way is not good.

**Comment by sbaechler** [comment]
Turned out, the malware only targeted a specific crypto wallet that was using the file-stream package as a transitive dependency.

However, I think this is just the first wave of node module based attacks. I highly recommend adding an automated check for security vulnerabilities in node modules to the build pipeline. npm is providing this service for free.

**Comment by matuzalemsteles** [comment]
Thanks @sbaechler by the information. We are thinking something about this for us to prevent these types of attacks.
