### ISSUE TITLE
Charts component name is not consistent with the rest of Clay Component

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#1409]
Naming convention we're following in all clay components is ClayComponentName but in Charts we're not following it.

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

I think we don't need to go over the effort for `2.x`, specially since we're already working on https://github.com/liferay/clay/milestone/14. In any case, @carloslancha, @matuzalemsteles , feel free to reopen if still relevant.

Thanks!
