### ISSUE TITLE
ClayMultiSelect: When you press backspace in input to focus on the tag the browser returns to the previous page in Firefox

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1448]

**Comment by matuzalemsteles** [comment]
This is not really a bug but an expected behavior of Firefox, see this for more information https://support.mozilla.org/en-US/questions/1057630.

I'll mark this as a wontfix, if anyone has any idea of ​​how to circumvent this behavior please leave your thoughts.

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

I understand firefox has this behaviour when the user is not typing text. The problem is that ClayMultiSelect is basically a "smart" input. 

When I type in it and press enter a label is created and, since I can keep typing to add more labels, I also expect the backspace to remove what I typed. 

If you try https://react-select.com/home it behaves the way I expect on both browsers (Firefox and Chrome).

I still think this is a bug.

Thanks!

**Comment by julien** [comment]
I'm re opening this issue since it also happens with V3
https://issues.liferay.com/browse/LPS-89052
