### ISSUE TITLE
Missing information in filterLabelCloseClicked

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1467]
When showing filter label items in the management toolbar, it's not really possible to implement a `handleFilterLabelCloseClicked` handler since [the fired event has no associated data](https://github.com/liferay/clay/blob/master/packages/clay-management-toolbar/src/ClayManagementToolbar.js#L133-L144) to know which filter was closed.

Additionally, one option that was mentioned by @adolfopa and @4lejandrito was that they could predict the urls beforehand, so we could simply make those links that do a standard navigation (or handle this globally for them)

**Comment by 4lejandrito** [comment]
We have 2 options:
1. We can pass the name of the attribute to be removed from the current URL and you guys take care of it internally. Easier for us, harder for you, less flexible. 
2. We can remove it ourselves in the backend and pass the whole URL to the label. This way you just need to set it to the href of the anchor for example. Harder for us, easier for you, more flexible.

I personally prefer option 2 even if it is more code on our side because it gives us more freedom to manipulate the URL in the precise way we need.

I p

**Comment by carloslancha** [comment]
For now fixing this we're passing correct data through components so it can be handled. From portal we'll add support for `removeLabelURL`
