### ISSUE TITLE
Use of semver

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#1489]
As part of the new path clay is about to follow I think we should talk about the correct use of semver in this project.

Until now we've been totally flexible about versioning so If for example we introduced a breaking change no mayor versions has been released.

## Proposal

I think we should follow semver specs as strict as posible. For me that's the only way to speak the same version language with the rest of the world. So if we introduce a breaking change there should not be any drama about increasing the major number.

It is totally true, and I agree with @jbalsas on that, that we must be more careful o what we do, and we should create and update or components in the smarter way we can to avoid as much breaking changes as possible.

Keeping all this in mind we should define what a breaking change is, what API means for us. We need to think about three parts: JS Components API, HTML and CSS.

So... what do you guys think?

**Comment by wincent** [comment]
> the only way to speak the same version language with the rest of the world

Absolutely. This is necessary to interop nicely with the community and avoid violating the principle of least surprise.

I agree with you that it is possible (and correct) to do both of these at once:

* Adhere very strictly to semver.
* Make a strong commitment to avoiding making breaking changes to the maximum extent that is practically possible.

(Some wiggle room in the wording of that second one to give us room in case we make mistakes despite our best intentions.)

Of the three areas that you mentioned, how to do it in JS is probably clearest. For HTML/CSS it may be a little trickier, but I think we can do it. One possible way is to namespace our CSS selectors into private/public parts — a selector that includes "public" (ie. in the class name) is one that we make a commitment not to change. Anything else is considered a (private) implementation detail. Just say somebody needs to do something that can't be targeted using public selectors? Instead of cooking up a selector that depends on internal DOM structure, it should become a feature request to expose a new class or make a currently private class.

**Comment by matuzalemsteles** [comment]
hey @carloslancha, I fully agree to follow the semver rigorously, but also to be attentive to the changes we implement.

So one thing we should make clear to follow through with the conversation, will we continue with the line of versioning each package or will all packages follow the same version as we are currently doing?

I will leave here some thought I have about this and some concerns:

## Beta Components

One thing we have very common in Clay's components when we started, which at the beginning of each component's creation, even though we care about the definition of the API and try to cover every use case, from which we merged and started testing it on Liferay for example, we always have API changes or new additions, this will break us a bit about following the semver strictly, because such changes are necessary.

I think we can follow the stream of branding the component with the Beta version and as soon as we spend that time we can add it as stable.

## API

My thoughts on the API definition of the components, I find it super valid to take into account API changes, removal, addition, compatibility..., being reflected in the versioning.

We have to work closely with API depreciation warnings and build compatibilities with implementing a new API and adding another (Something similar as proposed in # 1359) somehow, this can help not to "pollute" the versioning and we do not get close to v23 (not that I do not like...) so fast. Just thoughts to go carefully and handle version numbering when changes are needed.

### Behavior

It is noteworthy that behavior changes in a component, we must also take into consideration in the versioning, when an API is not modified its initial purpose.

## HTML/CSS

I think that ClayCSS should follow a numbering of part of the components, if we group everything in one place the numbering will be changed very frequently and it will have a lot of responsibility and it would be confusing for those who use it. We can have people using only ClayCSS and not Clay Components for example.

**Comment by matuzalemsteles** [comment]
hey @jbalsas I think the two complement each other but we can separate in a thread to discuss, I will open a new issue to create proposals to define this.

I think it's also useful then to create an issue to centralize all those proposals that will take effect for Clay 3.x and 2.x. Just to be aligned and visible to everyone and we can move this to the site maybe or `CONTRIBUTING.md`

**Comment by matuzalemsteles** [comment]
I will close this issue since we are now following SemVer from 3.x. If you have any other suggestions on this, feel free to open another issue.
