### ISSUE TITLE
Clay Multi Select gets focus when other input elements change

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#1581]
This is how we reproduce it:

![video](https://user-images.githubusercontent.com/1937354/53106745-eef2bb00-3533-11e9-90bf-bcc353107232.gif)

When any of the other inputs change the multiselect gets the focus. Please note that the whole thing is a Soy template.

This is the line that is run:

<img width="707" alt="screenshot 2019-02-20 at 17 00 51" src="https://user-images.githubusercontent.com/1937354/53106822-1c3f6900-3534-11e9-8de6-ea1c76e9afec.png">

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, thanks for reporting this use case, does `syncSelectedItems` run whenever some state change occurs on the other components and causes a re-render? Maybe it's not safe to use `sync` in this case...

**Comment by 4lejandrito** [comment]
I believe that's what's happening. When one of the components triggers a state change the multi select is rerendered and captures the focus.

**Comment by matuzalemsteles** [comment]
Thanks for the information!

**Comment by matuzalemsteles** [comment]
Just an update on this, I was investigating yesterday and seems to be a problem with Metal.js, it gets lost trying to identify which state changed value when it is of the type `array` (Metal adds a `set `and `get` to any value of the state object, this is strange and may be what is confusing the Metal to identify which prevVal and newVal). The problem is that there may be people who are using this as normal behavior because it is a very old problem and can cause a break change, I will try to do some controversy with this in Clay but this happens in `willReceiveState`, `sync` and `changed`.

A common case that is seen being used is updating the state of type `array` with the same reference to cause a new rendering.

cc @jbalsas
