### ISSUE TITLE
RTL is not working correctly with text align

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1743]
Bootstrap adds a text-align: left; in the body.
https://github.com/twbs/bootstrap/blob/3e05d016cf18e99725b9e77491a501c97b8dc7ac/scss/_reboot.scss#L53

So the RTL is not working fine.

We could try with something like:
```
body[dir="rtl"] {
	direction: rtl;
	text-align: right;
}
```

Original issue:
https://issues.liferay.com/browse/LPS-92808

**Comment by pat270** [comment]
@marcoscv-work RTL isn't supported in Bootstrap or Clay CSS out of the box. You need to run it through a converter that flips all the CSS properties (e.g., `text-align: left;` to `text-align: right`). We do this already in Portal so this doesn't need to be added here.

**Comment by jbalsas** [comment]
I'm reopening this here since it needs a bit further discussion.

The problem is not RTL, but when in LTR and a piece of the page is in `RTL`. That is, you're viewing a site in English (`lang="en_US" dir="ltr"`) but have a piece of content in a different language (`lang="ar_AR" dir="rtl"`). 

This happens, for example, when your site has English (US) as the default locale and you're in the process of editing some localized content. When editing the arabic content, the `input` and other related tags get the `rtl` attribute properly, but `reboot` nullifies that via CSS.

**Comment by jbalsas** [comment]
I created this [pen](https://codepen.io/jbalsas/pen/ROwdPg) to see the effect and I'm not sure if the issue is there or somewhere else, so we should investigate a bit further.

@marcoscv-work, could you link the original LPS ticket to see how this is surfacing in DXP?

**Comment by pat270** [comment]
@jbalsas @marcoscv-work Thanks for the clarification, I see the issue when there is mixed language content. I think we can override Bootstrap's `text-align: left` with `text-align: inherit`. https://github.com/twbs/bootstrap/commit/09019a8ecdccf61b52681dec3376a88509b4e6a3 is the reason why it was added. This doesn't apply to us and seems outdated even for Bootstrap.
