### ISSUE TITLE
Migrate clayui.com from wedeploy to gh-pages

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1834]
We need to move clayui.com to the gh-pages so we do not get out of the air when Wedeploy goes off the air until we decide to deploy changes of #1712.

**Comment by wincent** [comment]
Just to share my experiences with moving alloyeditor.com — it took about a week because there were two issues:

- We used to host alloyeditor.com on gh-pages, then moved away to We Deploy, and that meant that on moving back GitHub was saying that the custom domain is already used; @jeffreydothan had to contact GitHub support to get them to free up the domain.
- We also had problems enabling SSL: at first the checkbox wouldn't work, so we had to make some random change to enable the checkbox, then it worked.

If you run into the same issues, you can expect a delay, although now that we've seen it once it will be easier for us to solve the next time.

**Comment by matuzalemsteles** [comment]
Thanks @wincent for the information.

**Comment by matuzalemsteles** [comment]
Just a comment on this, our website is already back again.

**Comment by matuzalemsteles** [comment]
I'm closing this once we already have our website up and running again and maintained by gh-pages.
