### ISSUE TITLE
Explicitly defined props and interfaces

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#1953]
There're some components, like clay-checkbox, that should have `disable` prop. Now we can pass this kind of props directly to the components due we're rendering `...otherProps` but... my question is:

Should all this known props be defined as API? For me it's a yes.

Another thing is that I see some props defined inside the component (i.e. `checked` in `clay-checkbox` but is not defined in the Props Interface. Should we define all component props in those interfaces? For me it's also a yes, but I don't know if I'm missing something.

Thanks guys!

**Comment by matuzalemsteles** [comment]
> There're some components, like clay-checkbox, that should have disable prop. Now we can pass this kind of props directly to the components due we're rendering ...otherProps but... my question is:

I think setting all the unknown props are unnecessary when we have `...otherProps` and we extend the base interface with TypeScript. For those who use the component even if they are not using TypeScript, at least in the VSCode it will autocomplete the component props based on the interface and for those who develop the component as well.

> Another thing is that I see some props defined inside the component (i.e. checked in clay-checkbox but is not defined in the Props Interface. Should we define all component props in those interfaces? For me it's also a yes, but I don't know if I'm missing something.

I also find it unnecessary since we are already extending the base interfaces, if we go with that it will be something redundant or we will have to stop using `extends`, which I think would be a bad practice with React and TypeScript.

For example:
```typescript
interface Props extends React.InputHTMLAttributes<HTMLInputElement> {}
```

**Comment by bryceosterhaus** [comment]
I would tend to agree with Matu in that it isn't necessary to explicitly document either of those in the interface because the prop is inferred from the `extends React.HTMLAttributes...`. However, I think you do raise a good question because some of these props are necessary for the functionality of the component. For the example of `checked` from checkbox, technically I think that prop should be required which means we should explicitly declare it on the interface and make sure it is required rather than optional.

So ultimately I think if a prop is required for functionality, we need to explicitly define it in the interface without the `?` flag. However, if its just another prop that is optional from the `extends` then I think we can leave it.

**Comment by matuzalemsteles** [comment]
Hmm, good point. Makes sense.

**Comment by julien** [comment]
I think that what @carloslancha is trying to say is that we should try to expose a clear A.P.I.

I understand what was said about this earlier at least in the context of React and TypeScript.

> it isn't necessary to explicitly document either of those in the interface because the prop is inferred from the extends React.HTMLAttributes.

But since we extend `React.HTMLAttributes` which could possibly be anything in the format `key=value` (or `data-xxx=value`)  that doesn't really let us define a clear A.P.I. and it will make it harder for developers to know how to use our components and which attributes affect the behaviour of the component.

**Comment by matuzalemsteles** [comment]
hey @julien even if the person does not use TypeScript, he can still consult the documentation of Clay, the generator that we will create (react-docgen), it will infer the extends.

But I think even though anyone looking straight at the code still becomes clear when looking at the interfaces when they see an extend `React.HTMLAttributes<HTMLDivElement>`, I know that this component extends the base attributes of a div element with the React exclusive props.

I think if we follow this path, we will be duplicating a lot of interface and documentation unnecessary by our codebase. I do not think we should spend time worrying about it when writing the components.

**Comment by bryceosterhaus** [comment]
@carloslancha in response to your comment here, https://github.com/liferay/clay/pull/1975#issuecomment-491791496.

The reason I made `checked` and `onChange` required is because it is controlled component and without those, the component is not functional in the sense that you can interact with it. If we anticipate allowing users to just render a non interactive checkbox, then you are right we should probably remove those being required. If we do decide we want to let people do that, then we should just revert the commit and go back to using it the props extended from the html interface.

There may actually be some API backing to making those non-required, in the case someone wants to use it "uncontrolled" https://reactjs.org/docs/uncontrolled-components.html

Really just depends if we want to force the "controlled" paradigm, which for me I think is actually a good idea. It'll help narrow how users consume these components and in turn it'll make them much easier to maintain. This also stems from a philosophy I have in preferring a narrow API and force users into a specific paradigm rather than an open API and allow many paradigms.
