### ISSUE TITLE
Disabled state does not write success state over on input field

### ISSUE THREAD

**Issue by NemethNorbert** [liferay/clay#2144]
Hey,

**Reproduction:**
- Create an input field with a disabled checkbox
- Apply success state to the input field (add .has-success) 
- Disable the input field with the checkbox

Expected: The input field disabled state will override the already applied success css

Actual: The input field remain green.

<img width="880" alt="Screenshot 2019-07-01 at 09 02 34" src="https://user-images.githubusercontent.com/31600235/60417013-99b06f80-9bdf-11e9-9d69-004ae9440c2b.png">

Thanks,

**Comment by pat270** [comment]
Hey @NemethNorbert,

I prefer not to add disabled styles for inputs that have been run through the form validator. The `has-success` class should be removed when disabling the input. Is there a stronger argument for adding this?

**Comment by NemethNorbert** [comment]
Hey @pat270,

In a from builder scenario, as we can see in the above picture, a scenario like this can happen. The form validator should only validate fields and decide either it should validate the given field or not. Listening on the disabled checkbox to revert any css coming from validation is out of it's logic scope I believe. However from a CSS specificity perspective, the disabled attribute should still take effect no matter if the field has ben validated onBlur before that or not.
I think making this change would only make clay more robust.

Thanks,

**Comment by pat270** [comment]
The form validator part makes sense, but whoever implemented the checkbox should handle resetting the field to its original disabled state. The screenshot should make more sense. The disabled error state doesn't look correct to me.
<img width="798" alt="with-error" src="https://user-images.githubusercontent.com/788266/60536571-60e5c880-9cbb-11e9-9d92-4ba695d859ea.png">

**Comment by NemethNorbert** [comment]
Yes that does not look right. I agree there is more to the issue, however there are many technologies working together there. I'd say the implementation of the checkbox should be modified to handle at least the error message, but clay-css should still override previous success or error state css attributes with the disabled state.

**Comment by pat270** [comment]
@NemethNorbert
I'm still not convinced that adding this state is a good idea. If I proceed with this, I can use `.has-success .form-control:not(:disabled)` which makes it more specific by 1 CSS class. Devs that have overridden the `.has-success` state via CSS will now have to update their selectors with an extra class or the styles will revert back to the Clay CSS default. 

I can also opt to use `.has-success .form-control:disabled, .has-success .form-control.disabled` and restyle the inputs, but there are a lot of things going wrong in that particular example you showed me. For one, there is a `.disabled` class added to the `input` and `label` that is never removed.

Using `:disabled, .disabled` will always leave the inputs looking disabled. So the only option I have left is to use only `:disabled`, which leaves `<div class="form-control disabled"></div>` looking broken. Granted this is probably not a common case but we do use that pattern in [http://pat270.github.io/lexicon/v2.16.2/content/form-elements-input-groups/#form-control-tag-group](http://pat270.github.io/lexicon/v2.16.2/content/form-elements-input-groups/#form-control-tag-group).

I really don't want to bandaid over this particular issue with CSS because of some failure to properly change state using JS unrelated to the library. With that said if this is something that provides value to our customers or our devs I can add it, but I need more opinions.

@marcoscv-work @matuzalemsteles @carloslancha @diegonvs

**Comment by marcoscv-work** [comment]
Hey guys, 

After a conversation with David Aragones (from Lexicon) and @eduardoallegrini 
I think we should not solve this case by adding styles because it seems that a disabled entry cannot succeed:
https://www.w3.org/TR/html401/interact/forms.html#h-17.12.1

So I think to fix the issue LPS-97281 we should remove the combination of disabled and successful.
To do a double check David has created this task:
https://issues.liferay.com/browse/LEXI-640

In the other hand, it is possible to have a read-only input with successful, so Lexicon will work on the style for this combination:
https://issues.liferay.com/browse/LEXI-636

**Comment by matuzalemsteles** [comment]
Just expressing my opinion also about this, I would possibly go with Patrick, I think this is not a CSS job and seems to be more of a javascript implementation problem, so I would choose to fix this in the implementation rather than in CSS. Doing this in CSS seems like a makeup to correct the problem.

**Comment by pat270** [comment]
Thanks everyone, I'm going to close this. We can re-open or make new issue if we change our mind in the future.
