### ISSUE TITLE
Extensibility for Multi-Select component

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2152]
Conversation originates here, https://github.com/liferay/clay/pull/2123#issuecomment-507420983.

TLDR; how can we easily add extension points for multi-select without customizing the API to specifically for each individual use case. See https://docs.google.com/document/d/1cIx6RkWNbnho_fOSR__3Fp5alIBE_ObhO-jecfXlA9I/edit#heading=h.vtnk7gaj2m17 for extension points in multi-select

**Comment by jbalsas** [comment]
This is a conversation I started with @wincent offline some weeks ago. I don't think there's a lot of room for innovation here.

We probably need to follow a `*Renderer` approach where the Renderer prop can take:
- A component. This works in the case where the developer is "instantiating" the component directly and thus can inject its own component.
- A string referencing a component in a component registry. This covers the case where the component (multi-select) is instantiated somewhere else and the developer is merely adding her renderer and configuring the component without access to the component initialization.

This case would be the same for Tables and other high level components.

**Comment by matuzalemsteles** [comment]
> A string referencing a component in a component registry. This covers the case where the component (multi-select) is instantiated somewhere else and the developer is merely adding her renderer and configuring the component without access to the component initialization.

Hmm, that sounds interesting, I've been thinking something similar a couple of weeks ago as well, but I'm not sure I understand what you meant by the `component registry`... but I think it resembles what I'm thinking.

In high-level components, you typically do not take advantage of `children` because they are configured via props, but at the same time still holds markup rules that people can not touch, maybe that's natural 🤷‍♂️. But we can work on a strategy for the high-level components that need to be touched, for example:

```jsx
<DropDownWithPagination>
  <MyCheckbox override="checkbox" />
  <MyDropDown.ItemList override="item-list" />
  <MyDropDown.Item override="item" />
</DropDownWithPagination>
```

You can replace low-level components or other components within the high-level components, they can still receive the same properties that low-levels are receiving and follow with the idea of ​​keeping a registry of the internal components to replace, the `override` would be used to reference this.

Perhaps in terms of design this does not look so beautiful, but it can soften the creation of several `*renderer` props for some components that may have many.

**Comment by bryceosterhaus** [comment]
> A string referencing a component in a component registry. This covers the case where the component (multi-select) is instantiated somewhere else and the developer is merely adding her renderer and configuring the component without access to the component initialization.

Personally I would probably avoid this type of abstraction. This was one area in soy that I found a lot of people having struggles with since it wasn't explicit how to get the component in the registry in the first place.

My vote would be for a `*Renderer` prop that you would pass a function to or if you are setting a specific element you could add an `elementTag` prop. This is generally the same sort of APIs I see offered in the general react community.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, @matuzalemsteles 

One thing to keep in mind here is the use case. That's the reason I worded them differently and separated. Because they cover different use cases and **we need to support both**. So this is not so much a matter of if but of how.

Imagine a SaaS scenario where your instance of commerce is running on the cloud and you can't deploy applications, only your custom client code. The `CommerceCart` application is deployed and shows the list of products in your cart.

As a frontend developer, you want to provide a specific `ProductRenderer` to render the items in the list. The way I can see this done is:
- The commerce team has thought about this in advance and they have built code around their `<ClayList>...</ClayList>` code so that they could load third party code, figure out what to import from there and pass it down as a renderer prop.
- Our component `<ClayList>...<ClayList>` offers a contract by which the frontend developer can just register a `ClayListItemRenderer` and specify it in plain text. This means that the commerce team didn't need to specifically think about this scenario (or any other where they're using the list component).

Keep in mind that the problem of passing "plain text" configuration is straightforward and needs to be covered in both scenarios. The case of resolving an implementation of a component is the tricky part that would be benefitial to abstract away from the product teams.

/cc @FabioDiegoMastrorilli, @p2kmgcl, @andresfulla, in case you want to offer some insight on what your needs here might be.

**Comment by bryceosterhaus** [comment]
Hmm, this sort of API and abstraction seems to be at a higher level than React.

> you can't deploy applications, only your custom client code

What exactly are you imagining for this? How would you deploy client code, just via osgi module?

Just brainstorming, but I could imagine a configuration for CommerceCart where you select a deployed OSGI module to be the "renderer" for each list item. And then the user would have to create an osgi module that's exporting a function that renders a react component.

**Comment by jbalsas** [comment]
> What exactly are you imagining for this? How would you deploy client code, just via osgi module?

That would be one option, but it won't work in the SaaS model. Deploying an osgi module (at least to our container) still means that you'd be deploying code that potentially runs on our jvm and can affect the system's performance. The goal is to isolate custom code from impacting our infrastructure.

So, imagine you can just provide a list of urls in a config file (or through a UI, like codepen) and we've implemented it so they get added to the `head` of the page. I imagine you would have something like:

```javascript
// MyProductRenderer.js (might need to be served already transpiled)

export default (item) => {
    return (
        <li className="my-company-product-renderer-item">
            {$item.label}
        </li>
    );
}
```

Now imagine you're the Commerce team and you have your `CommerceCart` module. How would that look like?

**Comment by matuzalemsteles** [comment]
Hmm, this seems a little weird in dealing with this in Clay, the concern about this is, Clay follows the Lexicon Design System and the components follow the Clay markup that usually implies how the components will be written, this way they are somewhat tied up when high-level components are built, the low-level approach is to allow teams to customize to fit their needs. If we address this in Clay it creates yet another new concern that is no longer delivering these two approaches and just allowing Customers to change virtually everything from the component, low-levels will not exist for them, only higher levels that are already tied to the products for their needs like Commerce with the `CommerceCart` component.

I see this as something to be deployed in Liferay, the part of component registers, in a lib outside of Clay, maybe Clay can help with the part of creating `*Renderer` props to play on low-level components within a high-level and low-level components to replace its markup, we can use the same approach as in `ClayAutocomplete` which provides the `component` prop that replaces the markup of the component with the prop.

But this seems super interesting but it's still not so clear to me. At VTEX (https://vtex.io/io) they are developing an interesting approach to this part of customization, but there they will create their own serverless infrastructure to create components with React and backend only with GrapqHL that are implemented in Commerce... as if it were a large marketplace...

One more question in relation to all this, will this list of URLs be for Liferay to download these files or to consume it directly?

**Comment by bryceosterhaus** [comment]
I would agree with Matu on this, I think this sort of implementation isn't necessarily a concern for clay. Clay would need to expose an ability to customize what the row of a list looks like, but i think it would likely be the product team of whoever is creating the app that would add the functionality to customize which would internally just add a prop to the table. So for this ticket specifically, we would need to add an API like `itemRenderer` that would allow for custom rendering of each dropdown item. And then for the Commerce idea, I think that would be an issue for the commerce app itself and how they add the ability for a user to upload their own custom code. That make sense?

**Comment by jbalsas** [comment]
Hey guys, thanks a lot for your comments!

Just to clarify, we need to support this. Wether we do more here in Clay or leave more heavyweight to DXP is up to us... but we will need to support it nonetheless. 

I'm just trying to bring this up to see if we can do something over here that would ease our pain over there... I wouldn't want you to have to do a lot of heavy Java coding if we can add some initial support here to make it easier, that's all :)

**Comment by matuzalemsteles** [comment]
hey @jbalsas I understand, I'm just worried if we're not adding a lot of specific things here I think it makes sense that we support with the renderer APIs (we can discuss this in a possible ADR to try to cover use cases ...) to decrease the DXP pain, but I still have concerns about how this registry of components work and how the components of the clients will be consumed...

**Comment by bryceosterhaus** [comment]
>  I wouldn't want you to have to do a lot of heavy Java coding

is this a threat? 😨 

As far as what we can add here, I don't think this would be the place for a registry or anything like that. Best solution I see for this use render functions as props which would allow custom implementations for portal.

**Comment by jbalsas** [comment]
> is this a threat? 😨

Hahahaa... I didn't stop to think it could sound like that 😂 

It's not a threat, of course, but I do want to over-stress the fact that we need to support it so we don't make the decision of offloading this work lightly.

One last time and then I'll leave it as is... when time comes to implement this, we **won't have access to where props are passed** and even when we do, we **won't have access to JS**, meaning code will go through Java and other layers where we can't just pass JS functions around and all we can use are strings to compose something later on.

Isn't there any state of the art for this anywhere in existing libraries?

**Comment by matuzalemsteles** [comment]
I'll add a thought of mine about it, regardless if it's added here or on the portal. I think if it were to be coded in Java we would not have to do this, I might be wrong, but in my view I can not see where Java could help... I think this is not as complex as it can be here, when I talk about adding the APIs and taking the components registration to Liferay.

It seems very strange that we are reinventing the wheel with the system of registration of components being that we can adopt the use of `imports` even being static but also dynamic. For the case of Commerce specifically it seems very strange to create such an implementation. We have many implications that we should think about before going with this.

- Will the component links (transpiled or not) be consumed directly via HTTP or will these files be uploaded in DXP? going to consume HTTP can create many implications, the components will always have to be accessible and stable when you have millions of access, the client will have to worry about that. Also it may happen that the pages take a long time to render because you are making hundreds of requests to different places, just a hypothetical case, but it can happen. I tell you why we can not deploy them on the SaaS infrastructure... like you said.
- Creating a component registry increases the complexity for orchestrating this, so do not just add something here in Clay, developers will not just want to overwrite a DropDown item, they will want to rewrite a CommerceCart that has its own business rules. It turns out we have to raise this registry one level up.
- Requires more documentation not only on Clay level but on the products of its components that can be rewritten, this creates overhead for the product team in thinking about how the components can serve for customers to cover their various cases, they will be creating something not thinking only Lexicon but allowing its components to have flexibility.

Once again, we can adopt in Clay the possibility of replacing the markups with the API's.

```jsx
<DropDown.Menu component=“MyMarkup” />
```

If we are concerned with UI customization in a SaaS environment I think we should rethink our DXP infrastructure rather than swell with more complexity. Maybe it's time to unbind the DXP frontend 🙂...

**Comment by bryceosterhaus** [comment]
> you can't deploy applications, only your custom client code

...

> imagine you would have something like:
> ```js
> // MyProductRenderer.js (might need to be served already transpiled)
> 
> Liferay.registerRenderer('com.my.company.ProductRenderer', (item) => {
>     return (
>         <li className="my-company-product-renderer-item">
>             {$item.label}
>         </li>
>     );
> });
> ```

...

> we won't have access to JS

...

> all we can use are strings to compose something later on.

I'm a bit confused on this hypothetical you are talking about. This doesn't seem overly complex, and also doesn't seem like it even deals with clay. Assuming there is a commerce registry like you mentioned, wouldn't this just fall on commerce's implementation of the `ClayTable`? For example, their code might look like

```jsx
// Commerce app in React, using clay

<ClayTable
     //...
     rowRenderer={Commerce.getFromRegistry('rowRenderer')}
/>
```

and then the _custom client code_ that the user provides might be

```js
Commerce.setInRegistry('rowRenderer', (props) => {
    return (
        <li className="my-company-product-renderer-item">
            {props.label}
        </li>
    );
});
```

All of this seems pretty straight forward since its all just js functions. Clay can keep on being a specific react library, and then whoever consumes clay configures it for their use case. Am I off on something here?

**Comment by jbalsas** [comment]
Hey guys, thanks a lot for bearing with me on this and for keeping a critical mindset. I honestly appreciate you both fighting on this if you're not convinced even if I might sound frustrated :)

I think the best way to see this would be with a real example, so we can let this sink a bit until we can work with the Commerce team and a real DXP case to try to figure out if there's anything we'd like to add to Clay for this case.

@bryceosterhaus 

```javascript
// Commerce app in React, using clay

<ClayTable
     //...
     rowRenderer={Commerce.getFromRegistry('rowRenderer')}
/>

Commerce.setInRegistry('rowRenderer', (props) => {
    return (
        <li className="my-company-product-renderer-item">
            {props.label}
        </li>
    );
});
```

> All of this seems pretty straight forward since its all just js functions. Clay can keep on being a specific react library, and then whoever consumes clay configures it for their use case. Am I off on something here?

It certainly does seem straightforward. For the commerce case, you'd probably want different namespaces for different components and things like that... and same would go for every other team out there, so we'll likely end up with diverging "Registry" implementations with different APIs and levels of support.

Since it's straightforward... couldn't we do something like... `<ClayTableWithRegistry registryNamespace="CommerceCart">`... or something based on the `Context` API where things could be registered and retrieved?

Last time I checked, commerce had around 200 tables... and the rest of DXP around over 300. So, we have 500 tables spanning around 15 different teams that all need to think about a Registry for each one of those table instances if they want to be able to configure the display of cells or rows (which is a pretty common use case). Is there anything we can do to ensure our developers have a nice developer experience and provide extensible components with ease?

**Comment by wincent** [comment]
> Is there anything we can do to ensure our developers have a nice developer experience and provide extensible components with ease?

So I think that's what the `rowRenderer` prop is.

For the specific use case that @jbalsas is talking about though, a registry really does make sense, because as he said:

> we won't have access to where props are passed ... we won't have access to JS

I understand however, the reluctance to couple this registry notion inside Clay itself, as well as the fear that we don't want multiple permutations on the registry idea invented by different teams. Having a context-based API sounds like a nice compromise: adding an extension point that makes Clay more re-usable in these special situations, without having to pollute the prop-based API with stuff that's required for a relatively arcane special case.

**Comment by matuzalemsteles** [comment]
> Hey guys, thanks a lot for bearing with me on this and for keeping a critical mindset. I honestly appreciate you both fighting on this if you're not convinced even if I might sound frustrated :)

Oh no 😳, do not feel like this, I think we are just trying to understand and expose a little of our vision. It does not mean we will not do something like that, but we are seeing our options.

> I think the best way to see this would be with a real example, so we can let this sink a bit until we can work with the Commerce team and a real DXP case to try to figure out if there's anything we'd like to add to Clay for this case.

Hmm yeah, I guess I'm pretty inclined not to add that to Clay, but I think we can test and see real cases... but my big concern is whether we're going to have problems with that in the future, I can imagine hundreds of components that can be replaced at run time ... I do not see this as a good option going on at runtime, it may seem simple to solve this now, but I think we can have many challenges to make it work well in scale (When I say uncouple the Frontend of Java is because these things have become easier... 🙂, mainly for a SaaS environment).

> so we'll likely end up with diverging "Registry" implementations with different APIs and levels of support.

I think when Bryce and I we speak about not adding an implementation of this in Clay, that means we'll offer the props but we'll only have a registry of components being done in Liferay, we do not mean that teams will have to deal with this alone or make your own, we will be offering this registry within Liferay, that implementation would have lived there, just one, anyway people will still have to deal with the component registration APIs to add in their own component implementations.

My thinking on this is:

```jsx
// Commerce... app in React, using clay
// App.tsx
<MyClayTableCustom
     //...
     header={Liferay.getRenderer('com.commerce.table.header')}
     rowRenderer={Liferay.getRenderer('com.commerce.table.row')}
/>

// MyClayTableCustom.tsx
const MyClayTableCustom = ({
    rowRenderer: RowRenderer = MyDefaultRowRender,
    header: Header = MyDefaultHeader,
    ...props
}) => {
   return (
      <Header {...} />
      ...
       <ClayTableWithHighLevel // Maybe
           rowRenderer={rowRenderer}
       />
      ....
     <ClayTable // Other situation but with low-level>
         <ClayTable.Body>
             {items.map(item => (
                 <RowRenderer {...item} />
             ))}
         </ClayTable.Body>
     </ClayTable>
   );
};

// Outside from the Liferay or inside...
Liferay.registerRenderer('com.commerce.table.row', (props) => {
    return (
        <li className="my-company-product-renderer-item">
            {props.label}
        </li>
    );
});
```

> Since it's straightforward... couldn't we do something like... <ClayTableWithRegistry registryNamespace="CommerceCart">... or something based on the Context API where things could be registered and retrieved?

I like the idea of ​​having a record based on Context API, but I'm not sure yet about a `ClayTableWithRegistry`... Probably this context would live on several different trees so probably who would populate the context with the information would be something from the right backend?

So I can imagine something like this based on what I said above:

```jsx
// Commerce... app in React, using clay
// App.tsx

// Maybe we can make a wrapper in `LiferayRegistry` so that it already fetch the backend...
<LiferayRegistry.Provider value={registry...}>
    ...
</LiferayRegistry.Provider>

// Page.tsx any
const registry = useContext(LiferayRegistry);

<MyClayTableCustom
     //...
     header={registry.getRenderer('com.commerce.table.header')}
     rowRenderer={registry.getRenderer('com.commerce.table.row')}
/>

// ...
```

**Comment by bryceosterhaus** [comment]
> `<ClayTableWithRegistry registryNamespace="CommerceCart">`... or something based on the Context API where things could be registered and retrieved?

We could, but I just really don't think it makes sense to put that layer on the clay side of things. IMO, as soon as we start wanting to add very specific DXP related features into Clay, the lines start to blur for the purpose for the library. My goal would be to not blur lines between where clay ends and where Liferay DXP begins. I see the lines drawn as follows...

- **@clayui/*** - ClayCss implementation built in React. Usable anywhere react is consumed. API designed for react applications.
- *DXP* - Platform for modules and apps. Contains logic and features specifically for DXP. (This is where I imagine a registry of some sorts existing, since its purely a DXP need)
- *Commerce(or any other module)* - Module to be run on DXP and utilize DXP features.

Maybe I am wrong for thinking of drawing lines in this manner, but this helps me separate concerns and decide where a feature needs to live.

For example, DXP offers `Liferay.Language.get`, but we don't bubble this up to Clay and say "clay needs to provide all of our supported languages as default." I see this argument similar since we could argue that clay needs to provide all of the translations for "Submit" or "Cancel" and then we provide a `<ClayTranslationContext.Provider value="en" />`. But, the overhead and need for providing translations for everything isn't a necessity for Clay, we just need to enable developers to do that by providing props to customize those values. Similarly how we are providing `rowRenderer`.

> we speak about not adding an implementation of this in Clay, that means we'll offer the props but we'll only have a registry of components being done in Liferay

Totally agree with this, the argument is this registry of sorts shouldn't live in Clay. Its likely a feature we will need in DXP, but instead of pulling it into clay, lets build it as a DXP specific feature and out it in `liferay-portal`.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, @bryceosterhaus, @wincent, I think we can settle this then as:
- We will provide `*Renderer` props APIs where needed
   - Please, double check this is the case specially for list-based components
- We will start with a registry-like feature in DXP to allow external devs to connect renderers to components.

As soon as we get milestone-2 in DXP we can give this a try and see if we missed anything.

@bryceosterhaus, since you opened this... do we need anything else?

**Comment by bryceosterhaus** [comment]
Nothing else needed on my side. I'll go ahead and close this.
