### ISSUE TITLE
ClayDataProvider doesn't work on IE11

### ISSUE THREAD

**Issue by brunofarache** [liferay/clay#2221]
Importing `@clayui/data-provider` fails on IE11.

Error happens in [yallist](https://www.npmjs.com/package/yallist) dependency, in this line:

```js
Yallist.prototype[Symbol.iterator] = function* ()
```

Error in IE11 console is: `Expected '('`.

Generators are not being correctly transpiled to something IE11 understands.

Dependency tree: `#frontend-taglib-clay#@clayui#data-provider#lru-cache#yallist`

**Comment by matuzalemsteles** [comment]
hey @wincent can we add some babel transformer inside the portal, do we have any restrictions? I didn't want to replace `lru-cache` because of this.

**Comment by wincent** [comment]
Sorry about the delay (I was on PTO).

IIRC I believe @julien has mentioned in some other contexts that polyfilling `Symbol` in IE is hard ([here is the link to that](https://github.com/liferay/liferay-frontend-guidelines/issues/53#issuecomment-508029423)).

My personally take on this is that we should try to work through those polyfilling issues if we can so that we can freely use generators, but that may not be something that we can do quickly as it will take a while to iron out bumps and roadblocks.

I would just write an LRU data-structure and use it directly, as it is really incredibly trivial, and I don't think [the cost of adding this dependency](https://bundlephobia.com/result?p=lru-cache@5.1.1) (7.7K, minified) is really worth it. Without exaggeration, you could probably code up an LRU data structure based on a `Map` including tests in about 30 minutes to an hour. For example, [here](https://github.com/wincent/masochist/blob/8ee6fc3704b204adae6dc3ad9baca5108a741637/src/server/LRUCache.js) is one I wrote for my website, and [these](https://github.com/wincent/masochist/blob/8ee6fc3704b204adae6dc3ad9baca5108a741637/src/server/__tests__/LRUCache-test.js) are the tests.

**Comment by wincent** [comment]
And [here](https://github.com/facebook/relay/commit/3f5d799fa8beb5f810f2bd37813674fc22598b74) is another example from a project that I used to work on, which is very similar to the implementation that I just posted.

**Comment by matuzalemsteles** [comment]
Thanks for the explanations @wincent.

> IIRC I believe @julien has mentioned in some other contexts that polyfilling Symbol in IE is hard (here is the link to that).

Oh yeah, I had forgotten about that.

> I would just write an LRU data-structure and use it directly, as it is really incredibly trivial, and I don't think the cost of adding this dependency (7.7K, minified) is really worth it. Without exaggeration, you could probably code up an LRU data structure based on a Map including tests in about 30 minutes to an hour. For example, here is one I wrote for my website, and these are the tests.

Yeah, I had thought of that at first but I didn't want to reinvent the wheel as it has a lot of packages out and it is well used with 18 million weekly downloads, but I will go with the idea of ​​writing LRU for our data provider implementation.

**Comment by nicooprat** [comment]
Late to the party, but I had this issue in a Vue project and fixed it by manually transpiling some dependencies in `vue.config.js`:

```
module.exports = {
  transpileDependencies: [
    'yallist',
    'lru-cache',
  ]
}
```

Hope it can help someone lost in Google searching for this! There might be some similar config in other frameworks.
