### ISSUE TITLE
Labels and inputs on React

### ISSUE THREAD

**Issue by andresfulla** [liferay/clay#2242]
I'm trying to avoid generating random id values for my components while keeping a relationship between a `label` and its `input` elements. For that I tend to use inputs inside labels, which is apparently ok [according to Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Simple_label_example).

The problem is that the labels and `form-group` style breaks. [CodeSanbox example](https://codesandbox.io/s/inputs-inside-labels-8nkcq). In my opinion this pattern should be encouraged in the docs, as it avoids the classic ids collisions.

The CodeSandbox contains a simple proposition.

Thanks!

**Comment by matuzalemsteles** [comment]
hm, surprised that it doesn't work well with the input. In use cases with checkbox they work fine but only if I add utility classes I would be fine if we go with this proposal.

**Comment by wincent** [comment]
Shame that you require both elements to have custom classes for what should be the common case (label wrapping input).

**Comment by matuzalemsteles** [comment]
Yeah, I don't know if there was any problem with that, only @pat270 can say about that.

**Comment by pat270** [comment]
@andresfulla

We abandoned `input` wrapped in `label` because Bootstrap doesn't support it. I think their reason was related to accessibility. It was always better to have a unique `id` with the `for` attribute on `input` and `label` regardless of whether it was wrapped or not.

If you want support for this the markup is going to be similar to your 4th example:

```
<label class="form-control-label">
  <span class="form-control-label-text">My Label</span>
  <input class="form-control" type="text">
</label>
```

I'm also not sure how far the support will go with some of the more complicated form components like `input-group` since block level elements are technically invalid in `label`.
