### ISSUE TITLE
Can we add an option to pass in a custom fetch function to useRecource?

### ISSUE THREAD

**Issue by brunobasto** [liferay/clay#2261]
In portal we have a custom `fetch` function that takes care of authentication and security configurations. If we use `useResource`, none of that will apply and there's no way to change it: https://github.com/liferay/clay/blob/master/packages/clay-data-provider/src/useResource.ts#L153

@brunofarache @matuzalemsteles @jbalsas

**Comment by matuzalemsteles** [comment]
hey @brunobasto,you can pass to `link` an function but will have to deal with url construction and params if needed.

Example:
```javascript
const {} = useResource({
    link: () => Liferay.Util.fetch(...),
});
```

If you follow this path you will lose the benefit of using prop `variables` it will have no effect here.

Another option would be to do the same as `Liferay.Util.fetch`, for now it just adds `credentials: 'include'`, you can pass this through the `fetchOptions` API.

Example:
```javascript
const {} = useResource({
    link: '',
    fetchOptions: {
        credentials: 'include',
    }
});
```

**Comment by wincent** [comment]
> Another option would be to do the same as `Liferay.Util.fetch`, for now it just adds `credentials: 'include'`, you can pass this through the `fetchOptions` API.

The problem with that is the "for now": there is *already* [one other thing it does](https://github.com/liferay/liferay-portal/blob/27800770b780195b90da7e420bd1ee6e67e3f095/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/fetch.es.js#L29) (setting a `x-csrf-token` header), and no guarantee that it won't end up doing more things in the future.

I think we should explore ways to make `Liferay.Util.fetch` usable inside `useResource`, which might be a `fetch` parameter alongside `fetchOptions`, or some other solution.

**Comment by matuzalemsteles** [comment]
Oh thanks @wincent, don't you think passing `link` as a function is not enough? maybe we can pass the `variables` to the link function to maintain the benefit and also improve the caching system.

```javascript
const {} = useResource({
    link: (variables) => Liferay.Util.fetch(baseUrl + variables),
    variables: {...},
});
```

**Comment by wincent** [comment]
Yeah, I think that would work.

For anybody else reading this, this is the code we're talking about:

https://github.com/liferay/clay/blob/91e59e98264511b6e3711b33049318b21267fb68/packages/clay-data-provider/src/useResource.ts#L153-L173

Now that I look at it though, I see the typing for the `link` prop is a bit weak:

https://github.com/liferay/clay/blob/91e59e98264511b6e3711b33049318b21267fb68/packages/clay-data-provider/src/types.ts#L39

We have it typed as `Function | string`, but we assume the function returns a promise because we take it:

https://github.com/liferay/clay/blob/91e59e98264511b6e3711b33049318b21267fb68/packages/clay-data-provider/src/useResource.ts#L170

and end up calling `then()` on it:

https://github.com/liferay/clay/blob/91e59e98264511b6e3711b33049318b21267fb68/packages/clay-data-provider/src/util.ts#L18

**Comment by matuzalemsteles** [comment]
Thanks @wincent, I will mark this as an enhancement and add to our `milestone.3`.
