### ISSUE TITLE
[Discussion] High-level vs low-level component API

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2275]
Opening this to continue discussion from this PR and doesn't get lost, https://github.com/liferay/clay/pull/2240#issuecomment-520930837.

Overall, I think we need to discuss what sort of guidelines or requirements we need to follow when constructing the APIs for high-level components. I think we are starting to run into issues where developers are required to make fairly subjective decisions on the API that a certain high-level component offers. For example, if we have component A and it has a list of basic lexicon interactions, how do we decide what high-level components get created? This is the sort of decision process that we might want to discuss further.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, @matuzalemsteles, thanks for thinking this through and arriving to some compromises to avoid getting blocked.

As @matuzalemsteles says, we speak from experience here. We've failed to gain traction and usage in the past because we've failed to answer some of these questions. I want to think, as @wincent many times points out, that there's probably a sweet spot in between the different approaches where we could stand.

In Clay v2, we've been burned from every possible side:
> Your component is so high level that it doesn't allow me to do anything other than it was designed for

and 

> How come I have to reimplement everything on my own when I only want to tweak a little something on this overly complex component?

and

> I don't want small pieces to build my apps, this should be already provided so I can focus on my features!

and

> I don't want your components, I'd rather implement it all on my own so I have more control!

So, finding the sweet spot might definitely be harder than it seems 😂 

One key issue that I think @bryceosterhaus brought up is that **with little adoption and usage, it's hard for us to understand what's needed**. On top of that, I'll add that we need to go into the teams and work with them side by side to understand how is this being used so we can make better decisions. 

My suggestion would be something like:
- When in doubt, stick to low level components until a real usage is presented.
- Let's prioritize real usage issues so we can keep developers engaged and using Clay v3
- Try to allocate time (in my mind we could allocate up to 20%) to work with teams on new features/reviews/refactors to improve how Clay is used and our understanding of what's needed.

What do you think?

I know you had long conversations about this and I might have missed some key comments, so please, kindly bring them up again here and I promise I'll follow up 🙏 

Thanks!

**Comment by bryceosterhaus** [comment]
Seems like an accurate summary to me and I would agree with all of it. A couple of other things come to mind as well, and some of this might overlap a bit.

### Library vs Product
We also seem to run into the issue of knowing where the library(clay) ends and product begins. From my experience it seems like _Liferay has historically had a tendency to rely more on the library rather than building out the specific request within the product itself_.

Hypothetical example of what I mean, product `A` needs an autocomplete input that has a few unique designs/functionality that differ from the typical library use case. Instead of `A` building out their specific use case, they instead rely on the library to add that use case for their product.

IMO, I think that is why v2.0 got messy and cluttered so quickly. It starts to add specific complexity on the library for a single use case and also slows down product from going ahead.

### High-level requirements

> When in doubt, stick to low level components until a real usage is presented.

I really like this being a guiding principle for future development. We will need to come up with some criteria for what is required for high-level components though, and I think this is where we are getting a bit bottle necked. I could imagine the following be some of the requirements for high-level.

- Component is used in more than one place throughout liferay products.
- Component is not specific to a certain product.
     - For example, if it can only be used within the context of a Liferay instance than its probably too specific.
- Component does not require specificity outside of the lexicon definition
     - We shouldn't hardcode any functionality or markup that is not defined by lexicon.

I'm sure I'm missing others but these are what come to mind.

### high-level API?

We also run into the issue of API patterns and we will need to come up with a way to filter out our own preferences for API so that we can have a uniform and consistent API throughout components. For example, we talked about it in [this PR](https://github.com/liferay/clay/pull/2225#issuecomment-520933811). I think it'd be important for us to have some sort of standard to follow to keep our components consistent throughout.(this may also just be [bikeshedding...](https://css-tricks.com/what-is-bikeshedding/))

### Lastly
> Try to allocate time (in my mind we could allocate up to 20%) to work with teams on new features/reviews/refactors to improve how Clay is used and our understanding of what's needed.

What is the best way to go about this and what teams are actually using clay? I know I would be more than happy to dig into this more with other teams, but I'm not quite sure how we begin to start on this.

> Let's prioritize solving real usage issues so we can keep developers engaged and using Clay v3

This is huge and probably the most important. I would suggest we might benefit from some sort of regular feedback via questionnaire or loop post that teams can chime in and give feedback for the direction we are going.

/end rant

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, thanks for your comments!

### Library vs Product

> From my experience it seems like Liferay has historically had a tendency to rely more on the library rather than building out the specific request within the product itself.

This is a fair assessment. I think we're already taking steps to change this. Starting from Lexicon itself and continuing with us. 

The message is being passed on that Lexicon and Clay provide just what they provide. Both teams take requests from team to add support for additional cases. Those requests should be analyzed on a per-case basis and can be introduced in the core language/library or not. Not being included in them shouldn't mean we don't get to help the teams design and develop them, though 😉 

### High-level requirements

> Component is used in more than one place throughout liferay products.

Sounds good. If you remember, a while back we were talking about the 3-usage rule for when to count a component as general. Not sure if that worked out all that well, but to me, that's still a good guiding principle.

> Component is not specific to a certain product.

Sounds reasonable too. I'd like to make a remark here, though. We can't compare DXP and Analytics and count them both as a certain product. The amount of teams and projects riding on DXP is easily 10 times that of Analytics. So maybe rather than counting in "product" terms, we should think of "apps", or "teams", or "features"? For example, if both the Workflow and Search teams in DXP need something, it would not be fair to say that's just one product and they should both build it on their own.

> Component does not require specificity outside of the lexicon definition

This is key. We should either:
1. Take already validated requests from Lexicon
2. Run things by Lexicon for validation before moving onto implementation

/cc @drakonux

### high-level API?

> We also run into the issue of API patterns and we will need to come up with a way to filter out our own preferences for API so that we can have a uniform and consistent API throughout components. 

That would be great, indeed. Maybe we could start small and:
- Write an initial proposal (markdown)
- Agree on the basis and merge it with our `CONTRIBUTING` section?
- Try to implement some of the proposal through linting rules to help?

### Lastly

> What is the best way to go about this and what teams are actually using clay? I know I would be more than happy to dig into this more with other teams, but I'm not quite sure how we begin to start on this.

I think this is where we can benefit from our `distributed` nature. We already reach out to the different teams in Spain on a weekly basis to provide updates and gather feedback/requests. 

Not sure how much more formal we want to be, but probably a good way to start would be to reach out to those teams in your offices:
- Diamond Bar: Search, ChangeLists
- Recife: Workflow, DDM/Forms, AppBuilder
- Madrid: Echo, Lima, Tango

Just ask them how they're doing and tell them we're available to help them or guide them through development issues. If they have requests they can talk to me and @esanzp so we can coordinate together to allocate some time to them.

> I would suggest we might benefit from some sort of regular feedback via questionnaire or loop post that teams can chime in and give feedback for the direction we are going.

I'm all ears here. If you have any concrete initiative in mind, I'm more than happy to discuss it and get it done!

**Comment by bryceosterhaus** [comment]
Sounds good to me. I agree on most of this. Just a few comments..

> I think we're already taking steps to change this. Starting from Lexicon itself and continuing with us.

Care to share what some of these changes might be? Mostly asking because I don't think I have heard anything about this.

> The message is being passed on that Lexicon and Clay provide just what they provide. Both teams take requests from product teams to add support for additional cases. Those requests should be analyzed on a per-case basis and can be introduced in the core language/library or not. Not being included in them shouldn't mean we don't get to help the teams design and develop their requests, though

Seems like we might need a concrete workflow for adopting requests from teams. On one hand, as a library, we need to have a focused goal on what we deliver and have guidelines of what falls on us. On the other hand, we are giving a pretty open door to teams to have us develop their feature requests. One way to accomplish this might be establishing some sort of singular vision for Clay such as "Clay components are a React implementation of clay-css". That way we have a grid to filter requests. If we don't have a grid to filter requests, it ends up being whoever yells the loudest or is most adamant about their request. Or perhaps we even have Lexicon designers be the ones to create feature requests for Clay, since they are the ones defining the interactions and designs.

> Write an initial proposal (markdown)

Main question here is sort of a "where do we start?" Is there any sort of API design system within the react community we might be able to leverage? I could see this being either too granular or too high-level.

**Comment by jbalsas** [comment]
> Care to share what some of these changes might be? Mostly asking because I don't think I have heard anything about this.

@drakonux announced the [change in strategy for Lexicon](https://loop.liferay.com/home/-/loop/feed/19233439)

> Seems like we might need a concrete workflow for adopting requests from teams. On one hand, as a library, we need to have a focused goal on what we deliver and have guidelines of what falls on us. On the other hand, we are giving a pretty open door to teams to have us develop their feature requests

As we said, Clay's main goal is to make it possible to implement Lexicon. That includes css, low-level components, high-level components (as we see fit) and accompanying helpers (hooks, types, tooling...) to make the developer experience satisfactory.

While being flexible, **we should only include in Clay things that have been approved by Lexicon**. Technically, we will only take requests from Lexicon. Lexicon will only work on real team requests. 

So, as I wrote above, I think we should either:
1. Take already validated requests from Lexicon
2. Run things by Lexicon for validation before moving onto implementation

And to repeat again. Not adding something to Lexicon or Clay doesn't mean we can't chip in and implement it straight into the teams code-bases if they need our help and request it. We're here to help them succeed and deliver, one way or another :)

> Main question here is sort of a "where do we start?" Is there any sort of API design system within the react community we might be able to leverage? I could see this being either too granular or too high-level.

I'm at a loss here. If you guys have any idea, I'd be happy to hear it. I think this might be something worth discussing while we're together in Spain... @matuzalemsteles, we might need to call you 😉

**Comment by bryceosterhaus** [comment]
> we should only include in Clay things that have been approved by Lexicon.

👍 👍 👍 👍 

> Not adding something to Lexicon or Clay doesn't mean we can't chip in and implement it straight into the teams code-bases if they need our help and request it.

definitely agree. Especially when i'm pushing to someone elses code base 😉 


> worth discussing while we're together in Spain

Yeah I think this would likely be best done in person. So I am okay with waiting until then.

**Comment by bryceosterhaus** [comment]
Closing since this seems to be resolved. We can re-open if this discussion is needed again.
