### ISSUE TITLE
Importing convention for High Level Components

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2304]
We need to define a guideline for importing files when creating a high-level.
There are two different strategies:

```jsx
import Cell from '../src/Cell';

<Cell ...
```

and

```jsx
import ClayTable from '../src/index';

<ClayTable.Cell ...
```
Which approach is more adequated?

**Comment by wincent** [comment]
It seems that if you are importing something from your own package, you should be grabbing it directly, to avoid the unnecessary circularity of the kind removed in https://github.com/liferay/clay/pull/2301. The `index` file is really just a way of exposing the public API to external-to-the-package consumers (and because the `package.json` needs to point at something from its "main" property), not internal-to-the-package ones.

On the other hand, if you're grabbing a high-level component from another package, it seems entirely appropriate to access it via the package's "main"/`index`.

**Comment by jbalsas** [comment]
Yeah, I would also try to avoid unnecessary steps for local imports:

```
import Cell from './Cell';
```

rather than

``` 
import Cell from '../src/Cell';
```

Then, as @wincent mentioned, for external dependencies, I would prefer to just take on the default convention:

```
import ClayTable from 'clay-table';
```

rather than

```
import ClayTable from 'clay-table/src/index';
```

**Comment by bryceosterhaus** [comment]
We could probably assume the rule that `index` is entirely an external API and nothing within the package itself should reference `index` unless its a test.

**Comment by matuzalemsteles** [comment]
Are we ok with that? I will close this and if you still have problems with this feel free to reopen.
