### ISSUE TITLE
Create Popover and Tooltip

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2338]
This is a similar component to Modal, maybe it needs to be written to be called via Context, we have to evaluate if it is necessary to create a low-level for it and do the same as we did for Modal.

cc @bryceosterhaus

**Comment by jbalsas** [comment]
FYI, we have this long-standing request by @drakonux about the tooltip behaviour: https://github.com/liferay/clay/issues/1988

Might be good to implement this on v3 to stay on his good side 😉

**Comment by wincent** [comment]
> we might want to leverage some sort of HOC that wraps the app. We could then add an event for hover on any element that matches a certain selector and automatically add a tooltip via the title attribute.

I'm curious about why you'd need a *HOC* for this, and whether it would cover all the use cases. For example, will your event listener attach to the `document.body` so that it can see events on arbitrary elements (given that a `React.createPortal()` call could effectively mount an element anywhere)? And if it does that, it feels like you need context, may as well make a hook for it, may as well rely on React's event delegation etc, and I am not sure what a HOC would give you.

**Comment by drakonux** [comment]
> FYI, we have this long-standing request by @drakonux about the tooltip behaviour: #1988
> 
> Might be good to implement this on v3 to stay on his good side 😉

Please Clay come to the Light Side :D 

Yeah guys, please take a look on the [Time Delay ticket for Tootlips](https://github.com/liferay/clay/issues/1988). Lexicon Team agrees with the proposal I made :P 

- Clay Tooltip should offer the option to set the initial time delay (to cover extreme / non-default scenarios)
- The default initial time delay increases from 0 to 0.5s 
- We would like to hear your opinion about the alternative ideas proposed

**Comment by matuzalemsteles** [comment]
hey @drakonux this is totally valid. @bryceosterhaus is already working on this in #2347
