### ISSUE TITLE
Change  Input: read-only style

### ISSUE THREAD

**Issue by DuuriimaaBargaid** [liferay/clay#2425]
**Description**
Right now the style of input "read-only" does not offer enough visual differentiation with respect to regular input. On the other hand, the slight difference between the different gray levels may cause that in many cases the read-only is identified as an input with a wrong background color.                    
Therefore we have decided to re-design input: read-only

**Deliverables**
![Read only](https://user-images.githubusercontent.com/36294241/64770528-a2adad80-d54d-11e9-87a7-f91565a4b0b1.png)

[Jira](https://issues.liferay.com/browse/LEXI-559)
[mockup](https://www.figma.com/file/IU2cGjUw5aTGggEe3Ov5E6/Change-read-only-style-LEXI-559?node-id=1%3A61)
[Documentation](https://docs.google.com/document/d/1YZJdiYNBbWX--ZS5OixY-vn5cYSO9nDzNscAjvd6Njs/edit?usp=sharing)

**Comment by drakonux** [comment]
Hi guys, I noticed that the image within this thread is outdated. In the LEXI ticket was ok. Sorry because we didn't keep you posted.

![read-only-input](https://user-images.githubusercontent.com/21216422/68656693-97b5d000-0532-11ea-8049-9d027954619b.png)

There was some mistakes with the focus. Could you check the implementation? 🙏
