### ISSUE TITLE
Verify clay-alert for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2438]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by diegonvs** [comment]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
> Yes!
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
> Yes
- [] Does component accept a ref? Is the ref value what you would expect?
> Nope, was added in https://github.com/liferay/clay/pull/2484
- [x] Does this component allow for different translations?
> Yes
- [x] If this is a form element, does it accept a name attribute?
> It's unnecessary
- [x] Were you able to find documentation for this component? Was it clear?
> Yes

Additional Questions:

Is there anything about the public API that you would change?
> Instead of `variant` that only has a unique value(stripe), we could create a new property called `stripe` for it.

A pull request was sent here(**BREAKING CHANGE**): #2485

Is the naming of the available props clear? Nope, #2485

**Comment by eduardoallegrini** [comment]
I found these points: 

- `spritemap` has the same problem of the [icons](https://github.com/liferay/clay/issues/2448#issuecomment-532220618)
- the value `stripe` could be confusing because its [meaning](https://www.lexico.com/en/definition/stripe) and [common usage](https://getbootstrap.com/docs/4.3/components/progress/#striped)
- setting `variant="stripe"` I get a different result from the expected one
![current](https://user-images.githubusercontent.com/46778114/65057776-6de98e00-d973-11e9-9695-ac1e0fcd4001.png)
![expected](https://user-images.githubusercontent.com/46778114/65057856-8c4f8980-d973-11e9-9aad-3ddb0f0c44d8.png)
- Maybe we should add a [code example](https://github.com/liferay/clay/blob/12eed9e1f095017952c251ca33e5eae39425322f/packages/clay-alert/stories/index.tsx) of how to use the API, particularly the `<ClayAlert.ToastContainer>`

**Comment by eduardoallegrini** [comment]
- The icon placeholder when we are using [no-standard colors (css tab)](https://next.clayui.com/docs/components/alerts.html)
![image](https://user-images.githubusercontent.com/46778114/65138856-f0be2780-da0b-11e9-9f3a-e0fc1f973453.png)

- The HTML of the stripe version has an extra `.container` but I’m not able to tell if it’s correct because we don’t have it [documented yet](https://issues.liferay.com/browse/LEXI-687)
- I’m not sure about the combination of `<strong>` + `.lead` + `custom-css` to create the title. We can achieve the same result with
```html
<div class="alert alert-danger" role="alert">
 <span class="alert-indicator">
  <svg class="lexicon-icon lexicon-icon-exclamation-full" role="presentation">
   <use xlink:href="icons.svg#exclamation-full"></use>
  </svg>
 </span>
<strong class="mx-1">title custom</strong>
This is a stripe alert
</div>
```
or if we don’t want to use utility classes
```html
<div class="alert alert-danger" role="alert">
 <span class="alert-indicator">
  <svg class="lexicon-icon lexicon-icon-exclamation-full" role="presentation">
   <use xlink:href="icons.svg#exclamation-full"></use>
  </svg>
 </span>
<strong class="alert-title">title custom</strong>
This is a stripe alert
</div>
```
[Clay css, line 16 and 45](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_alerts.scss#L16)
```scss
// + .lead
+ .alert-title {
 margin-left: $alert-lead-spacer-x; //5px
}

// .lead 
.alert-title {
 right: $alert-lead-spacer-x; //5px
}
```

**Comment by bryceosterhaus** [comment]
@eduardoallegrini thanks for the feedback! I was following some of the examples seen here, https://pat270.github.io/lexicon/v2.16.2/content/alerts/.

**Comment by bryceosterhaus** [comment]
Going to release this since this is the current implementation we have from clay-css and it looks to match up with the lexicon definition on lexicon's site. If we decide to make changes to the css, we can update this component at the same time.
