### ISSUE TITLE
Verify clay-charts for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2441]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.

As far as I could see we're not taking this into account ... yet.
As discussed in other "review" issue tickets, it might be better to come up with some common patterns concerning these extra attributes before adding anything we might end up reverting.

> Is there anything about the public API that you would change?

Not at the moment. 

> Is the naming of the available props clear?

As far as I'm concerned that's a "yes", because it's just of matter of reading the billboard.js documentation and examples.

I've also had other people ask me about these charts and their usage (with the previous metal+soy version) and I usually suggested to look at the billboard.js documentation too.
I don't know how to do this in the most efficient way but it would be nice to specify that this is "just" a thin wrapper on top of billboard.js because it sometimes seems that wasn't the expectation. @bryceosterhaus @matuzalemsteles what do you guys think?

**Comment by bryceosterhaus** [comment]
Yeah you are right, we could do a better job at pointing to the billboard docs. I haven't look at charts in awhile, but I think we might benefit from going through it one more time and trying to line of the API to be as close to billboard as possible and any unnecessary logic on our end.

**Comment by julien** [comment]
@bryceosterhaus yes that sounds like a good idea too - I haven't seen to much unnecesarry stuff too far.

**Comment by bryceosterhaus** [comment]
@julien I went ahead and added an additional prop for providing attributes to the charts container element. Let me know if this seems appropriate https://github.com/liferay/clay/pull/2514. I didn't use `...otherProps` since I wanted to leave that open for other billboard config and API.

**Comment by julien** [comment]
@bryceosterhaus yes that looks appropriate to me. Thanks.
