### ISSUE TITLE
Verify clay-date-picker for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2445]
- [ ] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by kresimir-coko** [comment]
I'll verify this one, so assign it to me.

**Comment by kresimir-coko** [comment]
> Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.

Yes, no problems implementing.

> Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.

No, neither the `aria-*` or the `title` attribute gets rendered.

> Does component accept a ref? Is the ref value what you would expect?

It doesn't complain about it but it doesn't do anything when `ref` is assigned to it.

> Does this component allow for different translations?

It doesn't need these because it's all numbers.

> If this is a form element, does it accept a name attribute?

Not a form element.

> Were you able to find documentation for this component? Was it clear?

Yes, documentation was clear except for the following:
1. Needed more dependencies than just ClayDatePicker which is not documented, but those might just get automatically downloaded and added in the usual environment
2. `useState` is undefined - examples in the documentation should probably show the full code needed to get the demo working

> Is there anything about the public API that you would change?

There are a few things that aren't intuitive about this component in my mind:
1. Accepts letters. Should accept only numbers
2. You can input the date yourself, which doesn't work intuitively.
2.a I thought it would strictly format the date and time, letting the user input a valid 4 number year, 2 number for month and day, and not gibberish that it allows right now

> Is the naming of the available props clear?

Yes.

**Comment by diegonvs** [comment]
> Needed more dependencies than just ClayDatePicker which is not documented, but those might just get automatically downloaded and added in the usual environment

Fixed by: https://github.com/liferay/clay/pull/2512

> `useState` is undefined - examples in the documentation should probably show the full code needed to get the demo working

`useState` is a React Hook, imported previously :)

> Accepts letters. Should accept only numbers

You can create a custom hook like this code example: 

```tsx
const ClayDatePickerWithState = (props: {[key: string]: any}) => {
    const [value, setValue] = useState<string | Date>('');
    const useDateMask = (value: string): string => {...};
    return (
        <ClayDatePicker
            {...props}
            onValueChange={setValue}
            spritemap={spritemap}
            value={useDateMask(value as string)}
        />
    );
};
```

**Comment by diegonvs** [comment]
> 2.a I thought it would strictly format the date and time, letting the user input a valid 4 number year, 2 number for month and day, and not gibberish that it allows right now

This depends on the Intl, is better to keep this treatment for the developer.

**Comment by kresimir-coko** [comment]
@diegonvs 
> You can create a custom hook like this code example:

Sure you can create a custom hook, but to me this current implementation feels wrong, it's like having a component for inputting a phonenumber, and phonenumber only, but being able to input a string with length of 420 `letters` in it instead of a range of `numbers` with a length of 2-20ish.

You can create a custom hook for the phonenumber component too to combat my example, but shouldn't  the default implementation do it's best to do the job it want's to do?

**Comment by eduardoallegrini** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics** 
  - Minor accessibility issue: the date inserted through the input field does not update the calendar
