### ISSUE TITLE
Verify clay-icon for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2448]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics** 
  - **It is not blocking**, but there are some doubts about the use of an icon alone, not covered, without context, some cases we could need to remove the `role ="presentation"` and use `role="image"` with `alt=""` attribute. Right now, `role="presentation"` is fine

**Comment by eduardoallegrini** [comment]
I tried this component following the [Clay website](https://next.clayui.com/docs/components/icon.html) but I didn’t know how to set and import the spritemap

> Add `const spritemap = '[path-to-the-sprite]/sprite.svg';` to your code, after import React from 'react';

> Download and import the `sprite.svg` into the `public` folder of your project (if you are using the app created by the `npx create-react-app [app-name]`)

We definitely have to write what `[path-to-the-sprite]` is and where to download the `sprite.svg`.

I took it from the [Clay website repository](https://github.com/liferay/clay/blob/master/next.clayui.com/static/images/icons/icons.svg) but I'm not sure if it's right.

Also
> Add `import ClayIcon, { ClayIconSpriteContext } from "@clayui/icon";` to your code, after import React from 'react';

Instead of

> Just import `ClayIconSpriteContext` from the package and use your provider.

Could be better

**Comment by bryceosterhaus** [comment]
updates: https://github.com/liferay/clay/pull/2493
