### ISSUE TITLE
Verify clay-label for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2449]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by kresimir-coko** [comment]
I'll take this one, feel free to assign it to me when you get the chance.

**Comment by kresimir-coko** [comment]
> Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.

I was able to easily implement a demo, there were no problems or "gotchas"

>   Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.

The component does accept additional HTML attributes, and they are present as attributes in the rendered component.

>  Does component accept a ref? Is the ref value what you would expect?

Yes, it accepts a ref and the value is expected.

>  Does this component allow for different translations?

I'm not sure, but since it accepts a custom text I can draw a conclusion that it does allow in a similar manner that Soy did with the `msg` tag

>  If this is a form element, does it accept a name attribute?

Nope, not a form element

>  Were you able to find documentation for this component? Was it clear?

Documentation was clear apart from the fact if it supports localization or not.

> Is there anything about the public API that you would change?

Nope, it seems simple enough while supporting all the needs of this simple component

> Is the naming of the available props clear?

Only one of them is specific to this component , `displayType`, and it's purpose is clear
