### ISSUE TITLE
Verify clay-list for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2455]
- [ ] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by kresimir-coko** [comment]
I'll test this one so assign it to me when you're able.

**Comment by kresimir-coko** [comment]
>  Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.

The only hiccup I had was the fact that in order to get it working I needed to add more dependencies than just ClayList which are probably automatically downloaded when doing yarn install

>  Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.

Yes, the aria attributes get rendered correctly

>  Does component accept a ref? Is the ref value what you would expect?

No, it does not because it is a function component

>  Does this component allow for different translations?

I'm not sure, but since it accepts a custom text I can draw a conclusion that it does allow in a similar manner that Soy did with the `msg` tag

>  If this is a form element, does it accept a name attribute?

Not a form element

>  Were you able to find documentation for this component? Was it clear?

Yes, the documentation was easy to find and follow.

> Is there anything about the public API that you would change?

Perhaps explain what some of these options actually does - http://prntscr.com/p7oxx7
For example, what does "Flag to indicate if the `list-group-item-action` class should be applied." exactly mean, or well, what does `list-group-item-action` class change about the element.

> Is the naming of the available props clear?

Yes

**Comment by eduardoallegrini** [comment]
- [x] **HTML**
- [x] **CSS**
- [ ] **Accessibility basics** 
  - `.quick-action-menu` is not accessible with keyboard

![image](https://user-images.githubusercontent.com/46778114/65311717-407a2b80-db91-11e9-8734-7be85bc2c186.png)

**Comment by matuzalemsteles** [comment]
@eduardoallegrini I open an issue so we don't miss it.
