### ISSUE TITLE
ClayModal, how to close it properly

### ISSUE THREAD

**Issue by julien** [liferay/clay#2553]
I've got a question regarding the new `@clayui/modal` component.

I've set up an example in codesandbox [here](https://codesandbox.io/embed/claymodalexample-koiiy?fontsize=15) and I'd like to know what I doing wrong.

If you look at the example and click on the "Close Me" button, you'll notice that a warning is displayed in the console. 

Note that, this warning only happens **once**, even if you have multiple modal components in your "app".

This wasn't happening before `3.0.0`.

 I also commented [this](https://github.com/liferay/clay/blob/d0a2e3659a8b0f56f02bc3a2ca9fc2c35ccfe6ad/packages/clay-modal/src/useModal.tsx#L39) line (in my local `node_modules` directory) and the warning disapears.

Any help is appreciated, thanks.

**Comment by diegonvs** [comment]
Yes, this is weird. Needs more investigation but We found a temporary walkaround. If you move `useModal` from the Modal component to your App component this error doesn't appear more. https://www.diffchecker.com/3AXpWjOT

**Comment by bryceosterhaus** [comment]
First off, thanks for the codesandbox, always a huge help.

Hmm I think it might have to do with the `useModal` hook being in a component that is unmounted at the same time as the modal itself. I refactored it slightly [here](https://codesandbox.io/embed/claymodalexample-l6pjj?fontsize=14) so that `useModal` exists outside of that mounted component, and it doesn't seem to error.

However, this does seem like a bug. I would have thought that line wouldn't even run since it should be cleared when the hook is unmounted here at this line. https://github.com/liferay/clay/blob/d0a2e3659a8b0f56f02bc3a2ca9fc2c35ccfe6ad/packages/clay-modal/src/useModal.tsx#L64

I'll label this as an issue and we can look into it.

**Comment by bryceosterhaus** [comment]
looks like me and @diegonvs were both looking at the same time lol

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus, @diegonvs yeah I think we have to also analyze that even correcting this, if this case would be the most recommending to close the modal. The hook may be lost every time the component is unmounted at the same time as Modal, due to the use of the above ternary in the example. For me it makes more sense for the hook to be out of ternary since it is Modal's controller, it needs to be listening to Modal's changes since it is `observer`.

**Comment by julien** [comment]
Thanks to all for the quick reply.

@bryceosterhaus based on your updated example moved the `useModal` hook into the parent component (the one that renders the modal component) and it did indeed remove the warning so thanks for the fix.

**Comment by julien** [comment]
Hi again,

I'm able to fix most of our current use cases by moving the `useModal` hook inside the modal's parent component, but what I haven't been able to do is use this in tests - We're currently using `react-testing-library` and I can't see how I could "mock" this inside my tests. Just wanted you to be aware of this because the modal component is widely used in various applications.

**Comment by julien** [comment]
Just a(nother) quick update, I finally managed to mock the observer in the tests with this code

```javascript
const observer = {
  dispatch: (type) => {},
  mutation: [1, 1]
};
```

It's a big **ugly** but it works ;)

**Comment by matuzalemsteles** [comment]
@julien Thanks for bringing this up, can you give us some context in the tests?

> Just a(nother) quick update, I finally managed to mock the observer in the tests with this code

haha please keep this at seven keys just for you 😂. This is an API that I don't want people to know how it works. 😅

**Comment by matuzalemsteles** [comment]
Thanks a lot again @julien! I talked a little with Julien in Slack, so these are some of the thoughts I had quickly so we could encourage some practices and try to remove some that were already created.

- For testing, we can encourage the practice of creating a wrapper (`<ModalWithState />`) on top of `useModal` and Modal, as we do in our tests. We might want to document this on clayui.com
- For the correct use of `useModal`, we can better document this on clayui.com and address the use cases.
- We know when Modal is really visible, we can create an API to not encourage direct access to `observer`, maybe dispatch a warning when someone tries to access it directly.

**Comment by victorg1991** [comment]
hey @matuzalemsteles I had to use the observer directly because I needed to focus one element when the modal is visible. It seems that the modal is rendered twice before it is first shown (probably due to the React portal stuff) and the only reliable way of knowing when the modal is visible is tracking the observer mutation property

Is there another way to handle this case?

**Comment by matuzalemsteles** [comment]
hey @victorg1991 no problem about that for now, you could take some approaches:

- Create the expert Modal without the `useModal` hook and without the conditional rule attached to the component and add a` useEffect` with dependency `[]` so that it runs only on that component mount, with focus logic.

```jsx
const ModalWithFirstFocus = ({children, ...otherProps}) => {
	useEffect(() => {
		// Add focus logic
	}, []);

	return (
		<ClayModal {...otherProps}>
			{children}
		</ClayModal>
	);
};
```

Let's add `useModal` props so you can know when the Modal content really became visible. Both renderings happen due to two changes, the initial render that will cause the animation and when the animation finishes another render that is to show the content. This was necessary due to some issues reported here #2342.

**Comment by bryceosterhaus** [comment]
Going to close. If you still need questions answered I can re-open.
