### ISSUE TITLE
Add a Toggler property for ClayInput type="password"

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2583]
Hey folks, What do you think about adding a new API for ClayInputGroup like this: 

```tsx
<ClayInputGroup password>
	<ClayInput type="password" />
	<ClayInputGroupItem toggler={<ClayIcon symbol="view"/>}>
</ClayInputGroup>
```

/cc @matuzalemsteles @bryceosterhaus

**Comment by matuzalemsteles** [comment]
I think this may be more work than it sounds, because we will also have to control the visibility of the values ​​in `ClayInput`, we would have to create an abstraction to make it happen and the way to use `<ClayInput.GroupItem />` (ClayInputGroupItem) It makes it a more responsible component and shies away from its essence by having to add a unique use case.

I see this could be a high level but we would also have to evaluate if it is a common case within the Portal, otherwise we will bloat our code base.

People could do the same above with the components we deliver today and with less abstraction.

```jsx
const InputWithPassword = () => {
	const [visible, setVisible] = useState(false);

	return (
		<ClayInput.Group>
			<ClayInput type={visible ? 'text' : 'password'} />
			<ClayInput.GroupItem>
				<ClayButtonWithIcon
					symbol="view"
					spritemap={spritemap}
					onClick={() => setVisible(!visible)}
				/>
			</ClayInput.GroupItem>
		</ClayInput.Group>
	);
};
```

**Comment by matuzalemsteles** [comment]
I am closing this since we are not going to work on it yet, we will reopen when we reconsider.
