### ISSUE TITLE
CheckboxWithGroup makes sense?

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2660]
Would be a good a idea add a high-level component called `CheckboxWithGroup` that we can return the selected checkboxes on a custom event(e.g `onChange`)?

**Comment by diegonvs** [comment]
After some internal conversations, we(me and @matuzalemsteles) decided to create a component like `ClayRadioGroup` for wrapping `ClayCheckbox` components with a internal state for handling value changes inside wrapped checkboxes:

```tsx
<ClayCheckboxGroup
  inline
  onChange={value => console.log(value)} //value is an array with selected checkbox values
  initialValues={initialSelectedValues} 
>
  <ClayCheckbox value="opt_1" />
  <ClayCheckbox value="opt_2" />
  <ClayCheckbox value="opt_3" />
</ClayCheckboxGroup>
```

**Comment by bryceosterhaus** [comment]
hmm, im not really sure about this. The reason we have a RadioGroup is because the components are directly related to one another and the parent controls which is selected, you should only have one radio selected. For the case of checkboxes, I dont think it makes sense to have a parent controlling and listening to the values of the checkboxes since all boxes can be checked with no issue,

**Comment by bryceosterhaus** [comment]
closing for now, will reopen if we decide to come back to this.
