### ISSUE TITLE
ClayButton: Wrong focus style in buttons that are together

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#2780]
## What are the steps to reproduce?
I saw the documentation (https://clayui.com/docs/components/buttons.html) and this is actually happening in ClayButton.

<img width="725" alt="Screenshot 2019-12-11 at 11 19 20" src="https://user-images.githubusercontent.com/15845466/70613052-4f103600-1c08-11ea-9cf9-e762a7b9de0b.png">

## What is the expected result?
Focus style works well and the buttons do not appear to be under each other.

Thanks :)

/cc @marcoscv-work @eduardoallegrini @drakonux

**Comment by eduardoallegrini** [comment]
Since we are using the `box-shadow` property to create the focus status and it doesn't occupies the space of the border this behavior is expected in CSS.

https://codepen.io/eduardoallegrini/pen/yLyOqbE

Bootstrap have a similar issue but we can notice it because their buttons are `inline-block` elements by default (example 1)

If you put them inside a `display:flex` container we can see the same problem. (example2)

If we use a `.btn-group` container, it will work fine, because the class is adding `z-index: 1` to the focus status of the element but at the same time it's changing the `border-radius` (example 3)

**Comment by pat270** [comment]
The way it appears on the screenshot is exactly how it's supposed to look when you render multiple buttons next to each other with no white space between them. Add a space between each `<ClayButton>` or use the pattern:
```
<div class="btn-group">
    <div class="btn-group-item">
        <button class="btn btn-primary" type="button">Primary</button>
    </div>
    <div class="btn-group-item">
        <button class="btn btn-secondary" type="button">Secondary</button>
    </div>
    <div class="btn-group-item">
        <button class="btn btn-link" type="button">Btn Link</button>
    </div>
</div>
```

**Comment by matuzalemsteles** [comment]
With components you can wrap the buttons inside a `<ClayButton.Group />`, by default it will group the buttons together and if you just want the spaces between the buttons, add the `spaced` prop to `ClayButton.Group`.

```jsx
<ClayButton.Group spaced>
      <ClayButton>{"This"}</ClayButton>
      <ClayButton displayType="secondary">{"is"}</ClayButton>
      <ClayButton>{"a"}</ClayButton>
      <ClayButton displayType="secondary">{"button"}</ClayButton>
      <ClayButton>{"group."}</ClayButton>
</ClayButton.Group>
```

**Comment by dgarciasarai** [comment]
@matuzalemsteles I used your solution, but the buttons have a lot of space between them for our use case. Any help?

<img width="877" alt="Screenshot 2019-12-13 at 11 55 18" src="https://user-images.githubusercontent.com/15845466/70796313-39cf0f00-1da2-11ea-9267-3000c86c100f.png">

**Comment by matuzalemsteles** [comment]
I'm not sure but some inline item utils can help you with that. https://clayui.com/docs/css/utilities/inline-item.html

**Comment by pat270** [comment]
@dgarciasarai can you use buttons like in the initial post and just insert a space between?
```
<ClayButton displayType="secondary">{"1"}</ClayButton>{' '}
<ClayButton displayType="secondary">{"2"}</ClayButton>
```

**Comment by dgarciasarai** [comment]
Hey @pat270, you're solution doesn't work. I can add a `className="mr-1"` in the first button or add `<span>&nbsp;</span>` but I think it's not the best solution. If I add the space between, and then you fix it in Clay, I have to go back and remove it. I think this should be fixed in ClayButton.

**Comment by matuzalemsteles** [comment]
I'm not sure if it would be a problem for the ClayButton component, it is a standalone component and should not deal with it. You will probably have to deal with button spacing using pure HTML to do the expected, otherwise @pat270 would have to provide us with some utilities to handle different spacing in `<ClayButton.Group />`. @pat270 do you think this would be interesting?

**Comment by pat270** [comment]
> If I add the space between, and then you fix it in Clay, I have to go back and remove it.

@dgarciasarai I'm pretty sure I won't add a workaround for no space because I can't detect it via CSS. Any white space between buttons will work e.g., tab, space, newline or pass in utility like you mentioned. There were margin and padding utilities merged recently that don't have the `!important` flag. The class names are the same as Bootstrap's except they are prefixed with `.c-` e.g., `.c-mr-1`.

**Comment by dgarciasarai** [comment]
In the end, I added a little space between buttons to fix the reported bug regarding the focus style: https://issues.liferay.com/browse/LPS-105624. Thanks.
