### ISSUE TITLE
ClayModal: Additional components in header

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2844]
# Context
Reviewing the new features from **team-echo** for Page Collections. I've found they plan to use a simplified version of a [MultiStep](https://storybook.clayui.com/?path=/story/components-claymultistepnav--low-level) component in a modal window aka wizard. 

![Multistep simplified](https://user-images.githubusercontent.com/21216422/72280230-28468480-3638-11ea-9195-d6972856ff7a.png)
_Proposal not implemented for A/B testing_

# What is your questions? 

1. Does the [Clay Modal](https://clayui.com/docs/components/modal.html) component allow add additional content to its header?
2. Does **team-echo** be able to build this component using the [Clay Modal](https://clayui.com/docs/components/modal.html)? or should we create a high-level component to cover this modal window with steps?

Kind regards,
David

**Comment by bryceosterhaus** [comment]
Currently it is not possible to add this sort of functionality to either the high or low level components. We would need to add some additional markup to `clay-css` to allow for this change. 

Typically for a multi-step in a modal, I have seen this pattern defined by lexicon https://liferay.design/lexicon/core-components/forms/multi-step-form-simplified/

**Comment by pat270** [comment]
From the Clay CSS side of things there is no pattern for that, but the markup below:
```
<div class="modal-header">
    <div class="autofit-row autofit-row-center autofit-float">
        <div class="autofit-col autofit-col-expand">
            <div class="autofit-section">
                <div class="modal-title" id="clayLargeModalLabel">Modal Title</div>
            </div>
        </div>
        <div class="autofit-col">
            <div class="autofit-section">
                <div class="text-truncate">Step 1 of 2 / <strong>Details</strong></div>
            </div>
        </div>
    </div>
    <button aria-label="Close" class="close" data-dismiss="modal" type="button">
        ...
    </button>
</div>
```
will get it to display close to the screenshot and break decently in smaller screens. We will need to decide how to apply proper spacing or create a specific modal-header subcomponents for this.

**Comment by drakonux** [comment]
Yeah @bryceosterhaus it's true. Lexicon created [that component](https://liferay.design/lexicon/core-components/forms/multi-step-form-simplified/) but in my opinion, it wasn't well designed. I think nobody is using it and we would like to remove it at some moment. 

I have to admit @pat270 I get lost to decide which option should be better or if create a new component or a variant (because it's a modal window with steps) are options. 

Echo and Tango have plans to use it at some moment (in fact we have received a request to [review these patterns](https://issues.liferay.com/browse/LEXI-783).

**Comment by matuzalemsteles** [comment]
I think for this particular case we can provide a low-level header component that allows for a multi-step, I don't think we need to provide a high-level component for it at the moment and if the business rule is needed to deal with steps we can add some logic to the `useModal` hook.

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)

**Comment by bryceosterhaus** [comment]
Looks like the markup is merged. I'll take this and add to the clay components as well.

**Comment by bryceosterhaus** [comment]
Looking into the clay component, it looks like it might require breaking changes if we want to add this to `<ClayModal.Header>` since we wrap the `children` prop with the `modal-title` class . One way around this might be to add a flag prop that would enable us to use the new API which we would create more low-level components of `<ClayModal.Title>`, `<ClayModal.Item>`, `<ClayModal.ItemGroup>` etc. The immediate option that comes to mind is add a prop to `ClayModal` that would create a context that would enable the new API. We would just need a name for this and this would likely be a new pattern for us to follow in other components where we might need to make breaking changes.

Any thoughts on this?


This is the current markup in `ClayModal.Header`
```jsx
		<div className="modal-header">
			{status && (
				<div className="modal-title-indicator">
					<Icon spritemap={spritemap} symbol={ICON_MAP[status]} />
				</div>
			)}
			<div className="modal-title">{children}</div>
			<Button
				aria-label="close"
				className="close"
				displayType="unstyled"
				onClick={onClose}
			>
				<Icon spritemap={spritemap} symbol="times" />
			</Button>
		</div>
```

And we would likely want to turn it into something like the example below where children could be any allowed content in the header. `title`, `title-indicator`, `close` etc.

```jsx
		<div className="modal-header">
                         {children}
		</div>
```

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus I was thinking that we could create a new Header component to support this instead of adding a new API to change its entire context of use, maybe it would be better to depreciate this component that we created in `ClayModal.Header` and remove later, following the idea of ​​warnings first. And then we can introduce `ClayModal.HeaderBase`? What do you think?

**Comment by bryceosterhaus** [comment]
I think our existing component still is useful, but in this paradigm we have created it should probably called something like `ClayModal.HeaderWithTitle` to signify it is more than just a wrapper. I am also a little hesitant to just add `Base` at the end of the component name to make it seem more low-level. I am trying think what would be an appropriate pattern for us when we want add new API that we _wish_ would be the default API. Adding "Base" or another word is one option, but I'm not sure that is as flexible for other cases where we might need to make a similar change.

One option I thought of last night was this
```jsx
<ClayModal.Header withTitle={false} /> // default internal value would be true
```
This would help us not make a breaking change. It would also already sort of identify what the new component would be on the next major update. We could remove the prop, and then have both `ClayModal.Header` and `ClayModal.HeaderWithTitle`.

The more I think about this option, the more I like it since we essentially make the component behave how we would want, but we hide it behind a prop that is a flag.

What do you think?

I can send an example PR today just to get an idea, and if it's ugly we can try the `HeaderBase` route and see what that looks like.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus Hmm yeah, I'm not sure if we should follow a pattern for a name when we want the component to be lower level, I think it will depend on each case. For now we are trying to find good names 😁, although it is difficult.

I like your idea, I think we can go with that. We can also create a signed ticket for a major version of ClayModal so that we can remember to remove this internal API and create the new component. It just seems a little strange to have the idea of ​​creating an API that it will be deprecated soon 😅

**Comment by bryceosterhaus** [comment]
> seems a little strange to have the idea of ​​creating an API that it will be deprecated soon

It is a little odd, however I don't think we will be making a major change for awhile so its probably fine. And really we won't be getting rid of the API in the future, but instead extracting it to its own component.

**Comment by matuzalemsteles** [comment]
> It is a little odd, however I don't think we will be making a major change for awhile so its probably fine. And really we won't be getting rid of the API in the future, but instead extracting it to its own component.

Yeah no problem, we can continue with this.
