### ISSUE TITLE
ClayTooltipProvider should handle jsx via content props

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#2855]
Hi, we just stepped into a situation where we need to place some formatted data inside of a tooltip. The basic one accept custom `jsx` as content but the provider doesn't.

This is quite a big constrain for us that could be solved by passing our code via props like:
```
<ClayTooltipProvider content={<strong>text</strong>}>
	<div>
		<button data-tooltip-align="top">
			{"Hover"}
		</button>
	</div>
</ClayTooltipProvider>
```
Also we could enrich the basic component using the dropdown approach:
```
<ClayTooltip 
	alignPosition="bottom"
	visible={visible}
	trigger={(
		<ClayButton
			displayType="secondary"
			onMouseEnter={() => setVisible(true)}
			onMouseLeave={() => setVisible(false)}
		/>
	)}
>
	<strong>text</strong>
</ClayTooltip>
```

Thank you :)

**Comment by diegonvs** [comment]
Something like this was related here: https://github.com/liferay/clay/issues/2836.

Would be a good idea create this `content` property to use like render props like:

```jsx
<ClayTooltipProvider renderContent={(content) => <strong>{content}</strong>}>
	<div>
		<button data-tooltip-align="top">
			{"Hover"}
		</button>
	</div>
</ClayTooltipProvider>
```

**Comment by FabioDiegoMastrorilli** [comment]
Thank for you feedback @diegonvs  :) 
Btw, at that stage, we already know the content so there's no need to pass a function: just jsx would be fine. 
Something like: `renderContent ={<button className="btn btn-primary">om nom nom!</button>}`

**Comment by bryceosterhaus** [comment]
Hey @FabioDiegoMastrorilli I went ahead and added this functionality. I went with using a render function since the Provider is a global provider and not necessarily per tooltip instance. Go ahead and check out the demos and let me know if this is what you would expect. 

[Storybook](https://5e20c749c648400008f49c2c--storybook-clayui.netlify.com/?path=/story/components-claytooltip--claytooltipprovider-w-custom-jsx)
[CSB(if you want to play with it)](https://codesandbox.io/s/flamboyant-tdd-m6ys0)
 
Another option I was thinking of adding is providing the `targetRef` in the props for the `contentRenderer`. This would allow users to grab whatever they need off the tooltip node, so they could add their own `data-tooltip-*` attributes. What do you think?

**Comment by FabioDiegoMastrorilli** [comment]
Hi @bryceosterhaus perfect like this. In our scenario we didn't need a callback function but we can just pass no params. Also `targetRef` would be a great thing to add :)
