### ISSUE TITLE
[New] Clay Number Input + Product Card Number Variation

### ISSUE THREAD

**Issue by pat270** [liferay/clay#2907]
https://github.com/liferay/clay/issues/2843 requires a number input that we don't have. It looks like:
<img width="147" alt="clay-number" src="https://user-images.githubusercontent.com/788266/73976288-d7474a80-48dc-11ea-9e11-672dc8ac511c.png">
I'm leaning toward using the native `input[type="number"]`, but has some issues:

Pros:
- Native element
- Mobile devices displays number keyboard by default

Cons:
- ~~Can't currently hide increment/decrement arrows in Firefox (72). See https://bugzilla.mozilla.org/show_bug.cgi?id=1355521 and https://bugzilla.mozilla.org/show_bug.cgi?id=1355574~~ Looks like the selector, `input[type="number"]` wasn't specific enough for Firefox. The `.class[type="number"]` can hide increment/decrement arrows.
- You can still input text (abcdefg) in `input[type="number"]` in IE, Safari, and Firefox

For hiding increment/decrement arrows in Firefox, I can cover them up with a container with `background-color` and custom increment/decrement buttons.

**Comment by jbalsas** [comment]
Lexicon's [Text Input Variations](https://liferay.design/lexicon/core-components/forms/text-input-variations) already define how numeric inputs should look like, so I don't think we should take this, unless Lexicon works on this and adopts it. It should be fine as long as commerce can build that component.

If we ever have an increasing demand for the component, we should clear it out with @drakonux first and make a proper UX study before including it in the library.

Closing for now so we don't get confused, but feel free to continue the conversation!

**Comment by pat270** [comment]
@jbalsas 
Sounds good. I don't think it's a bad idea to include this as a Clay Component. The `input[type="number"]` behavior between browsers are inconsistent. Normalizing them via CSS + JS is a time saver. I was thinking it would be nice if we could normalize the number input behavior and allow passing in some kind of html template where the increment and decrement buttons could be enabled via a `data-attribute`. This would allow for some nice custom number inputs.

**Comment by jbalsas** [comment]
Hey @pat270, as we discussed a while ago, our approach is to build things based on real/specific needs. That is, if we have several teams that request to build something, then we get Lexicon to look into it, come up with the proper proposal (after studying design and interaction patterns) and we'll implement whatever comes out of their work. What we can't do is take 1 isolated request and elevate it to a system-wide component (specially if the team behind it had no problem building it themselves), because it might not be used anymore and then we end up maintaining something for a single team.
