### ISSUE TITLE
Date picker calendar position fixed on the right end of the page when using dir="rtl" in the liferay-portal

### ISSUE THREAD

**Issue by albinojunior** [liferay/clay#2971]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

A: Unable to reproduce this problem outside the liferay-portal.

## What are the steps to reproduce?

1 - Install @clayui/datepicker@3.0.7; 
2 - Import "ClayDatePicker" on my component file;
3 - Load the liferay-portal configured with a language that uses dir="rtl" (for example: "ar").
4 - Click on the calendar icon to open the date picker;
5 - Date picker calendar is displayed at the right end of the page;. [(View image)](https://user-images.githubusercontent.com/28923749/75676671-7eaf6700-5c68-11ea-950f-5917ffc25256.png)

## What is the expected result?
- Date picker calendar should be displayed relative to the date picker field;

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  (@clayui/date-picker) |  v3.0.7  |

**Comment by diegonvs** [comment]
As @pat270, mentioned in some internal conversations, would be great check for `dir="rtl"` and reverse the positioning because clay-css doesn't provide a way to align a `dropdown-menu` when it's not relative to the `dropdown` element.

**Comment by bryceosterhaus** [comment]
@albinojunior I think we figured out the main issue here. Check out this PR for reference, https://github.com/liferay/clay/pull/3022.

If you need a quick work around, go ahead and add a custom style for `.dropdown-menu` so that `right` is set to `auto`. Note that when liferay-portal does the rtl transform, it takes all the "left" properties and calls them "right".
