### ISSUE TITLE
Add new icon: disk

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#3080]
Please, include this new icon. Find the SVG in [LEXI-793](https://issues.liferay.com/browse/LEXI-793).
**disk**: floppy, save
<img width="69" alt="Screenshot 2020-03-23 at 17 16 25" src="https://user-images.githubusercontent.com/56547676/77734475-0d659880-7009-11ea-9049-6520bcabd9fd.png">

Thanks!

**Comment by wincent** [comment]
I know this is probably not the right forum for this kind of feedback, it's probably to late, and the representation here is supposed to be iconic and not literal, but the floppy disk in the icon wouldn't actually work in the physical world:

![floppy](https://user-images.githubusercontent.com/7074/77736586-c37eb180-700c-11ea-9a0e-4d1d43d54dd0.png)

The metal piece needs to slide to the left in order to expose the disk internals, and in the icon, there is nowhere for it to slide because it is already all the way over to the left instead of in the center.

Sorry for being a nerd, @laugardie. The icon looks great.

**Comment by jbalsas** [comment]
![nerdalert](https://user-images.githubusercontent.com/905006/77737200-c6c66d00-700d-11ea-91af-495a1e9ad650.gif)

**Comment by laugardie** [comment]
hahaha, no worries. @wincent I completely see your point. Thanks for the feedback. We have taken a look into it and we have decided to make some changes as never is too late 😂Don't get used to this! 😏

<img width="134" alt="Screenshot 2020-03-27 at 12 31 09" src="https://user-images.githubusercontent.com/56547676/77752192-63493900-7027-11ea-9614-28d248138e07.png">

**Comment by wincent** [comment]
❤️  the new one!

**Comment by laugardie** [comment]
hey @bryceosterhaus @pat270 [LEXI-793](https://issues.liferay.com/browse/LEXI-793) has been reopened as we were suggested to add some adjustments to the save icon. I have included in the ticket the new SVG with the icon adjusted. Could you update it, please?

Thank you guys :)
