### ISSUE TITLE
Documenting ideas that require a breaking change.

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3094]
Goal: Consolidate ideas/info for future breaking changes.

@matuzalemsteles and I were talking and realized we don't currently have a way to consolidate any information on future changes we want to make that would require a breaking change. I am thinking we should actually store these thoughts with code itself. Two ideas come to mind for this.

1. Add a markdown file(perhaps BREAKING.md) per package, and use it to store a collection of API ideas that we want to implement for 4.x. We could also have one in the root of the repo to dicuss more overarching changes.
2. Add in-line comments such as `// TODO 4.x` and explain what we would want to do differently in the next major version.

I think I am more of a fan of adding a markdown file. This would allow us to add snippets of a hypothetical API and also we could just add links to PRs, issues, or lines of code to further explain.

Any thoughts on this?

**Comment by wincent** [comment]
`1.` is better than `2.` because you can't mark things up in `TODO` comments.

Other options:

3. One `BREAKING.md` for all packages instead of one per package (most packages shouldn't have breaking changes anyway).
4. In an issue (like this one).
5. On the wiki.
6. By creating issues for proposed changes and labeling them with some label that means "proposed breaking change for 4.x" (I don't know what the actual wording of the label would be).

FWIW, I kind of like 6 because it would provide a clear place to discuss each change, and then an easy way to find all of the breaking change discussions (by searching for the label). If we had a `BREAKING.md` we'd in theory have one PR for each breaking change too, but it might not be as easy to find them.

**Comment by jbalsas** [comment]
> By creating issues for proposed changes and labeling them with some label that means "proposed breaking change for 4.x" (I don't know what the actual wording of the label would be).

On the risk of having many long-lived issues, this sounds like a good option to me.

**Comment by matuzalemsteles** [comment]
I also like the idea of ​​creating issues and adding labels and also gathering the issues in a `BREAKING.md`. 👍

**Comment by bryceosterhaus** [comment]
> At the risk of having many long-lived issues

This was the reason I thought actually committing to a markdown file might be appropriate since its sort of "resolved" via PR discussion. Sometimes issues seem to drag on and its not super clear that the discussion is resolved and finished.

**Comment by bryceosterhaus** [comment]
>  If we had a BREAKING.md we'd in theory have one PR for each breaking change too, but it might not be as easy to find them.

What do you think about doing the BREAKING.md and then adding labels to the PRs? Itd be sort of mix.

**Comment by bryceosterhaus** [comment]
See example of this at https://github.com/liferay/clay/pull/3152

**Comment by bryceosterhaus** [comment]
@matuzalemsteles @wincent, this look okay with you guys? This way we get both a static doc to track, and also can see PRs with labels to track a discussion around changes.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus looks good for me, I think it's a good step, we can refine best practices as we use them.

**Comment by wincent** [comment]
> this look okay with you guys? This way we get both a static doc to track, and also can see PRs with labels to track a discussion around changes.

👍 — When there are lots of options on the table sometimes you just have to pick one and move forward.
