### ISSUE TITLE
ClayModal size CSS class is applied twice

### ISSUE THREAD

**Issue by markocikos** [liferay/clay#3107]
See `['modal-${size}']: size`, [here](https://github.com/liferay/clay/blob/2f5b60bb897cf1c6d4530af8167921a58d563a1d/packages/clay-modal/src/Modal.tsx#L92) and [here](https://github.com/liferay/clay/blob/2f5b60bb897cf1c6d4530af8167921a58d563a1d/packages/clay-modal/src/Modal.tsx#L99).

This is probably not intended. The effect is that is causes double padding, and awkward overriding in implementations. It it was intended, it's a bad practice that we should avoid.

| Tech  | Version |
| ----- | ------- |
| Clay  | v3  |

**Comment by matuzalemsteles** [comment]
hey @markocikos this was intentional to solve the problem of Modal being closed when the modal aggregates several portals inside it, it is common that it aggregates portals inside it, there may be many DropDowns and we need to check if the click is inside the modal body, I I remember I had problems with the CSS, the way it was done prevented us from checking if the click was really being inside the Body. I had added some comments here https://github.com/liferay/clay/commit/ad46c53bc6837b29fb5931cb7766798f47db6a8a

**Comment by markocikos** [comment]
@matuzalemsteles If I understood you correctly, portal aggregation explains why we need two container `<div>`s, the top one containing aggregate content. `modal-dialog` is important to be in inner container. But, why do we need duplicate size CSS classes, `['modal-${size}']`?

**Comment by matuzalemsteles** [comment]
@markocikos yeah, we need it so that `<div />` occupies only the space to give the body width, so we kind of simulate with this class, without it the `div` will occupy all the edges, this is because we want to know if I click it was outside the body of the modal, if so we will close the modal when the click happens. 

I agree that it was not the best solution but I had to do this to circumvent some things in the CSS, this also ended up being influenced due to the backdrop.

**Comment by markocikos** [comment]
Maybe we could have a different inner class, that adds the same padding? I got some annoyingly unexpected results overriding this class, and probably won't be the last one.

**Comment by matuzalemsteles** [comment]
> Maybe we could have a different inner class, that adds the same padding?

We could even but we would have to adjust the chosen size accordingly, in the end we would have the same result as `modal-{size}` but I think it would not be ideal to add a class to cover an "error" of component.

> I got some annoyingly unexpected results overriding this class, and probably won't be the last one.

Out of curiosity what did you find?

**Comment by markocikos** [comment]
> Out of curiosity what did you find?

There is a clash of styles if AUI modal and ClayModal are on the same page, see more [here](https://github.com/wincent/liferay-portal/pull/192#issue-395804787). Both are using `modal-dialog` class. When I tried

```css
.liferay-modal .modal-dialog {
	position: relative;
}
```
it fixed the default behavior but broke full screen behavior. It is not a blocker, there is a way around it. It is just annoying because I tested by modifying one div, did not know of another, all in all resulting in much longer than needed debugging session.

**Comment by matuzalemsteles** [comment]
> did not know of another, all in all resulting in much longer than needed debugging session.

Oh I'm sorry that you spent a lot of time debugging this because of these changes 😞.

> There is a clash of styles if AUI modal and ClayModal are on the same page, see more here. Both are using modal-dialog class...

Hmm I see, what effects did `modal- {size}` have?

**Comment by markocikos** [comment]
@matuzalemsteles [This](https://i.imgur.com/eDS90bV.png) is what the bug looks like, [this](https://github.com/wincent/liferay-portal/pull/198/commits/fe2617898f0bdc6059955e047eca3e1443dbf9c6) is my solution, in review.

**Comment by matuzalemsteles** [comment]
Thanks @markocikos, I will leave this issue open so that we can find a better solution for this. I'll mark this as an enhancement!

**Comment by mcikos** [comment]
See https://issues.liferay.com/browse/LPS-116090, double padding size is caused by the size class being applied twice.

We can fix the padding in CSS, but ideal solution imo would be to remove duplication of the class.

**Comment by markocikos** [comment]
See https://issues.liferay.com/browse/LPS-116090, double padding size is caused by the size class being applied twice.

We can fix the padding in CSS, but ideal solution imo would be to remove duplication of the class.

**Comment by matuzalemsteles** [comment]
Hey @markocikos, I think I can try to make an improvement to that. Since it is causing a lot of unwanted side effects, I will see that this afternoon. Thanks!
