### ISSUE TITLE
Removing Bootstrap 4 Dependency

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3149]
Integrating Bootstrap in DXP has caused some issues for developers wanting to create custom sites based on Bootstrap. DXP's admin controls are tightly coupled with Bootstrap and presents a problem for devs that want to style Bootstrap's components directly without affecting admin control styles. See https://github.com/liferay/clay/issues/1104.

There is no solution to this issue because of the global nature of CSS. We can help alleviate some of the CSS bleed by namespacing all of our components and removing our dependency on Bootstrap.

Now that Bootstrap 4 is mature, we can begin this process by merging Clay CSS components with Bootstrap's. Clay CSS duplicates a lot of properties declared in Bootstrap because there is no way to customize them through Sass variables. Merging will give us more control over the component and will reduce the number of duplicate properties. A preliminary list of components we should take over:
- [x] import Bootstrap components separately #3261
- [x] move components `aspect-ratio`, `icons`, `buttons`, and `type` earlier in import chain #3263
- [x] root #3273
- [x] reboot #3271
- [x] type #3276
- [x] images #3277
- [x] code #3284
- [x] grid #3285
- [x] tables #3291
- [x] forms #3297
- [x] buttons #3312
- [x] button-group #3438
- [x] transitions #3318
- [x] dropdown #3322
- [x] input-group #3379
- [x] custom-forms #3438
- [x] nav #3381
- [x] navbar #3438
- [x] card #3382
- [x] breadcrumb #3438
- [x] pagination #3384
- [x] badge #3438
- [x] jumbotron #3386
- [x] alert #3438
- [x] progress #3388
- [x] media #3438
- [x] list-group #3390
- [x] close #3438
- [x] toasts #3392
- [x] modal #3438
- [x] tooltip #3394
- [x] popover #3438
- [x] carousel #3396
- [x] spinners #3438
- [x] utilities #3438
- [x] print #3398
- [x] bootstrap mixins #3562
- [x] bootstrap variables #3902

Once a component has been fully adopted, we can theoretically begin namespacing the components with Sass `@extend`. Take `.btn` for example:

```scss
$enable-old-classnames: true;

%c-btn {
  ...css declarations
}

.c-btn {
	@extend %c-btn;
}

@if ($enable-old-classnames) {
  .btn {
    @extend %c-btn;
  }
}
```

We will have two classes for the same button. Whenever we are ready/done converting to the new namespace we can set `$enable-old-classnames: false;`. The old class names will still be available with the flip of a switch for those who didn't want this change.

**Comment by wincent** [comment]
@pat270: So I merged as many of these as I could, in order (to reduce the chances of conflicts), but in the end there are a number that will need an update:

- https://github.com/liferay/clay/pull/3380
- https://github.com/liferay/clay/pull/3383
- https://github.com/liferay/clay/pull/3385
- https://github.com/liferay/clay/pull/3387
- https://github.com/liferay/clay/pull/3389
- https://github.com/liferay/clay/pull/3391
- https://github.com/liferay/clay/pull/3393
- https://github.com/liferay/clay/pull/3395
- https://github.com/liferay/clay/pull/3397
- https://github.com/liferay/clay/pull/3399
- https://github.com/liferay/clay/pull/3403
- https://github.com/liferay/clay/pull/3415

Even if you update them all, they will probably conflict too, so I suggest that you:

1. Make one big PR consisting by cherry-picking all of the commits onto one branch; exclude changes to `packages/clay-css/src/scss/_bs4.scss`.
2. Make all the changes to `packages/clay-css/src/scss/_bs4.scss` in one go, at the end.
3. Ship it!

The other noteworthy one was this one:

https://github.com/liferay/clay/pull/3398

I merged it, but it looks like another one that may require some follow-up due to licensing, as it contains some code substantially(?) copy-pasted from another project.
