### ISSUE TITLE
Clay CSS Navbar, Application Bar, Management Bar, Navigation Bar only output `.navbar-expand` and `.navbar-expand-md` styles

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3236]
## What is your proposal?
This is a breaking change. Right now we output styles for `.navbar-expand`, `.navbar-expand-{sm|md|lg|xl}`. The same goes for `.application-bar.navbar-expand-{sm|md|lg|xl}`, `.management-bar.navbar-expand-{sm|md|lg|xl}`, `.navigation-bar.navbar-expand-{sm|md|lg|xl}`. We should only output the base `.navbar-expand` and `.navbar-expand-md` versions since we only use the `md` breakpoint in DXP / Lexicon.

## Why would adopting this proposal be beneficial?
Saves ~40kb of unminified CSS. There will be an option to enable a specific `navbar-expand` breakpoint via Sass map. If you want to enable the `lg` breakpoint:
```
$navbar-expand: (
    xs: true,
    sm: false,
    md: true,
    lg: true,
    xl: false
);
```

## What are the alternatives to this proposal?
Output styles for all breakpoints, but give option to disable output with `$navbar-expand`.

**Comment by kresimir-coko** [comment]
To me, this sounds like we anticipated usages of more breakpoints than needed. When I do this when developing components I've been taught to not anticipate and over-engineer the capabilities of the component, but instead build a good foundation and then add features as they get requested.

Taking that into consideration, I agree with you that we should not output styles for breakpoints that aren't used, we can always add more breakpoints as they're requested. But, since it's a breaking change, perhaps go with the alternative for starters.

**Comment by marcoscv-work** [comment]
That's sound great to me, the only thing to consider is to offer the same behavior for some customer are using other breakpoints, something so easy like:

> "We have deprecated this but you can get it back by doing this"
