### ISSUE TITLE
New ClayLayout: `<ClayLayout.ContainerFluid>` cannot display only the class `container-fluid`

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#3313]
### New ClayLayout: `<ClayLayout.ContainerFluid>` cannot display only the class `container-fluid`
https://storybook.clayui.com/iframe.html?id=components-claylayout--row-positioning

## What are the steps to reproduce?

We tried by adding:
`<ClayLayout.ContainerFluid fluidSize={false}>``
it does not work

## What is the expected result?

Be able to remove the default class:
`container-fluid-max-xl`

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | master  |
| React |         |

**Comment by bryceosterhaus** [comment]
You should be able to get around `fluidSize` by using the Container component directly with the `fluid` prop.

```jsx
<ClayLayout.Container fluid>
```

It was discussed that we wanted ContainerFluid to default with a size class, but I'm not sure we ever discussed disabling the class on the component. @jbalsas, I think you were advocating for the default size, do you think it makes sense to be able to disable size on `ContainerFluid` or should we tell people to use `<ClayLayout.Container fluid>` instead since its the same thing?

**Comment by jbalsas** [comment]
I would expect `ContainerFluid` default size value to be overridable... but I think `<ClayLayout.Container fluid>` sounds reasonable enough.
