### ISSUE TITLE
Keyboard Trap in FocusScope

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#3332]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

See https://codesandbox.io/s/heuristic-leaf-1oz21?file=/public/index.html

## What are the steps to reproduce?

Case **1a**: Using **only your keyboard**, press `TAB` until you reach the button `NEXT`.
Case **1b**: Using **only your keyboard**, press `TAB` until you reach the `Dropdown` button. Click 
`ENTER` to expand the dropdown, then use `TAB` to reach `NEXT`.

Case **2a** and **2b**. Try the same steps starting from the `NEXT` button pressing `SHIT+TAB` instead to tab in reverse order until reaching the `PREV` button.

## What is the expected result?

All buttons are always reachable using only the keyboard

## What is the current result?

The dropdown component (trigger or menu) trap the keyboard focus once it enters the component.

---

On a quick exploration, `event` is [always prevented regardless of the result of focus management](https://github.com/liferay/clay/blob/master/packages/clay-shared/src/FocusScope.tsx#L50-L64). This should likely be something like:

```javascript
if (...) {
	if (focusManager.focusNext()) {
	    event.preventDefault();
        }
} else if (...) {
	if (focusManager.focusPrevious()) {
	    event.preventDefault();
        }
}
```

This would solve the focus trap, but would not achieve proper tab order when leaving the dropdown menu. When tabbing out of the last element in the menu, focus should go to the next "tabbable" element after the trigger.

**Comment by matuzalemsteles** [comment]
Hmm yeah, that would be an expected limitation of FocusScope, it deals only with the elements that are in the React structure, otherwise, it will not be able to control the focus, we can check the result of the focusManager as you did above, so it doesn't get caught in the trap. Perhaps we can implement a fallback to control non-React elements with a limited scope.

**Comment by jbalsas** [comment]
> [...] that would be an expected limitation of FocusScope [...]

I would say this is rather unexpected. To be expected, then `FocusScope` shouldn't be able to gain focus from outside of React elements either. It's weird that it can gain it but then it won't give it away.

It's okay if we want/need to restrict FocusScope to a component and add something else to deal with the entering-leaving the Focus (seems unnecessary, but could be). 

In any case, we should make sure not to break tab general order neither when entering nor when leaving our components.

**Comment by jbalsas** [comment]
Just to be clear... it should only handle React elements within the scope... but then it should be able to give away control in a proper way, respecting the HTML tab order

**Comment by matuzalemsteles** [comment]
Yeah, I agree with you. If he cannot reach the element he must at least let it follow the natural order. I had implemented this to achieve the non-React elements, not using the React framework to help with this, but we had a lot of problems with edge cases, using portals made things more complex. That's why we use React's internal structure to search for elements, so we don't need to do direct searches in the DOM and we also don't have problems with Portals.
