### ISSUE TITLE
Apply C-inner to Clay components 

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3342]
## What is your proposal?

My proposal is to apply [C-inner](https://clayui.com/docs/css/utilities/c-inner.html) by default.

## Why would adopting this proposal be beneficial?

I think we receive a lot of complaints about the focus-style: very aggressive, thick, etc. I think we took a good decision for the sake of accessibility but on the other hand, we could adjust the experience using it not overwhelming the user if he/she doesn't interact with the keyboard proactively. 

## What are the alternatives to this proposal?

The alternative is to reduce the visual noise of the focus style to a thinner version (1px instead of 2px).

## More context

This proposal becomes from a [slack conversation](https://liferay.slack.com/archives/CNBG06JS3/p1590399390109700) about the focus for the section component in DXP Page Editor.

## Concerns

I really don't see what are the cons of applying c-inner. So I would encourage you to explore and discuss what are the consequences of enabling it by default.

**Comment by marcoscv-work** [comment]
This can be a drastic change for the customer who is used to the "focus" state on mouseover, so I think probably would bee more safe working on the changes by adding "c-inner" class instead of applying the pattern for all clay.
In another hand, we could do it for all components by activating/deactivating a setting variable

Thoughts?

**Comment by pat270** [comment]
The `c-inner` pattern isn't perfect. `button` elements still receive focus on click IE11. To work around this, we need to add the attribute `unselectable="on"` which presents another problem in IE11. When you click a `button` with `unselectable="on"` the browser doesn't move focus that element. If the user decides to navigate via keyboard at that time, it won't be at the place where they expect it to be.

**Comment by marcoscv-work** [comment]
About the IE11 problem. could it be considered an expected and assumable behavior?

IE11 is not the most popular browser:
![image](https://user-images.githubusercontent.com/7963804/85259034-a0776880-b468-11ea-93a1-db4d86ed55ed.png)

**Comment by kresimir-coko** [comment]
Where did we land on with this issue @pat270 @marcoscv @drakonux it feels stuck in discussion for now.

**Comment by drakonux** [comment]
Hey, any progress/update with this request? It would be great to implement this as other design systems currently have. 

cc\ @liferay-lexicon

**Comment by matuzalemsteles** [comment]
@drakonux we haven't made any progress on that. I think it just stayed in which direction we should go with this, if this change is going to impact users as @marcoscv-work pointed out, for me, it doesn't make sense to create a property to disable this and make it optional. In my view here is that the focus with the border is actually something newer when compared without and some users find this weirder at least for buttons, taking into account the other components like input I'm not sure anymore.

If we go with this I think the decision here is to apply it to everything or not to use it, this creates more inconsistency if we leave this as something optional, because some components have this option and others don't, I don't see why a component should follow `c-inner` and another not, we adopted this for example in TreeView but the vast majority still use it with the border by default.

If we apply this to all components, I think it's just the input that we'll have to control via JS because we don't have a way to do that with just markup and CSS.

**Comment by matuzalemsteles** [comment]
Yeah I've seen this happening in other libs like [Adobe's React Spectrum](https://react-spectrum.adobe.com/react-spectrum/Button.html) too. Well, I'm quite inclined to adopt that as the default too ah not unless anyone sees some other big problem but it seems to me a balance to implement this.

**Comment by pat270** [comment]
I think we're far out enough now where we don't need to worry about it working on IE11. They can just have the focus outline. I don't have a CSS only solution for form elements. I can look into it, but not hopeful that I will find one right now.

**Comment by matuzalemsteles** [comment]
Yeah, I believe that for input we will have to control via JS, no problem we can do that.

**Comment by matuzalemsteles** [comment]
Well, I believe a good part will be for us to implement a way to disable/enable this on the Clay side of the components not at the component level but in general, I don't know if this would be possible only with class CSS @pat270 could speak better. But I think that a good part of the products also has to be implemented, I've seen some products not using the most basic components of Clay, for example, the Button, so it may be that they would have to update, there are some DXP menus that would also have to be updated manually, then it would take some review effort to identify where it needs to be updated.

We would also need to identify a simple way to enable/disable this so as not to create something too complex that has become repetitive in many places.

**Comment by pat270** [comment]
Closing this since we are adding focus-visible.
