### ISSUE TITLE
ClayButton should have an example of a ClayButtonWithIcon with a label

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3407]
In the Markup page of the Button we have a markup example of a button with a label. 

ClayButtonWithIcon's API table doesn't even mention a possible label.

Here's the section about the ClayButtonWithIcon that has text inside as well.
![image](https://user-images.githubusercontent.com/24564752/86216614-98ad7780-bb7e-11ea-9429-6ca71930fa1e.png)

Edit: after a quick investigation, the ClayButtonWithIcon doesn't even support a label, so that's something that should be added to the implementation.

**Comment by jbalsas** [comment]
Yassssss!!! I just [asked myself this question](https://github.com/liferay-frontend/liferay-portal/pull/2#pullrequestreview-440606660) :D

![notjustahatrack](https://user-images.githubusercontent.com/905006/86217098-46208b00-bb7f-11ea-8372-dd378d3f1ba7.gif)

**Comment by kresimir-coko** [comment]
It got inspired by that comment!

![](https://media0.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif)

**Comment by matuzalemsteles** [comment]
Hey @kresimir-coko and @jbalsas this was intentional, this high-level component is just to cover the very common case on the Portal, where people used the composition of a Button with Icon without text. Adding support for the text starts to complicate the API further in defining where the icon will be and in what position, left, right... I'm inclined to not add support to this.

**Comment by bryceosterhaus** [comment]
Yeah I think I would agree with @matuzalemsteles. If someone wants to use both an Icon and text, they should use `ClayButton` with `ClayIcon`. `ClayButtonWithIcon` is intentionally used for _just_ an icon with no text.

**Comment by jbalsas** [comment]
Sounds good to me, y'all!

I did have to write a Button with a Label and an Icon and it wasn't super straightforward, to be honest... specially because of the `inline-item` classes... 

I'm fine if we want to see this play out a bit more, but maybe write out an example on how to do this? Seems like a common enough use case to grant at least that :)

**Comment by kresimir-coko** [comment]
I agree that we should at least have an example of that usage, it stills fits with the title so we can keep the issue open :)

**Comment by bryceosterhaus** [comment]
Sent an update to the docs for adding an example at https://github.com/liferay/clay/pull/3470
