### ISSUE TITLE
Data prop won't get spread when using `ClayDropdownWithItems`

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#3445]
Discovered while testing https://github.com/liferay-frontend/liferay-portal/pull/2

The following code:

```javascript
<ClayDropDownWithItems
    items={
        data={
            bar="bar",
            foo="foo"
        }
        label: "Something with data"
    }
/>
```

Will render items like:

```html
<button data="[Object object]">Something with data</button>
```

While this is somewhat to be expected... we were using `data` before to render something like:

```html
<button data-bar="bar" data-foo="foo">Something with data</button>
```

We can address this in the DXP wrapper, but I'm afraid it might trip devs using `ClayDropdownWithItems` directly...

Looking for thoughts on what to do. Options:
1. Treat a `data` prop as special and spread it as data attributes
2. Do this treatment in DXP `DropdownMenu` wrapper 
3. Update call sites to pass independent `data-*` props rather than one single `data`
4. Other?

**Comment by wincent** [comment]
> ```js
> <ClayDropDownWithItems
>     items={
>         data={
>             bar="bar",
>             foo="foo"
>         }
>         label: "Something with data"
>     }
> />
> ```

Innovative syntax 😉 

![innovation](https://user-images.githubusercontent.com/7074/86459625-5a9f8780-bd27-11ea-944b-bf62c79cc852.gif)

> Looking for thoughts on what to do. Options:
> 
> 1. Treat a `data` prop as special and spread it as data attributes
> 2. Do this treatment in DXP `DropdownMenu` wrapper
> 3. Update call sites to pass independent `data-*` props rather than one single `data`
> 4. Other?

"1" is awfully tempting, but maybe it is only seducing me because it is "sexy".

The thing is though, how often are we going to want to do this? If we make it super easy (ie. "1"), then we may end up further encouraging use of data attributes. Is that something we want to do? On the flip side, if it is a rare thing, then "3" may actually be fine.

Of the options, "2" is the least appealing one. If this is a thing that is generically useful enough to warrant us having the handling in DXP, then it is arguably generically useful enough that it belongs in Clay instead (ie. "1").

**Comment by bryceosterhaus** [comment]
Personally I think #3 is the best option and makes most sense to me. If we start treating `data` as its own special prop, it becomes sort of a reserved word for Clay and I can imagine we will forget to add it in places similarly to how we have to remember to add `forwardRef` to things. Overall, I think it just adds greater overhead when we can already add it by adding a `data-foo` prop.

```jsx
<ClayDropDownWithItems
    items={[{
        data-bar: 'bar',
        data-foo: 'foo',
        label: "Something with data"
    }]}
/>
```

**Comment by jbalsas** [comment]
Okay, I sense we're all in agreement at least in not doing this in Clay, so going to close this.

For reference, I ended up doing ["the least appealing one"](https://github.com/liferay-frontend/liferay-portal/pull/2/commits/a240cbaa6d2e6ad5a1128ba53a55ee37fdd62735#diff-f0525bff0b549a2b86d74130c53122e1R34) as @wincent called it. 

Just because it's not so simple to change the call sites. I did so for other cases, like `clay:button` where we can now pass simply `data-foo`... but where Java passes down `data` maps, and in this specific case, where the `data` attribute is nested inside other data, there's no easy way to make those truly dynamic without far-reaching changes.

Leaving the door open for those changes in the future depending on how much usage we have.

**Comment by wincent** [comment]
> For reference, I ended up doing ["the least appealing one"](https://github.com/liferay-frontend/liferay-portal/pull/2/commits/a240cbaa6d2e6ad5a1128ba53a55ee37fdd62735#diff-f0525bff0b549a2b86d74130c53122e1R34) as @wincent called it.

To clarify, I don't think what you did is bad because it is a one-off (so far). The thing that I was referring to as "least appealing" would be make a generic API in DXP for spreading data attributes. The idea being that if it is generic enough for DXP, that would kind of prove that it is generically useful enough to belong in Clay intself.

Doing it by hand in one place doesn't close any doors to us, so we can abstract this (or not) any way we please in the future.

**Comment by jbalsas** [comment]
> To clarify, I don't think what you did is bad

![istillloveyou](https://user-images.githubusercontent.com/905006/86812732-a2077a00-c07f-11ea-8fa7-b30aca46f53b.gif)
