### ISSUE TITLE
@clayui/color-picker Why do we use a hidden input to store the color value when we already have an input in the input-group?

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3524]
Continuing from unrelated pr #3519 and trying to get to the bottom of this. I think we are getting closer.

My next theory is that we need it for the native `input[type="color"]`. I see that the hidden input changes to input to `type="color"` at https://storybook.clayui.com/?path=/story/components-claycolorpicker--native.

If this is the reason, I think we could approach this in another way. We could replace the Splotch with `input[type="color"]` and and overwrite the default styles of the input to match Lexicon.

**Comment by bryceosterhaus** [comment]
Yeah I think you are right, we added it for the two variants of the picker. We can tweak it to always have one input and and conditionally hide it based on the variant

**Comment by pat270** [comment]
What's the reason for having a native color picker again? The only reason that comes to mind is that it "works" without JS. The native color pickers are pretty bad especially Safari.

**Comment by jbalsas** [comment]
> What's the reason for having a native color picker again? The only reason that comes to mind is that it "works" without JS. The native color pickers are pretty bad especially Safari.

To use the native pickers, specially for mobile, where a native UI would be far superior than ours. We've seen this in the past, with other like `DatePicker`. Our "modal" approach doesn't work at all in small devices and the native ones do a better job at this. If that's not useful in this case, we can throw it away.

Again, please don't discard the requirement of this having to work with HTML form submission by default.

**Comment by bryceosterhaus** [comment]
So I tried removing the hidden input and making the input group conditionally show and only use that input. However, this would also require css changes since the border radius of the splotch is modified by having a sibling element
<img width="305" alt="Screen Shot 2020-07-21 at 10 15 25 AM" src="https://user-images.githubusercontent.com/6843530/88085730-1b50a380-cb3b-11ea-88a0-c57a59701851.png">

**Without sibling element**
<img width="148" alt="Screen Shot 2020-07-21 at 10 13 10 AM" src="https://user-images.githubusercontent.com/6843530/88085550-daf12580-cb3a-11ea-88ed-0efc156f41a6.png">

**With sibling element hidden**
<img width="152" alt="Screen Shot 2020-07-21 at 10 13 05 AM" src="https://user-images.githubusercontent.com/6843530/88085554-dd537f80-cb3a-11ea-8c06-8a96727c5245.png">


So overall, I think we might just be better off by leaving the hidden input in there unless we are running into a bug because we have two inputs. My primary reason for leaving it _"if it ain't broke, don't fix it"_. The css changes are fine to update, but it doesn't seem necessary just to avoid two inputs.

**Comment by pat270** [comment]
The way I was envisioning it (without sibling element) was:
```
<div class="clay-color-picker">
  <label for="colorPicker4">Native</label>
  <div class="input-group clay-color">
    <div class="input-group-item input-group-item-shrink input-group-prepend">
      <div class="input-group-text">
        <input id="colorPicker4" name="colorPicker4" type="color" value="#FFFFFF">
      </div>
    </div>
  </div>
</div>
```
We wouldn't need a hidden text input because we could update the color input directly. 

I'm good with leaving it. I think it will be a lot of work to normalize color input behavior across browsers. We have a few issues with our native color picker implementation though https://storybook.clayui.com/?path=/story/components-claycolorpicker--native.

1) Chrome / FF when you change the color, the button color and hex value aren't updated
2) That page doesn't work in Safari (13.1)
3) What happens when a browser doesn't support `input[type="color"]`
