### ISSUE TITLE
@clayui/css `drilldown-item-indicator-text-*` click area should be larger

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3579]
Text inside dual click areas in a dropdown item is too small.

<img width="262" alt="dropdown-item-indicator-text-*" src="https://user-images.githubusercontent.com/788266/89226929-a39a6400-d591-11ea-9360-5f89acc4ef69.png">

The purple area should expand to fill the yellow area up to the icon.

**Comment by kresimir-coko** [comment]
Reminder that you self-assigned this one to yourself @pat270 😄

**Comment by kresimir-coko** [comment]
@pat270 I tried finding how to reproduce this, I assume it's when the drilldown is a parent, when `A Shortcut` and `>` lead to different views? We don't have that example in Storybook, and on your test site I couldn't find this specific example, even tho I found it in source code: [clay-css/dropdowns_drill_down.html#L178](https://github.com/liferay/clay/blob/master/packages/clay-css/src/content/dropdowns_drill_down.html#L178)

**Comment by pat270** [comment]
@kresimir-coko Yes on items with two links that lead to different areas, the click area of `A Shortcut` is too small. The image below should help visualize what I mean. The red box around The Click Area should be bigger.

<img width="557" alt="click-area" src="https://user-images.githubusercontent.com/788266/94719028-72c37a80-0307-11eb-8b03-8e2184730680.png">

**Comment by kresimir-coko** [comment]
Alrighty, it took me a bit of digging through my notes to find that in order to see this example I need to fire up a gulp server inside clay-css. We should definitely add that into the GitHub readme thingy.

Once I did get it fired up I realized the main culprit, `dropdown-item` is always the parent of the item, and always has the same `padding`, which makes sense. What doesn't make sense is that it's child in case of simple text, like `Folder` in the above example doesn't have an HTML element wrapped around it, so it's just `<div class="dropdown-item">Folder</div>`.

My proposal is to add another layer of HTML, like a `span` to that `Folder` text, so that we can target `dropdown-item` with CSS and remove the `padding` from it. 

I sent a WIP example of the styles just to get feedback from you @pat270 if I should be doing it in a different file, or a certain way with these variables and imports, haven't worked in a proper CSS project yet.

I also sent a commit that fixes a couple small things in Drilldown, lemme know what you feel about them @bryceosterhaus
