### ISSUE TITLE
Esc to dismiss a tooltip

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#3696]
After reviewing [LEXI-600](https://issues.liferay.com/browse/LEXI-600), Lexicon finds that implementing "esc" command key to dismiss a tooltip would be a positive improvement in terms of accessibility for the Tooltip component.

**Comment by jbalsas** [comment]
Sounds good to me... some of this might need to be implemented in DXP side directly, so you might file an LPS as well :) 

My only concern is that `ESC` might trigger other actions, so I'd investigate a little to see what are the possible ramifications of such a behaviour.

One ridiculous example is that `ESC` with focus on Chrome DevTools opens a panel. Native tooltips can be dismissed using `ESC` (so this proposal is aligned with default behaviour). Since tooltips show without focus, you can have focus somewhere and trigger something while dismissing the tooltip. I imagine this interacting with autocompletes, closing dropdowns, modals... things like that...

**Comment by matuzalemsteles** [comment]
I have the same feeling that Chema, we will have problems with DropDowns and Modals, mainly in Modals, maybe we can prevent him from closing everything, I can test this next week.

**Comment by victorvalle** [comment]
Hi @matuzalemsteles , you closed this ticket without the outcome of your exploration. Could you write some lines about what happened? Otherwise, it just looks to me it was closed without any work done on it.

Thanks

**Comment by victorvalle** [comment]
Sorry for my last comment, I see in #3704 that you did the tests and implementation.
Thanks!
