### ISSUE TITLE
'this' not accesible in handleSubmit (ClayForm onsubmit)

### ISSUE THREAD

**Issue by nachoge** [liferay/clay#3703]
Hi,

How is supposed to update (or reference) this ( let's say ClayForm) in handleSubmit. 
there's just one param (event) and this is undefined...

Imagine there's a Clay component that performs a submit, for instance, it calls the back and retrieves data. Once it's finished I want to update the caller (or any other) I can not.

Which is the way

**Comment by bryceosterhaus** [comment]
Hey @nachoge!

In Clay we follow a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) mechanism for our form elements. Rather than accessing `this`, we store the form values on the parent component. For example, if you wanted a form with an input and handle its submission, you would so something like this:

[Demo](https://codesandbox.io/s/gallant-grothendieck-4ryh6?file=/src/index.js:196-654)
```jsx
const App = () => {
  const [value, setValue] = React.useState("");

  return (
    <ClayForm
      onSubmit={(e) => {
        e.preventDefault();

        alert("Submitted: " + value);
      }}
    >
      <label>{"Name"}</label>
      <ClayInput
        onChange={(e) => setValue(e.target.value)}
        placeholder="Name"
        type="text"
        value={value}
      />

      <ClayButton type="submit">{"Submit"}</ClayButton>
    </ClayForm>
  );
};
```

As a whole, both in Clay and often when using React with function components, we don't really ever access `this`.

**Comment by nachoge** [comment]
Hi, I undertand

thank you very much
