### ISSUE TITLE
The Icons page is frozen for a while

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#3744]
When accessing the [Icon component page](https://clayui.com/docs/components/icon.html), my browser freezes for some (5) seconds before becoming responsive.

Haven't fully explored the reasons but I assume we're doing some heavy work with the data or the icons...

![icons](https://user-images.githubusercontent.com/905006/95434381-75e6e800-0951-11eb-88d5-bbb9b1c7454f.gif)

**Comment by wincent** [comment]
FWIW, not happening for me on Chrome 85.0.4183.121 + macOS High Sierra.

**Comment by jbalsas** [comment]
> FWIW, not happening for me on Chrome 85.0.4183.121 + macOS High Sierra.

![showoff](https://user-images.githubusercontent.com/905006/95438142-2f47bc80-0956-11eb-9dae-b63cdf84cd5c.gif)

Happenning to me on Version 86.0.4240.75 (Official Build) (x86_64) + macOS High Sierra 10.13.6

**Comment by kresimir-coko** [comment]
Same for me, latest Chrome `86.0.4240.75 (Official Build) (x86_64)` and macOS Catalina `10.15.6`.

Gonna take a look

![](https://media1.giphy.com/media/SXYzfz4rCV5zdwM8q3/giphy-downsized-medium.gif)

**Comment by kresimir-coko** [comment]
So, using `Fast 3G` to slow things down a bit I came to the conclusion that it might be `icons.svg` file that's causing this problem. Here it can be seen without any throttling how delayed it is, and I paid attention and as soon as that got loaded I could scroll the page. Same happens when changing to the Markup tab, because it hosts the same icon search components as in the Examples tab.

![image](https://user-images.githubusercontent.com/24564752/95461951-22879080-0977-11eb-9475-ee7fd0f4c658.png)


Another thing to note, this issue is nonexistant when there is only one Icon Search component on the current page, and currently we have Icon Search and Flag Search. Removing one of those, and refreshing (with deleting cache) resulted in instant load times.

Will investigate further tomorrow.

**Comment by pat270** [comment]
This has been happening for a while. The problem goes away when you have dev tools open and refresh the page. I think it might have to do with svgs and Chrome cache.

**Comment by bryceosterhaus** [comment]
Just looked into this a bit and it seems like its an issue with chrome specifically. I tested on Firefox and safari and it works fine.  There have been a few chrome issues I've run across with svgs+cache since v84, so I wonder if there might be something lingering they haven't fixed. I tried to look through their reported bugs and couldn't find anything specific to this, but parsing through all the issues is a bit difficult as well...

As a temporary fix, we could add `svg4everybody`?
