### ISSUE TITLE
Navigation bar variables pattern

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#377]
In [v2.0.0-beta.2](https://github.com/liferay/clay/blob/master/CHANGELOG.md#v200-beta2-november-10-2017), there are some breaking changes in navbars:
- Breaking: Navbar removed Clay versions of .navbar-light, .navbar-dark, .navbar-secondary, .navbar-primary and corresponding Sass map variables $navbar-light, $navbar-dark, $navbar-secondary, $navbar-primary
- New: Navigation Bar added .navigation-bar-light, .navigation-bar-secondary, -bar-light, and $navigation-bar-secondary

Based on [Navbar - Color Schemes](https://getbootstrap.com/docs/4.0/components/navbar/#color-schemes), shouldn't we simply be doing:

```html
<nav class="navbar navbar-dark bg-secondary">
  <!-- Navbar content -->
</nav>
```

What's the reason behind the custom navigation-bar variables? If the problem is that we have different secondary backgrounds, shouldn't this be called `$bg-clay-secondary`?

See an example of current usage in a place that is not a `navigation-bar`:

<img width="1362" alt="navigation-bar-secondary" src="https://user-images.githubusercontent.com/905006/32832567-3dafc1f6-c9fc-11e7-803f-de438bf57912.png">

**Comment by pat270** [comment]
BS4 makes a lot of assumptions like a primary background should be the same across all components and any variant should be lightened or darkened by a specific percentage. The Lexicon Experience Language has a specific color palette that doesn't quite fit with this pattern (a problem not unique to Lexicon). We have 2 types of primary backgrounds. The one (#1865FB) used in `.btn-primary`, `.badge-primary`, `.progress-bar` and one (#F0F5FF) used in `.management-bar-primary`.

In the BS4 theme, a primary navbar would use the classes `bg-primary navbar-dark`, whereas in Lexicon, we would need to use the classes `bg-primary navbar-light`. We could solve this by: 

1) applying specific colors to the `bg-primary` and `navbar-dark` classes when it's used inside some navbar variant (e.g., management-bar)
2) creating a new bg utility `bg-primary-light`
3) create component specific utilities (e.g. management-bar-primary)

The problem with 1) is now we have a `bg-primary` that is some variant of the primary color and `navbar-dark` is now light. 2) We open up the doors to a bunch of color utility classes that can be littered across an application without much thought as to how it will effect themeability in the future. 3) Is the least destructive because it scopes the colors to each component and gives it specific meaning. `management-bar-primary` can now be some blue colored variant with light or dark text without having to worry about changing the background-color of a panel in some random application.

I think BS3 got it right with the color scheme. I'm not sure why they decided to move away from it (might be related to some of the newer front-end frameworks like React). We are deviating from Bootstrap 4's color utilities and the utility system, in general, because it assumes you have 100% access to the markup. In Portal this is not the case, it's really hard to update markup. Because of this I think it's generally better to take colors, spacing, positioning, etc on a per component basis.
