### ISSUE TITLE
ClayCss: Change the default aspect-ratio value

### ISSUE THREAD

**Issue by edalgrin** [liferay/clay#3792]
## What is your proposal?

- Make the class `.aspect-ratio` 16:9 by default
- Add a `.aspect-ratio-16-to-9` class
- Remove the [overwrite](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_cards.scss#L789) for `.card-type-asset`

## Why would adopting this proposal be beneficial?

- [Bug fix](https://github.com/liferay-frontend/liferay-portal/pull/455)

/cc @marcoscv @pat270

**Comment by marcoscv-work** [comment]
Actually, LPS-122274 is not caused by this, and this change suggestion is not a blocker for the LPS, LPS-122274 is caused by custom properties implementation. But we consider after analyzing the issue, probably Lexicon is using only `16_to_9` aspect ratio, so we could make it the default one and probably think about removing the other ones since they are not been using in portal. If customers are already using them, then we can consider only to change the default one.

**Comment by pat270** [comment]
Clay CSS already has a 16-to-9 class. See https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_aspect-ratio.scss#L197.

I'm not sure about changing the default to 16:9. It has been 1:1 since version 2.x. If you want we can up the specificity of our aspect-ratio utilities. If clay-for-admin becomes a thing, I'm willing to change the default to 16:9 there.

**Comment by marcoscv-work** [comment]
That seems fine to me

What about `.card-type-asset`? Do we need this class? could we directly use 16: 9 class?

**Comment by pat270** [comment]
@marcoscv-work yes you can remove `card-type-asset` and use `aspect-ratio aspect-ratio-16-to-9` directly. My preference is to keep it the way it is. It makes more sense to me if we decide to change the aspect-ratio in the future or have a different ratio in small screens.

**Comment by marcoscv-work** [comment]
Hey @edalgrin @pat270, then we prefer to close this Issue or propose a new point of view?

**Comment by pat270** [comment]
@marcoscv-work I'm good with closing this unless we have more to discuss.

**Comment by edalgrin** [comment]
We can close this, I'll keep it in mind for future changes (Clay 4 CSS?)
