### ISSUE TITLE
[Discussion] ClaySelect doesn't have support for a label & needs updated DOM structure

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3796]
I'm making a JPS tag for the Clay Select component and I've noticed, with the help of @carloslancha that the component is missing a label accompanying it. 

The old Soy tag had it and the DOM structure was:
```html
<div class="form-group">
    <label>Label</label>

    <select class="form-control">
        <option>
    </select>
</div>
```

### This is a blocker for https://github.com/liferay-frontend/liferay-portal/pull/492 

Whatever gets decided here will be implemented as the DOM structure for the new `<clay:select>` tag

**Comment by matuzalemsteles** [comment]
@kresimir-coko this is intentional the Label must be a composition with the component, so we no longer provide the label with a `form-group` wrapper to allow it to be flexible to be composed with other components.

**Comment by kresimir-coko** [comment]
@matuzalemsteles would you recommend we make a `<clay:label>` tag in DXP then, as well? @jbalsas @carloslancha  what're your thoughts on this?

**Comment by carloslancha** [comment]
`<clay:label>` exists already, but it's other stuff: https://clayui.com/docs/components/label.html

@matuzalemsteles the thing is that to me we're not being consistent between components. To me makes sense that `ClaySelect` renders only a `<select>` tag, but it so I would expect `ClayCheckbox` to only render an `<input>` tag, and it's not, it's rendering a label and a `form-group` div.

We would argue that a checkbox should always have a label, but what if we want the checkbox at the right side of the label? We won't be able then to use `ClayCheckbox` because we need to compose it in a different way, exactly the same reason we have for the `Select`, right?

**Comment by markocikos** [comment]
I guess that depends on use cases. I don't imagine there are a lot of selects without labels, but there could be a lot that would prefer their own markup for label and container. If that is the case, I don't think we would want to be opinionated with add out-of-the-box label in `<ClaySelectWithOption>`. It's a design balance question of flexibility vs. consistency that never has a black or white answer.

**Comment by matuzalemsteles** [comment]
Well, I think we are very oriented in how the taglibs were made when we created Clay on Metal+Soy in v2, it is worth remembering that we had a different view and Metal+Soy brought some impediments that this was reflected in the API and the same for taglib.

With that in mind, Clay v3 has developed into a side where you try to become flexible using composition in the first place to get close to the components that are developed in the React way but still maintaining a bit of the essence of v2 with the high-level, like `<ClaySelectWithOption />`.

So, making wrappings with `form-group`, `label` in a `ClayCheckbox`, `ClaySelect`, `ClayRadio` or `ClayInput` component are out of the question because they would become a high-level component and not a primitive one low-level, because we prioritize the composition first and if it becomes a common pattern and it makes sense we study whether it makes sense to make this composition a high-level.

I'm not sure when you say whether it's an inconsistency of the taglibs with the React component or between the React components, anyway I disagree that it's an inconsistency, Clay v3 has been changed to a new philosophy and this is part of its version change, I know this is difficult to manage for taglibs.

These components mentioned are equivalent:

```jsx
<ClayForm.Group>
	<label htmlFor="basicInputText">Name</label>
	<ClayInput
		id="basicInputText"
		placeholder="Insert your name here"
		type="text"
	/>
</ClayForm.Group>

<ClayForm.Group>
	<label htmlFor="basicSelectId">Name</label>
	<ClaySelectWithOption
		id="basicSelectId"
		options={options}
    />
</ClayForm.Group>

<ClayForm.Group>
	<label htmlFor="basicCheckboxId">Name</label>
	<ClayCheckbox
		id="basicCheckboxId"
		checked
    />
</ClayForm.Group>
```

As a final thought of what I'm seeing is that we are migrating the existing taglibs to use v3 but it is happening the other way around, we are trying to keep the React components of v3 looking like version v2. This is not happening strongly, but seeing some things is a feeling of what I am having.

Another point to consider, we cannot infer if it makes sense to only have `ClaySelect` with `label` because at the moment we are developing the UIs they can go together in some case but this can change at any time on any team that is using the Clay in DXP, in some places I can see some forms without the label but it depends on the Designer, Lexicon inferred some standards but what we try here is to make our components flexible to increase their longevity.

**Comment by carloslancha** [comment]
Hey @matuzalemsteles !

Sorry, when I said

>but it so I would expect ClayCheckbox to only render an <input> tag, and it's not, it's rendering a label and a form-group div.

I meant "rendering a label and a custom-control" div

>I'm not sure when you say whether it's an inconsistency of the taglibs with the React component or between the React components, anyway I disagree that it's an inconsistency

Between react components, I'm not talking about tags (yet).

With inconsistency I mean that while `ClaySelect` is rendering just a primitive `<select>` tag, `ClayCheckbox` is rendering a `div` with a `label` with an input, not a primitive `input` tag. So in the example you provided, the checkbox example would be:

``` 
<ClayForm.Group>
	<ClayCheckbox
		id="basicCheckboxId"
		checked
		label="Name"
    />
</ClayForm.Group>
```

which result would be
```
<div class="custom-control custom-checkbox'">
	<label>
		<input type="checkbox" />
		<span className="custom-control-label">
			<span className="custom-control-label-text">
				Name
			</span>
		</span>
	</label>
</div>
```

even if you pass no label the resulting markup will be:
```
<div class="custom-control custom-checkbox'">
	<label>
		<input type="checkbox" />
		<span className="custom-control-label">
		</span>
	</label>
</div>
```

which is far from being a primitive input.

So, to me the inconsistency is that `ClayCheckbox` renders a label, `ClaySelect` doesn't.

Sorry if I didn't explain well before :)

**Comment by matuzalemsteles** [comment]
@carloslancha I understood your point of view, I would say that you are right but I still disagree a little that it is still an inconsistency, bringing the case of `ClayCheckbox` to the real world, since I had made pseudocode.

The case of this label is different from a label that you would add for input or select, normally it is for cases when you have multiple checkboxes and radios, where the label adds an explicit value for each checkbox but there is still a label that you add in the context of the field group. A few examples on [Lexicon](https://liferay.design/lexicon/core-components/forms/radio-check-toggle). There are cases where you will use the checkbox without the label but it is being used in a context where the composition of the components is offering the explicit context.

So I think they are different cases and not a problem of inconsistency and also why we do not allow the checkbox to keep the label in different positions.

```jsx
<ClayForm.Group>
	<label>Select your favorite color</label>
	<ClayCheckbox
		checked
		label="Blue"
	/>
	<ClayCheckbox
		label="Red"
	/>
	<ClayCheckbox
		label="Black"
	/>
</ClayForm.Group>
```

Well, this is my point of view in relation to this case, but maybe if we bring the case of the `SelectBox` we can say that it is an inconsistency and we must correct it.

**Comment by carloslancha** [comment]
>but there is still a label that you add in the context of the field group.

That `<label>Select your favorite color</label>` shouldn't be a label but a `<h*>`, a `<p>`...

A `label` is an element that represents a caption for an specific item

>The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered. (via [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label))

So, in the same way the label of a select is a caption of that specific select and is programmatically associated to it, the label of a checkbox is the same. The only difference here is that we're assuming that the label of a checkbox will always be inline.

And in the way `ClayCheckbox` is built (I guess because the custom controller to add custom styling to it) the label text and the input must be wrapped inside a label and a div in order to make that programatic connection works, that's why makes sense for `ClayCheckbox` to receive a `label` prop. 

But they're still labels. So in the end we have some "primitive" components that renders "primitive" tags, and others that doesn't. That's what I find inconsistent.

About `SelectBox`, yep, absolutely 😅

**Comment by jbalsas** [comment]
Just a quick note. I have only skimmed the whole thread, so forgive me if I'm missing anything.

`<clay:select>` and `<ClaySelect>` do not need to be necessarily the same thing and they're used in different contexts. 

I bring this up specially because of the `[Blocker]` tag. We can simply make the `clay:select` tag output whatever we think make sense and then update it if a different solution is reached here. Let's try to avoid getting blocked by things like this. We control both libraries, so we can coordinate the changes in a way that they evolve as we need them to.

**Comment by kresimir-coko** [comment]
@jbalsas In that case my implementation of `<clay:select>` is good enough, as it outputs a working components, we're mainly hung up on the details of the DOM structure here. So if you think we can go ahead with my implementation over on https://github.com/liferay-frontend/liferay-portal/pull/466 I'll make it not a Draft and we can get around to reviewing it and merging.

**Comment by jbalsas** [comment]
If we decide to finally add labels here, then we can update the tag when the component (which we're not even using over there right now) is updated.

**Comment by markocikos** [comment]
> We can simply make the `clay:select` tag output whatever we think make sense and then update it if a different solution is reached here.

That falls back to the question of backwards compatibility. There was some discussion about that in https://github.com/liferay-frontend/liferay-portal/pull/492. In short, @carloslancha and me have reversed positions we had on `HorizontalCard`, I am leaning for breaking compatibility and he is leaning against :slightly_smiling_face:

**Comment by jbalsas** [comment]
> That falls back to the question of backwards compatibility. There was some discussion about that in liferay-frontend/liferay-portal#492. In short, @carloslancha and me have reversed positions we had on HorizontalCard, I am leaning for breaking compatibility and he is leaning against 🙂

Changing one's mind is often a sign of intelligence ;)

Added some comments there as well complementing this. Let's not have hard rules but rather evaluate in context each time and apply all we have to those changing contexts as best as we can. As we all know by now, there's no silver bullet or one-shoe-fits-all, so be ready to adapt! ;)

**Comment by markocikos** [comment]
In any case, this issue should not be marked as [Blocker], as https://github.com/liferay-frontend/liferay-portal/pull/492 currently implements this markup without any change on Clay part. I believe, in fact, that we can safely close it.

**Comment by carloslancha** [comment]
Don't close it please, I think we can continue with the discussion about the consistency between components ;)

**Comment by matuzalemsteles** [comment]
> That <label>Select your favorite color</label> shouldn't be a label but a <h*>, a <p>...

@carloslancha yeah, you're right, about this really for this case we should not consider the `<label />` tag talking mainly about accessibility.

I'm more inclined to go in the direction of removing the `label` from the Checkbox than adding the label to the other components, because we still need to allow the developer to customize any component as in the examples above, mainly because we need to add the `form-group` wrapping the label and the component but for the Checkbox case it is the only exception here. Or just consider Checkbox an exception as well as Radio and remove the label from other components that exist (that would be a breaking change, so it would probably be for v4).

I think we can start by reviewing some APIs of the low-level components to have a view of the inconsistency problems that exist to be able to trace an improvement, be it name or behavioral as the case of the label.

cc @bryceosterhaus if you have any ideas.

**Comment by bryceosterhaus** [comment]
> @matuzalemsteles 
> I'm more inclined to go in the direction of removing the label from the Checkbox than adding the label to the other components
> ...
> consider Checkbox an exception as well as Radio and remove the label from other components that exist

I agree with these thoughts. I think it makes sense to de-couple elements that aren't required and allow them to be composed together.

**Comment by matuzalemsteles** [comment]
I'm going ahead and closing this issue to focus discussion on this in issue #4741 which we'll be working on soon. Things related to API consistency have been worked on different fronts, some of them have already been merged and others are being worked on.

- [API consistency improvements for controlled and uncontrolled components](https://clayui.com/blog/2022/05/02/api-consistency-improvements-for-controlled-and-uncontrolled-components.html)
- [Standardizing collection components](https://github.com/liferay/clay/pull/4840)
- [Standardizing form-related components](https://github.com/liferay/clay/issues/4741)
