### ISSUE TITLE
UserCard labels

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#3799]
Hey guys, I just realize that UserCards are not supposed to accept labels:

Lexicon website: https://liferay.design/lexicon/core-components/cards/cards-variation/#user-card
Lexicon docs: https://docs.google.com/document/d/1st2moaRVphrsFrDJUz-ic26aH-V46YkQam75X6BHPY0/edit#

>User cards do not have labels.

Is there any particular reason because we're accepting `labels` in `ClayCardWithUser`?

This is important because I added support for the attribute `labels` in `UserCard` tag in DXP based on this component when there wasn't any support for it in 2.x tag nor Clay 2.x Soy components and we shouldn't add not required/needed stuff.

Thx

**Comment by bryceosterhaus** [comment]
@carloslancha likely was un-intentional to add it as a feature. We can go ahead and remove it from `ClayCardWithUser` if lexicon is saying not to allow it.

For some background, when we first created a lot of these components, we did so in a pretty short time period. We primarily went off of the clay site and lexicon site for specifications and we actually didn't have the google doc specifications for most components. I don't know if it was ignorance or laziness or that we couldn't find them but I don't remember having detailed specifications on components and so we did our best as piecing together the requirements. I think this is what led to some issues like this, where we saw labels used on other cards in the lexicon site, and so we figured that labels were on all cards and added the API for all cards. **So, with all that to say, if you come across APIs or features that don't align with Lexicon, its likely we missed it and Lexicon is right and we need to update to follow that pattern.** So thanks for opening these issues though and keep them coming, they really help us refine Clay into what lexicon intends.
