### ISSUE TITLE
Active state nav-bar

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#381]
Hi Patrick, we have found an issue with the active state of the navbar (http://pat270.github.io/lexicon/content/navbar/) in **Lexicon V2.0.0-BETA.3** 

1. Lexicon doesn't have any of the cases with the active as Blue because we use it as primary color, so as the active state for texts we use the Main color (#272833). This is creating confusion with other teams here, they're using the blue color as active and is something we want to avoid. 
![image](https://user-images.githubusercontent.com/27729173/33178105-38db3074-d065-11e7-96ae-7d6ef5682833.png)

2. In the dark navbar we need the secondary color for the other tabs that are not active in order to differentiate them, please use the #CDCED9 for those tabs. 
![image](https://user-images.githubusercontent.com/27729173/33178255-d87340f4-d065-11e7-95c4-be14b839362e.png)

Thank you!

**Comment by pat270** [comment]
Hey @emiliano-cicero,
Component teams shouldn't be using Navbar, but a Navbar variant (Navigation Bar, Management Bar, or Application Bar) in their components. All the colors should match the ones defined in Lexicon. The only time they would use Navbar is if they wanted to create a custom Navbar style that isn't covered by [Navigation Bar](http://pat270.github.io/lexicon/content/navigation-bar/), [Management Bar](http://pat270.github.io/lexicon/content/management-bar/), or [Application Bar](http://pat270.github.io/lexicon/content/application-bar/).

Clay uses Navbar as a base component for the other horizontal navigation like bars. [Lexicon 2's Navbar](https://lexicondesign.io/docs/patterns/Navigation/horizontalNav.html) pattern is defined in Clay as Navigation Bar, [Header WIP](https://lexicondesign.io/docs/patterns/Navigation/header.html) is Application Bar, and [Management Toolbar](https://lexicondesign.io/docs/patterns/Toolbars/management_bar.html) is Management Bar. Unfortunately we can't follow Lexicon's naming convention 1 to 1 because Bootstrap 4 has reserved the Navbar class name and this component pattern fits best with Lexicon's different horizontal navigations.

The first navbar with blue active is just a navbar without any color modifier classes. It should look that way because it's just inheriting colors from the base nav component. I will have to revisit and update the [Nav](http://pat270.github.io/lexicon/content/nav/) component colors. I'm not sure if it will fix this issue since the Nav component is also a base component that shouldn't really have too many color styles.

The dark navbar colors are the base for the colors used in Lexicon's Header WIP and changing these would break the colors for Header WIP. We can tackle the color differences from many angles, but I think the core issue is the lack of documentation and naming inconsistency between Lexicon and Clay. I will add some documentation to the Navbar page and Home page to help clarify some of the confusion.
