### ISSUE TITLE
[Date Picker] Hyphen vs Slash

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3980]
I'm working on a new variant for the date picker component to allow users to select a date range (see [LEXI-1127](https://issues.liferay.com/browse/LEXI-1127)) and I noticed Clay is using hyphens by default in the format of the date. 

In the new variant I was planning to use the following format using slashes and a dash: "YYYY/MM/DD – YYYY/MM/DD". 

<img width="463" alt="date range" src="https://user-images.githubusercontent.com/21216422/110575739-b1374e00-815f-11eb-8574-652cdc17c3b8.png">

I read that this is defined by the formatting rules of [date-fn](https://date-fns.org/v2.14.0/docs/format)s which is an implementation of the [unicode technical standards](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table). 

I have four questions:

1. Are the hyphens "-" used in the format date related to the internationalization feature?
2. Could we set by default to use "/" instead of "-"? 
3. Do we have a [forgiving format](http://ui-patterns.com/patterns/ForgivingFormat) feature?
4. Do you have any technical recommendations for the new variant I'm working on?

Thanks!

**Comment by matuzalemsteles** [comment]
Hey @drakonux, answering some of your questions:

> Are the hyphens "-" used in the format date related to the internationalization feature?

I think this is [related to internationalization](https://docs.oracle.com/cd/E19455-01/806-0169/overview-7/index.html), some languages seem to use "-" instead of "/".

> Could we set by default to use "/" instead of "-"?

I do not see any problems in defining to use this standard, it is worth remembering that Clay is not opinionated in this part, it allows an API that teams can change the date format according to the internationalization mechanism...

> Do we have a forgiving format feature?

Well, as I said above, Clay provides the APIs needed to format the date and deal with internationalization but does not automatically detect the user's language, this is up to those who are using Clay to implement their own mechanism.

> Do you have any technical recommendations for the new variant I'm working on?

These are some of the questions that come to my mind right now, maybe I can come up with more when we have the document with the details.

- I believe that the user will also be able to write in the right input? maybe it's time to implement a masking mechanism to make typing easier and not break with the parse system.
- Will the date range have any limits? I can have a range of years, months...
- Will the Data Range allow extension points, such as adding the timer?

**Comment by drakonux** [comment]
Thanks Matu!

> I think this is related to internationalization, some languages seem to use "-" instead of "/".

👌

> I do not see any problems in defining to use this standard, it is worth remembering that Clay is not opinionated in this part, it allows an API that teams can change the date format according to the internationalization mechanism...

👌 We are using "/" instead of "-" in our documentation but it's ok. We plan to update it on [LEXI-975](https://issues.liferay.com/browse/LEXI-975). We will give a recommendation. of use. 

About forgiving format :

> Well, as I said above, Clay provides the APIs needed to format the date and deal with internationalization but does not automatically detect the user's language, this is up to those who are using Clay to implement their own mechanism.

> I believe that the user will also be able to write in the right input? maybe it's time to implement a masking mechanism to make typing easier and not break with the parse system.

I think both are related. I was trying to find out if we do something to help the user typing the date. We will request improvements in that line with [LEXI-975](https://issues.liferay.com/browse/LEXI-975)

> Will the date range have any limits? I can have a range of years, months...
You are right. I've added that requirement to the definition doc. I think the component should provide two properties:

- Min number of days between the start and end date.
- Max number of days between the start and end date. 

> Will the Data Range allow extension points, such as adding the timer?

Currently, I don't have any requests to require it. However, I would request a new side extension point.

**Comment by matuzalemsteles** [comment]
Thanks @drakonux!

**Comment by matuzalemsteles** [comment]
Hey @drakonux I will go ahead and close this ticket I think the main question has been answered, if you have any further questions feel free to open an issue or reopen this. Thanks again!
