### ISSUE TITLE
[Date Picker] Unexpected behavior using keyboard arrows

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3981]
Reviewing the current behavior of the [date picker](https://clayui.com/docs/components/date-picker.html) component I noticed that the calendar behaves in a different way I expected:

![focus-jump-using-keyboard](https://user-images.githubusercontent.com/21216422/110577464-fad56800-8162-11eb-9614-63105ed0f4b1.gif)

**Steps to Reproduce**
1. Open the calendar
2. Click on a date
3. Click on the input (to change manually the date)
4. Press the right arrow ➡️  
5. Click on the input (to change manually the date)
6. Press the right arrow ➡️ 
7. ~Delete the date~

**Expected behavior**

1. Pressing ⬅️ ➡️ moves left/right one char position the cursor
 
2. Besides, when the cursor is placed:

AT THE START of the string:

- Pressing ⬆️ or ⬅️: nothing
- Pressing ⬇️ : move the cursor to the end of the string

AT THE END of the string:

- Pressing ⬆️ : move the cursor to the start of the string
- Pressing ⬇️ or ➡️ : nothing

cc\ @marcoscv-work

**Comment by matuzalemsteles** [comment]
I think this is related to the focus control that we have enabled for Date Picker to also use the arrow keys, I think we can disable it for now.

**Comment by drakonux** [comment]
I thought the keyboard support for the "calendar" is important. Are you suggesting disabling that? that will deteriorate the accessibility of the component, isn't it?

**Comment by marcoscv-work** [comment]
Probably we would need to disable the current focus control and create a specific behavior for data piker

**Comment by matuzalemsteles** [comment]
Yeah, it won't cause so much trouble because we still have the focus. But yes, we need more details about the behavior of focus in Date Picker so that we can improve this in Date Picker and maybe also for Color Picker.

Some libraries implement different focus behaviors on Date Picker, when there is a little time left (when passing this migration that I'm working on), I can bring up some use cases so that we can think about it more.
