### ISSUE TITLE
SVG paths states

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#3997]
## Should we create different state icons instead of trying to modify internal SVG paths?

Since Liferay portal is using svg4everybody and it's creating a Shadow DOM closed, we cannot customize internal SVG paths:

![image](https://user-images.githubusercontent.com/7963804/112129842-1e1eff00-8bc8-11eb-9e6e-b01fc7d18682.png)

So functionalities like management-bar order icons are not working correctly in portal:
https://clayui.com/docs/components/management-toolbar.html

### Proposal:

We can change the classes path control for show/hidden the correct state icons, for this we will need to create three new icons: "order not applied", "order up", "order down":

![image](https://user-images.githubusercontent.com/7963804/112130297-a30a1880-8bc8-11eb-87d2-afa4971d7013.png)

**Comment by dsanz** [comment]
**Need**
The underlying need here is to come up with a solution to represent 2 (and potentially 3) different **ordering states**:
- Ascending
- Descending
- None of the above (optional)

**Problem statement**
Currently, there is only one icon to represent ordering state. Therefore, the way to multiplex it to meet the identified need is to apply style _selectively_ (i.e. to specific parts of the icon) in order to signal different states.

In SVG parlance, each icon "part" is a '<path>'. When an icon has several parts, we add specific classes to it. So, initially, the  [issue](https://github.com/liferay/clay/issues/1606) was solved by [adding a specific style](https://github.com/liferay/clay/pull/1851/files) when 2 class selectors were present. That should make it possible to use different colors for different paths (in this case, arrows in the icon).

`<use>` element is our mechanism to include SVG elements in the page. We use it from our `<liferay-ui:icon>` and `<clay:link>` tags, and also as direct markup from a bunch of JSP and JS files. `<use>` allows to reuse SVG content by introducing a (closed) shadow dom node where the referenced SVG content is deeply cloned. This behavior is stated in the [svg 1.1 recommendation](https://www.w3.org/TR/SVG11/struct.html#UseElement) and similarly described in the [svg 2 candidate recommendation](https://svgwg.org/svg2-draft/struct.html#UseShadowTree).

This mechanism works when the SVG is directly added (not cloned via `<use>`), as illustrated here:

![image](https://user-images.githubusercontent.com/861014/112200090-2a7a7a80-8c0f-11eb-8628-0eb9ff302de4.png)

Because of how shadow dom works, the classes inside the cloned svg content are not visible to the external (non-shadow) dom in terms of CSS selectors. This means that style properties based on selectors crossing a shadow dom tree will never apply to the elements in that tree, invalidating any mechanism based on this.

**Analysis**
As additional context, it's worth mentioning that style properties can leak into the shadow dom when they apply to parent elements of the shadow root. This allows to implement different colors for the same icon as a whole, useful to show different meanings:

![image](https://user-images.githubusercontent.com/861014/112201501-98737180-8c10-11eb-8fe7-2465df5dca51.png)

Although there are some ~techniques~ hacks to propagate styling through shadow dom [in the context of svg](https://tympanus.net/codrops/2015/07/16/styling-svg-use-content-css/), the point is that there is a difference between the two use cases above: whereas the former tries to act upon a part of the icon, to signal different states, the latter changes a property which applies to the full icon, to signal different meanings (average vote vs individual vote).

After a conversation with @drakonux, there are additional context/background about how icons are designed in lexicon. Lexicon follows some [principles](https://gist.github.com/natecavanaugh/b9546c4215e5d5ef88a1b9d6ae2041a3#lexicon-icon-design-guidelines) to develop icons. The [icon library](https://www.figma.com/community/file/869683830747037733?preview=fullscreen) reflects them. For the purposes of this issue, I'll higlight a couple of them:
 * Icons should only use one color, which is pure black for all elements
 * Icons should not have any style elements embedded or use any CSS for presentation (in fact, at the very most, only fill="none" is acceptable as a presentational attribute)

As a result, lexicon is **reluctant to include an icon using more than one color** to signal state as it would break the design principles used for the rest of the icons.

For some icons, there exist **"full" and "empty" variants**, which are implemented as **separated icons**, still using a single color. In practise, that was enough to represent **different states** such as emitted votes (via full stars/thumbs) vs non emitted ones (empty variants). Unfortunately, this is not enough to represent what we need.

Still, we need a proper solution for this icon as otherwise implementors would make their own choices as it's the case of the current **dataset display** implementation, which uses [separate arrow icon pairs](https://github.com/liferay/liferay-portal/blob/40d130bfe5f2abbfd1f2dbbe4317959a86cc78f0/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/data_set_display/views/table/TableHeadCell.js#L92-L109) to represent the order state of columns. Obviously, that does not sound as the right path to follow if we want to be aligned with Lexicon design principles.

**Conclusion and action items**
Following current design practises, it looks like the need will be addressed by separate icons, however, the specific solution and design has to be created by the Lexicon team, then incorporated to the management toolbar and to clay.

Action items:
- [ ] Request a design for this need to the lexicon team. This should end up with new icons to represent the state
- [ ] Request a redesign for the management toolbar to properly **signal** and **change** the ordering state depending on the selected field
- [ ] Request a redesign for the table component to properly **signal** and **change** the ordering state on a per-column basis, for those columns which are sortable
- [ ] Incorporate the icons to clay
- [ ] Implement the changes in the management toolbar
- [ ] Implement the changes in the data set display table view component

**Comment by pat270** [comment]
The best way to go about this, IMO, is to have two separate icons like `order-arrow-up` and `order-arrow-down` and combine them via html instead of having 3 different icons with hardcoded colors. This will allow colors to be changed via CSS. We also won't add to the size of the SVG spritemap.

We already have them at https://clayui.com/docs/components/icon.html. They are just slightly shorter, not sure if that matters.

**Comment by jbalsas** [comment]
Closing here since the path is clear and @dsanz is on it. Added a brief comment back in https://github.com/liferay-frontend/liferay-portal/pull/928#issuecomment-810924884.

@dsanz, would be great if we could get a scoped effort to change the icon without having to go through the whole review in order to speed up the resolution of the issue in a reasonable way.

**Comment by dsanz** [comment]
Yes, we can do that @jbalsas I'm discussing the scope with the lexicon team as coupling this with the MT review might not be a good idea

**Comment by d80wrk** [comment]
Hopefully some constructive feedback, I know it's a year late:

"order not applied" doesn't make sense being "shaded dark" like that, if the sort order is not applied the icon should surely be uniformly shaded lighter. Having both arrows set to be shaded dark seems confusing as it's suggesting both states are true. That couldn't be true since you can't have a list ordered up and down at the same time.
