### ISSUE TITLE
ClayTable headers

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#404]
Lexicon specifies that each table header has to be bold on hover.

Table header section:
https://docs.google.com/document/d/1WGhuEebDWpTLNyIKiMCdjpJVL8ZVM3Fi1-paCMihMWg/edit#

**Comment by yuchi** [comment]
Usuals 2 cents: font weight changes on hover (or interactions generally) is a recipe for problems since you can't reliably know the final width of the text.

**Comment by carloslancha** [comment]
cc @victorvalle

**Comment by yuchi** [comment]
By the way Google managed to do it using Roboto on Google News (tabs if I recall correctly)

**Comment by pat270** [comment]
I agree with @yuchi once again. I'm not a fan of bold on hover and bold on active (for SPA's) because of the width issue he's mentioned. Font's don't grow proportionately when bolded in macOS or windows. It grows to the right, which can either shift content to the right or left. To make something like this work requires a lot of janky hackery. There might be a pure CSS method out there that I don't know about. If you know/find one please tell me.

**Comment by yuchi** [comment]
A good alternative is using color with smaller weights. A muted gray appears as thinner. Don't forget about a11y constraints in the process!
