### ISSUE TITLE
Nav nested has lost its previous styles

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#405]
The styles are defined here:
https://lexicondesign.io/docs/patterns/Navigation/verticalNav.html
![image](https://user-images.githubusercontent.com/7963804/34716253-9023f32c-f52f-11e7-9dd0-87a95e71b7ee.png)

Currently and from Clay beta 4 it looks:
![image](https://user-images.githubusercontent.com/7963804/34715891-77e65706-f52e-11e7-87f7-86383478b2ec.png)

There is an issue in Liferay portal:
https://issues.liferay.com/browse/LPS-76907

**Comment by pat270** [comment]
Hey @marcoscv-work,
Bootstrap 4 removed active styling from base navs (http://getbootstrap.com/docs/4.0/components/navs/#base-nav). Nav Nested is now a base component for creating nested navigations. We will need to add colors and active styles to the compatibility layer.

Lexicon 2 also reworked the pattern so that it collapses in mobile (https://lexicondesign.io/docs/patterns/Navigation/verticalNav.html). I ended up creating a `menubar` component (http://pat270.github.io/lexicon/content/menu-bar-vertical/) to make it happen. There's only one type right now where it collapses at 767px. If we need one that doesn't collapse I can add one, I just didn't see the pattern in any of the Lexicon documents.

**Comment by jbalsas** [comment]
I assume this is also the problem showed in https://issues.liferay.com/browse/LPS-76907 where we're likely better off updating the markup.

Could either of you take a look?

**Comment by marcoscv-work** [comment]
Hey guys,

Lexicon guys have reviewed the component and they think **is correct**, so we would only need to create the clay component, add this nested navigation component to claycss.com and update it in portal.

Thanks @pat270 !

/cc @victorvalle
