### ISSUE TITLE
Wondering if we need/use some RTL icons

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#4077]
## Just wondering if we are currently using RTL icons and why we created some of them

I think we could remove some of them since their meaning is not changing or providing new or better information in RTL version. They are:

- copy-rtl (it is a standard icon, just a quick review in other tools to see they don't usually change it in RTL)
- flag-empty-rtl (the wind changed? haha)
- flag-full-rtl
- paste-plaintext-rtl (no meaning changes)
- paste-word-rtl (no meaning changes)

![image](https://user-images.githubusercontent.com/7963804/118673788-933e3780-b7f9-11eb-9496-4268545e21ff.png)

**Comment by drakonux** [comment]
Yeah you are right @marcoscv-work, I agree. 

As I said in [#175](https://github.com/liferay/liferay-ckeditor/pull/175) I made some icons that don't make sense to keep it, most of them caused by the rush to complete the icon set. 

But the rules are clear, if the direction of the icons doesn't give additional context it's because RTL is not needed. For example, bullet-list and numbered-list should have an RTL version. 

The direction of the wind is important 😅

**Comment by marcoscv-work** [comment]
Then can we create an issue to review and resolve this?
Probably those icons are not in use but we need to confirm it

**Comment by nhpatt** [comment]
Let's do it!

![](https://media.giphy.com/media/eK7TPkHbWslj9rEAng/giphy.gif)

**Comment by pat270** [comment]
Can we just use this issue?

**Comment by matuzalemsteles** [comment]
It makes sense to me, I think we need to create a new ticket to analyze the use of icons in DXP, and when we finish analyzing we will remove the icons from Clay

**Comment by marcoscv-work** [comment]
Checked, no uses of those icons in DXP:
https://issues.liferay.com/browse/LPS-132516

**Comment by matuzalemsteles** [comment]
Thanks @marcoscv-work, so I think it's safe to remove it from Clay
