### ISSUE TITLE
List Item Field API table is missing

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#4163]
On the [ClayList docs](https://clayui.com/docs/components/list/api.html) the List Item Field API table is not being rendered properly.

![image](https://user-images.githubusercontent.com/24564752/124748637-a6c96d00-df23-11eb-9cc0-25bb50ab46e4.png)

**Comment by julien** [comment]
Hey @kresimir-coko thanks for notifying.

I think this is similar to #4095 and #2994, and you it looks like you can find more info in #4130.

I personally have no idea of why we're using a "Table API creation engine that is based on react-docgen" (I don't even know what a Table API creation is) if it doesn't work ... Maybe using a more manual approach would be easier and more simple.

**Comment by diegonvs** [comment]
> "Table API creation engine that is based on react-docgen"

The idea of using it is to make API docs easier. Since it will traverse a TSX file and it will bring some details from TS and also from JSDocs(As far I remember). I remember we had a specific issue when using it but it never was prioritized. Some react libraries depends on react-docgen for creating those docs and it's a very useful thing to automate a part of our work.

> Maybe using a more manual approach would be easier and more simple.

I remember one of the things that Chema asked us is to try to automate everything as we can and using this APITable component was one of these automations. However, it requires a bit of maintenance and the docs were not prioritized too much for maintenance. 

I think @matuzalemsteles will have more points to talk about this decision :)

**Comment by matuzalemsteles** [comment]
Hey @kresimir-coko, thanks for reporting this, I think we probably forgot to modify this, because we removed the file in favor of using `ClayLayout.ContentCol`, so `ClayList.ItemField` just became an Alias. I sent a fix #4170

Hey guys, as Diego commented, this was a decision to automote our documentation, we have a lot of components, and keeping the documentation up to date was very difficult especially for APIs, so we adopted what is natural to create a generator and in the end we used `react-docgen` recommended by Greg at the time instead of creating ours.

A Table API generator is responsible for extracting the properties of a component, with description, default values and other information and creating this API that we have, something very common to facilitate maintenance, Storybook and other tools have a generator to facilitate this, Libraries like Adobe's [Baseweb](https://baseweb.design/components/button-group/) and [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/index.html) also use the idea of creating a Table API, it's not something new it's used a lot in documentation generators for React.
