### ISSUE TITLE
[Button] New Button definition

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#4174]
### Context
Due to the requests from DXP product teams about the customization of Clay components, we would like to redefine the essential component of a UI library: the Button component (see [LEXI-1205](https://issues.liferay.com/browse/LEXI-1205)). 

Most of the changes come from a project from the Solutions team called Dialect to define a different look and feel for site pages in DXP. Furthermore, they would like to have, in the long term, custom components for various industries (insurance, travel, banking). For now, Dialect will be a Theme in DXP.

![Dashboard](https://user-images.githubusercontent.com/21216422/126484282-eb4780a6-a2d0-4d13-afc5-649bf6f45800.png)

In addition, to allow this kind of creations, we are working on [LEXI-1204](https://issues.liferay.com/browse/LEXI-1204) to define a token definition (@hold-shift is working on it). 

### Approach
Our approach is the following:

1. Create a new button component to serve as a basis for other components

<img width="158" alt="Split Button" src="https://user-images.githubusercontent.com/21216422/126480760-4b238e7b-aa89-4bdd-a51f-4cae4ee6280e.png">

2. It has to be flexible enough to allow DXP product teams to create their own Buttons.  

<img width="474" alt="Custom Primary Button" src="https://user-images.githubusercontent.com/21216422/126480758-c390dc3c-fe6e-4693-b60a-11c9af9e3614.png">

### Proposal
To do so, we've created a new [definition document ](https://docs.google.com/document/d/1l-v23-Sh1AF5Tgoh6zgwHQfdPQ7ImG09WrFYjNQYJ4s/edit?usp=sharing)for the Button component. 

**Summary of changes**
- Set properties for attributes of the Button (height, font-size, background color)
- Add Outline as a new button variant
- Add Large as a new size of the Button
- Use a grid for the structure of the Button: this will allow us more control placing elements within (not mandatory)

**Disclaimer**
Since the new token definition is not finished yet, most of the values of the properties defined in the document are set using a value. However, we would like to have those properties set with available tokens, so once the token definition will be ready, we will update the Button document. 

Although the definition of the document is not closed, at least the parts related to this request are ready. Besides, the current Clay button works well, so probably, there won't be new requirements. However, Team-lexicon needs to continue updating the doc's content because the current one is from 2016, so there are many updates to do. 

cc\ @jbalsas @nhpatt

**Comment by pat270** [comment]
@drakonux 

I will need to update some variable code in Clay CSS (still using deprecated property names in Atlas), but we can already do this. Here is a quick example:

###### _clay_variables.scss
```
$white: #fff;

$primary: #085567;
$primary-d1: darken($primary, 5.1);
$primary-d2: darken($primary, 10);
$primary-l1: lighten($primary, 22.94);
$primary-l2: lighten($primary, 32.94);
$primary-l3: lighten($primary, 44.9);

$font-weight-light: 300;
$font-weight-normal: 400;
$font-weight-semi-bold: 600;
$font-weight-bold: 700;
$font-weight-bolder: 900;

$btn-primary: (
  background-color: var(--primary, $primary),
  border-radius: var(--btn-border-radius, 4px),
  border-width: var(--btn-border-width, 1px),
  color: var(--btn-font-color, $white),
  font-weight: var(--btn-font-weight, $font-weight-semi-bold),
  font-size: var(--btn-font-size, 16px),
  height: var(--btn-height, 40px),
  padding-bottom: 0,
  padding-top: 0,
  hover-bg: var(--primary-d1, $primary-d1),
  focus-bg: var(--primary-d1, $primary-d1),
  active-bg: var(--primary-d2, $primary-d2),
  disabled-bg: var(--primary, $primary),
);
```

**Comment by marcoscv-work** [comment]
Technically speaking, Dialect needs to make all those changes without implementing a new theme, so all those properties must be custom properties :-D

Basically, this is the definition of the minimum set of custom properties that we will need.

**Comment by pat270** [comment]
In my example, I'm making them custom properties without defining them. What I'm trying to say is that we can support custom properties in Clay CSS without coding it into the source.

**Comment by matuzalemsteles** [comment]
Hey guys I was taking a closer look at the definition and thinking a bit more about all of this, I have some concern as to what this might become in the near future when we have more components with the updated definition.

For example, I have the feeling that we are "replicating" CSS properties in CSS Variables to be changed at runtime, that's fine for a while, but I'm more concerned about how many variables we're going to make available per component. For example, it's ok, we have some variables to change styling things like font size, colors, bg... but it starts to become an abstraction when we start having more variables to change, `padding`, `border`... Component-specific, we're practically taking the scoped CSS properties to CSS Variables.

The point I want to make here is, if we're getting to a low-level abstraction level, that we're wanting people to create a new Button component just by changing the CSS Variable and it could do the same just by adding some CSS properties, let me try to clarify a little more:

```css
/* We're just taking the properties of the class and scoped it to CSS Variable.
 * But this is similar to someone creating a new class or just reusing the class name
 * and adding its properties.
 */
.btn.btn-primary {
  background-color: var(--btn-primary-background-color);
  border-color: var(--btn-primary-border-color);
  color: var(--btn-primary-color);
  padding-left: var(--btn-padding-x);
  padding-right: var(--btn-padding-y);
}

/* For example, this would be the same as the developer creating their own component via CSS. */
.btn.btn-primary {
  background-color: #333333;
  border-color: #33333;
  color: #ffffff;
  padding-left: 12px;
  padding-right: 12px;
}
```

I'm not taking into account the benefit this brings from changing it at runtime via Style Book for example or elsewhere. The concern here is if we're just covering for the case of Dialect, because in the end it's not a Lexicon specification but a web implementation specification, so I'm kind of concerned about how generic Lexicon might become, I see the benefits of Design System when the possibility of it is to allow changing changes in the implementation of a component and that this is replicated throughout the interface without the need to change in each place it is used but when we start to define properties at this level of granularity I have a bit of worry if we are running away from this idea.

Dialect will have its base mounted on top of the CSS and React components to create its own style, at the very end it will have its own version of Design System for each customer, the benefit of what I see is just a reuse of CSS standards and the reuse of components , Clay's CSS is pretty much an alias to keep these patterns since you only change the variables at that level of granularity.

I don't know if I could explain what I'm thinking, but my concern is, allow this level of granularity, what moves us away from regular CSS?!

For example, Tailwind appeared at this same level of granularity, but its proposal is a utility with some unscoped standards, almost a translation of CSS properties to classes with a certain level of abstraction, many people have seen the value of this in not necessarily needing touching on CSS or having many patterns, such as spacing, offering uniformity to the "APIs", for example, spacing, padding, more abstract classes that add more than one property... that is, it takes Tailwind to the level you want can build anything with it. What I see is that we are almost at this level but I would say that we don't have a certain kind of limit, as far as it can go, we just use CSS variables translated into CSS Variables. The concern of embedding all of this in Clay and at the same time as part of Lexicon is that it starts to slip away from the line of reasoning of a Design System in my view and give it such high freedom that we can tie and smother Clay CSS the large amount of APIs being added.

Another point, if we want them to reuse the React components, could we draw other strategies? React components can follow a headless philosophy that is without style, I've seen some cases being thought this way to allow components to be used in any Design system up to a certain level of implementation, Tailwind also brings this idea with Headless components React, Vue... but they are few components. On a CSS level, I think I could just let them create their own properties on top of Clay's base classes or whatever pattern they want, we can think more about that if need be.

In a world where DXP is in SaaS like LOL, instead of dealing with Themes being a Style Book or anything else via the UI, we should think about a foundation based on uploading or uploading pre-compiled CSS files to the Cloud, being stored in some S3 with CDN... well this is what Shopify has been doing in its infrastructure, this is where CLI starts to appear to help deploy these resources, I think trying to take everything to be edited in the UI and stored in a DB, in the end, we're just overloading ourselves with more abstract pieces.

Well, that's my point of view just to make it clear and it's some of the concerns I have the most about how we're handling this to allow you to change pretty much anything in CSS. Let me know if that's a valid point too.

**Comment by pat270** [comment]
> In a world where DXP is in SaaS like LOL, instead of dealing with Themes being a Style Book or anything else via the UI, we should think about a foundation based on uploading or uploading pre-compiled CSS files to the Cloud, being stored in some S3 with CDN

This is the way. It gives so much flexibility. We hand off compilation to the user and don't have to worry about it. They can choose what to include and remove. I would go as far as allowing any of our module CSS to be replaced in this way.

`<textarea class="form-control" id="clayCSSReplacement" name="clayCSSReplacement" placeholder="Paste your Clay CSS replacement here."></textarea>`

DONE!

If they want a fancy UI with dropdowns, autofill, and color pickers, create a separate portlet, website, or just use the clay repo that will compile Clay CSS with your custom values. You can copy and paste directly into DXP.

**Comment by nhpatt** [comment]
> Hey guys I was taking a closer look at the definition and thinking a bit more about all of this, I have some concern as to what this might become in the near future when we have more components with the updated definition.

@marcoscv's needs are centered in the button component (he literally told us that it was the main issue preventing reuse in the last meeting, right?) and it's also the focus of this issue... I would try to not conjecture about the shape of the solution for the next components because I think it will be different.

> For example, I have the feeling that we are "replicating" CSS properties in CSS Variables to be changed at runtime, that's fine for a while, but I'm more concerned about how many variables we're going to make available per component. For example, it's ok, we have some variables to change styling things like font size, colors, bg... but it starts to become an abstraction when we start having more variables to change, padding, border... Component-specific, we're practically taking the scoped CSS properties to CSS Variables.

That's a valid concern but IMHO I don't think it applies to the button solutions right now, as I think that the proposed variables (with Patrick solution none, as all the definitions fall onto Dialect side) but also with the "Expose CSS variables in Clay" were reasonable as not-a-lot.

> The point I want to make here is, if we're getting to a low-level abstraction level, that we're wanting people to create a new Button component just by changing the CSS Variable and it could do the same just by adding some CSS properties, let me try to clarify a little more:

Something that they can currently do (and are doing) with a theme. We are trying to add a new feature to simplify that.

> so I'm kind of concerned about how generic Lexicon might become, (...) but when we start to define properties at this level of granularity I have a bit of worry if we are running away from this idea.

I'm concerned too but here is where Lexicon and ourselves will have to decide what it makes sense and what it doesn't. I don't think Clay can be a meta design system that implements several different design systems. But I do think it can implement several Lexicon-inspired design systems or at least be more generic to allow easier replacements.

> I don't know if I could explain what I'm thinking, but my concern is, allow this level of granularity, what moves us away from regular CSS?!

I don't see it as that we are moving away from regular CSS. The solution of adding a theme is there but we offer more options.

> For example, Tailwind appeared at this same level of granularity, but its proposal is a utility with some unscoped standards, almost a translation of CSS properties to classes with a certain level of abstraction, many people have seen the value of this in not necessarily needing touching on CSS or having many patterns, such as spacing, offering uniformity to the "APIs", for example, spacing, padding, more abstract classes that add more than one property... that is, it takes Tailwind to the level you want can build anything with it. What I see is that we are almost at this level (...)

IMHO I think we are very far from that level. Tailwind started as a utility library of css classes. What we are proposing here in to add more types of buttons and expose some internals of the design system, generyfing it but without changing the goal.

> but I would say that we don't have a certain kind of limit, as far as it can go, we just use CSS variables translated into CSS Variables. The concern of embedding all of this in Clay and at the same time as part of Lexicon is that it starts to slip away from the line of reasoning of a Design System in my view and give it such high freedom that we can tie and smother Clay CSS the large amount of APIs being added.

This is also a very valid concern that we have to balance.

> we should think about a foundation based on uploading or uploading pre-compiled CSS files to the Cloud, being stored in some S3 with CDN...

This is a good idea, that we are already considering. 

Take into account the graduated approach (did you see this document?)... Liferay has always been stellar at allowing complete customization for Liferay developers and we less stellar in simpler customizations.. But the entry barrier to change everything is very high, to be able to create a theme or to be able to replace Clay CSS you have to know A LOT on how everything is structured and hope it doesn't break in the next update... it's simply a lot of work.

The idea is not to abandon this, we still want to be able to be customizable even at the last pixel but we also want to provide easier options for less Liferay/Clay oriented developers. Are those CSS variables exposed in the buttons enough to support your use case? great, customize them via java code, a property file in JSON or even an UI. Is not enough? add a CSS to replace what you want.

**Comment by nhpatt** [comment]
> If they want a fancy UI with dropdowns, autofill, and color pickers, create a separate portlet, website, or just use the clay repo that will compile Clay CSS with your custom values. You can copy and paste directly into DXP.

I see value in both approaches. Are the CSS properties exposed enough for your needs? No, go ahead, add your CSS. My idea is to add less powerful options for less Liferay-experienced developers that need less customization :)

**Comment by matuzalemsteles** [comment]
Hey @nhpatt, thanks for answering ❤️!

> @marcoscv's needs are centered in the button component (he literally told us that it was the main issue preventing reuse in the last meeting, right?) and it's also the focus of this issue... I would try to not conjecture about the shape of the solution for the next components because I think it will be different.

Yes, I understand that. But I think if we are going to add tokens for buttons we will probably add to Checkbox, Badge... and smaller components if we consider Dialect Design, otherwise, it would be a little inconsistent since the goal is also Dialect. But anyway we can also wait for the next definitions to have an input dimension of all this.

> That's a valid concern but IMHO I don't think it applies to the button solutions right now, as I think that the proposed variables (with Patrick solution none, as all the definitions fall onto Dialect side) but also with the "Expose CSS variables in Clay" were reasonable as not-a-lot.

Yeah, I think just balancing and not exposing all possible properties can be a way to keep control of what's exposed and for sure bringing CSS variables to the DXP has more control of that.

> I'm concerned too but here is where Lexicon and ourselves will have to decide what it makes sense and what it doesn't. I don't think Clay can be a meta design system that implements several different design systems. But I do think it can implement several Lexicon-inspired design systems or at least be more generic to allow easier replacements.

Yeah, this is quite complicated because of Dialect's input this decision becomes more difficult and also how are we going to do it, not that it will be difficult but there are several ways to make this possible but just a matter of what is the best way.

> I don't see it as that we are moving away from regular CSS. The solution of adding a theme is there but we offer more options.

Yes, I think maybe that's the problem 😅, I don't necessarily mean that we're wrong to use CSS Variables to customize or simplify usage, but I'm more concerned when we granulate the possibilities of modifying a component's properties, taking into the Patrick's PoC, it looks good what we're allowing, I worry if we get to the level of defining, `padding`, `margin`...

> IMHO I think we are very far from that level. Tailwind started as a utility library of css classes. What we are proposing here in to add more types of buttons and expose some internals of the design system, generyfing it but without changing the goal.

Yes, I'm not necessarily saying that we are close to Tailwind but that despite being two different approaches, there are similarities in your goal, taking into account the proposed tokens, for example: Tailwind as it is a utility class that translates a lot of CSS properties in classes with light abstractions it is similar to the idea of translating a component's CSS properties into CSS variables. There is a difference, the Tailwind properties are reusable, bringing them into the Clay context, since we scope out CSS Variables at the component level it sounds like a translation, only when we take properties like `padding`, `margin`, and other properties.

Well, I don't know if it's clear but I'm taking more into consideration the issue of having CSS Variables at the level of allowing to define `margin`, `padding` and Lexicon to define the base structure of a button without taking the "foundations" of Lexicon to allow you to build any style when we do that it's not a Lexicon experience but just Web.

> This is a good idea, that we are already considering.

Oh good to hear that.

> Take into account the graduated approach (did you see this document?)...

Hmm no, I didn't see it. you could send the link here or Slack to take a look 😬

> But the entry barrier to change everything is very high, to be able to create a theme or to be able to replace Clay CSS you have to know A LOT on how everything is structured and hope it doesn't break in the next update... it's simply a lot of work.

Yeah, I totally agree, maybe a big problem with this is allowing you to change a thing N ways at different levels, sometimes being a little restrictive is good for keeping healthy, that's usually what swells up and what lengthens the learning curve.

> I see value in both approaches. Are the CSS properties exposed enough for your needs? No, go ahead, add your CSS. My idea is to add less powerful options for less Liferay-experienced developers that need less customization :)

Yeah, I think when we come to a balance it's great, for example, CSS Variables are for style stuff... for people who don't understand the structure, Clay, CSS... that's good and has a lot of value. But when we take `padding`, `margin`, we are just implementing another way to modify Clay that you would get just via defining Sass variables or building new variations for its components ie just N ways to achieve the same goal but when we talk about a select group of CSS Variables, there is a real more substantial value. It makes sense?

**Comment by brunofernandezg** [comment]
After talking to @drakonux and @nhpatt we can close this issue.
It will be need it to update the documentation, and if something else is required we will open new issues.

**Comment by pat270** [comment]
@drakonux I think so. There is a demo covering those use cases (https://pat270.github.io/clay3-test-site/). The source is at https://github.com/pat270/lexicon/tree/clay-to-dialect/packages/clay-css/src/scss/themes/dialect. We also added CSS variable support.

**Comment by drakonux** [comment]
Thanks Patrick! ⭐
