### ISSUE TITLE
@clayui/modal allow passing CSS classes to Modal Footer, Modal Body, and Modal Backdrop

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4221]
https://issues.liferay.com/browse/LPS-137335

I have a problem. I ran into a situation where I need to isolate most components of a modal except whatever is contained in the body. I'm unable to do so because I can't pass custom CSS classes to Modal Footer, Modal Body, and Modal Backdrop. This feature would be beneficial to users in general imo.

![modal](https://user-images.githubusercontent.com/788266/129622173-cfa66e55-9556-4139-9d17-7b7d114a60a1.jpg)

**Comment by matuzalemsteles** [comment]
Hey @pat270 I think this could be possible just by adding a second scope over the body, for example:

```jsx
<Provider spritemap={spritemap} theme="themeless">
 {...}
</Provider>
```

I think it doesn't make sense to add a new API to the component because Modal is fully controlled in DXP, or maybe we have to add a new API in Modal's implementation in DXP to allow adding a second scope only in the body. Just to illustrate what I mean using Clay's components.

```jsx
<Provider spritemap={spritemap} theme="cadmin">
	<ClayModal
		observer={observer}
		status="info"
	>
		<ClayModal.Header>{"Title"}</ClayModal.Header>
		<ClayModal.Body>
			<Provider theme="themeless">
				<h1>{"Hello world!"}</h1>
			</Provider>
		</ClayModal.Body>
		<ClayModal.Footer
			first={
				<ClayButton.Group spaced>
				<ClayButton displayType="secondary">{"Secondary"}</ClayButton>
				<ClayButton displayType="secondary">{"Secondary"}</ClayButton>
				</ClayButton.Group>
			}
			last={<ClayButton onClick={onClose}>{"Primary"}</ClayButton>}
		/>
	</ClayModal>
</Provider>
```

**Comment by pat270** [comment]
@matuzalemsteles It doesn't work that way with the CSS unfortunately. Once the parent element is scoped, everything is scoped. It will reset the styles inside the body unless the body content is in an iframe.

**Comment by matuzalemsteles** [comment]
> It doesn't work that way with the CSS unfortunately. Once the parent element is scoped, everything is scoped. It will reset the styles inside the body unless the body content is in an iframe.

Yes, I understand, in that case, `themeless` could not revert as we did for `cadmin` so that any property above it has no effect, the same would apply to `themeless`. But if this is too complex, we can only isolate parts of Modal.

> Edit: I also this modal is using the Liferay.Util.openModal api. We have no opportunity to add a custom provider this way.

In fact we can, `openModal` uses `render` to render the React component, that wouldn't be a problem. https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L271

The idea of `Provider` with `theme` is that it will target elements that are using `React.createPortal`.

**Comment by pat270** [comment]
This is a stupid question but I'm going to ask it anyway. I think it might be helpful. If we wanted to use Provider in modal.js:

```js
import {Provider} from '@clayui/core';

...

<ClayModal.Header>
  <Provider spritemap={spritemap} theme="cadmin">
    {headerHTML ? (
      <div
        dangerouslySetInnerHTML={{
          __html: headerHTML,
        }}
      ></div>
    ) : (
      title
    )}
  </Provider>
</ClayModal.Header>
```

could we also do:

```js
<Provider spritemap={spritemap} theme="cadmin">
  <ClayModal.Header>
    {headerHTML ? (
      <div
        dangerouslySetInnerHTML={{
          __html: headerHTML,
        }}
      ></div>
    ) : (
      title
    )}
  </ClayModal.Header>
</Provider>
```

**Comment by matuzalemsteles** [comment]
Yes, we can, for now, this would have no effect because the Provider doesn't add a wrapper with the `theme` class on `children` but just propagates to all elements that use the React.Portal. I'm doing it right now testing in TreeView https://github.com/liferay/clay/pull/4218#discussion_r688618914

As these are a pretty simple case just adding `<div className="cadmin" /> ` would be better than adding the `Provider` which instantiates other things too, it would be more useful if some element is on top of the React.Portal

**Comment by pat270** [comment]
> I think it doesn't make sense to add a new API to the component because Modal is fully controlled in DXP

So I've been trying to implement a solution, but I'm struggling to without deviating from Clay CSS markup structure. We don't have full control in DXP unless we don't use [ClayModal.Footer](https://github.com/liferay/liferay-portal/blob/9d8b3fc8e2d4b4a8ad3b61dba9979297a1169959/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L226-L248) in DXP's `Modal.js`. Wrapping pieces with `cadmin` inside a component like Modal will cause style issues that will be hard to correct in the future. It would be great if we could keep as close as possible to Clay CSS markup structure and not have to do:

```
<div class="cadmin">
    <div class="modal-header"></div>
</div>
<div class="modal-body"></div>
<div class="cadmin">
    <div class="modal-footer"></div>
</div>
```

**Comment by matuzalemsteles** [comment]
@pat270 I see, well we can modify or add a new API to the footer if need be, let me know if you need anything.

Well can wrapping the elements break the look? I remember I had a lot of problems in the past trying to add an extra div to make it easier to integrate with React.Portal in Modal but I always had visual problems but I think the extra div were above the `.modal-content` element.

**Comment by pat270** [comment]
Extra divs will break the look, I'm trying to avoid that as much as possible. I'll send a pr for just modal-body and modal-footer. I can work around not adding to modal-backdrop.
