### ISSUE TITLE
[Tooltip] The tooltip is off-center with respect to the application menu button at browser width <1250px

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#4249]
## What are the steps to reproduce?
This issue was discovered fixing this [other issue](https://issues.liferay.com/browse/LPS-138306), therefore this part should be deployed.

- Sign in as admin
- Go to Application Menu > Applications > Remote Apps 
- Resize browser to width less than 1250px
- See the tooltip in the Application Menu button
<img width="502" alt="Captura de pantalla 2021-09-01 a las 12 39 11" src="https://user-images.githubusercontent.com/9701095/131657645-a22e1454-e57c-44dd-9bf5-7291f152ea26.png">

## What is the expected result?
The tooltip should be centered with respect to the button.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.x  |

**Comment by julien** [comment]
Hey @veroglez I'm not sure this has to do with the tooltip component itself:

I looked at the [issue](https://issues.liferay.com/browse/LPS-138306) you mentioned and the corresponding [fix](https://github.com/liferay-echo/liferay-portal/pull/5674/commits/14928c872e18af1459f588ac90ff99f66cd88231), from what I saw this didn't actually solve entierly the problem: with the fix, the tooltip's arrow points in the right direction, but since there's no space for the tooltip to fit on the screen it doesn't look quite right: 

![](https://user-images.githubusercontent.com/5572/131983333-3cfd845e-28c8-4039-a82d-db2b7ae4995a.png)

In this case, I would suggest using `data-tooltip-align="bottom-left"`, which makes it look better (imho) 

![2021-09-03-11:17:51](https://user-images.githubusercontent.com/5572/131983495-539968a9-703f-4325-9fd0-7e7c2276e4cd.png)

Since this seems like an OK solution to me I've sent a follow up pull request [here](https://github.com/liferay-echo/liferay-portal/pull/5711), and if you are satisfied with the solution, feel free to close this issue.

Thanks

**Comment by veroglez** [comment]
Perfect @julien! Thanks, It a good solution. I review the pull request 👍 .

**Comment by julien** [comment]
@veroglez great

**Comment by matuzalemsteles** [comment]
I'm going to reopen the issue to investigate the possibility of repositioning the tooltip on Clay's side when there's no room to position it correctly.

For more context https://github.com/liferay-frontend/liferay-portal/pull/1450 the same problem.
