### ISSUE TITLE
[PaginationBarTag] Unexpected behavior when the component is loaded

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#4283]
## What are the steps to reproduce?
Add the PaginationBarTag taglib with the following configuration:
- totalItems: 6
- activeDelta: 2
- activePage: 1

https://user-images.githubusercontent.com/9701095/134196397-5538bb69-9afd-446e-b3eb-b3138a06d864.mov

## What is the expected result?
- An unexpected ellipsis should not appear when the component is loaded. 
- When the active page is 2 and the page is switched to 3, an unexpected 4th page should not appear.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.x |

**Comment by matuzalemsteles** [comment]
Thanks @veroglez for reporting this. It sounds to me like it's more related to taglib SSR rendering which is then fixed by runtime rendering, so maybe that's a way for us to investigate this issue.

**Comment by julien** [comment]
Hey @veroglez, I've sent a test pull request [here](https://github.com/veroglez/liferay-portal/pull/80) - before sending to our repository. 

I think it's good to report "tag" related issues here (since they are Clay tags it makes sense), but at the same time since the fix goes to DXP, could you please create an issue in Jira, because we'll need an LPS to submit the change. Thanks!

**Comment by julien** [comment]
@veroglez nevermind, I forgot issues created here actually generate an "IFI" issue, I guess I can use that.

**Comment by julien** [comment]
pull request submitted [here](https://github.com/liferay-frontend/liferay-portal/pull/1498)

**Comment by veroglez** [comment]
Thanks a lot @julien!
