### ISSUE TITLE
clayui.com Document how to vertically align alert-indicator with text

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4338]

**Comment by beltranrengifo** [comment]
hi @pat270 !
I'm trying to address [this bug](https://issues.liferay.com/browse/LPS-157502). In fact I've already sent a [pr](https://github.com/liferay-frontend/liferay-portal/pull/2478) for the JSP tag.
I was thinking about sending the same fix for ClayUI but after seeing this issue here I think maybe you have this solved in any other way...
Let me know whenever you can, thxs!

**Comment by pat270** [comment]
The reason for the difference is `AlertTag.java` is using different markup from the markup we use on clayui.com (probably due to misinterpretation). We can add `align-items: baseline` to `.alert-autofit-row`. I spent a good chunk of time revisiting this again and we can probably tweak some other things like setting `.alert-indicator`'s `line-height: 1`. It's insanely tedious to vertically align varying sizes of text and icons with CSS or I need to watch some CSS trick tips.
