### ISSUE TITLE
I've found that the styles between lexicon and clay in the dual list box are different, is that correct?

### ISSUE THREAD

**Issue by susanavr** [liferay/clay#4430]
## I've found that the styles between lexicon and clay in the dual list box are different, is that correct?

This is the clay snapshot: <img width="597" alt="clay" src="https://user-images.githubusercontent.com/32902604/141975966-2633452e-b0f8-44c4-884e-61eb2ed095d8.png">

And the Lexicon snapchot: 
<img width="566" alt="lexicon" src="https://user-images.githubusercontent.com/32902604/141975971-69f0d5bd-369b-4e6a-8b22-80ed98d3994a.png">

**Comment by julien** [comment]
Hey @susanavr, 

Thanks for reporting, and just to confirm you're right: there is a difference.

This is a good example of why I think Lexicon and Clay should unify their efforts and use only one website, because this isn't the first time this type of issue happens and probably not the last.

The last modification I can think of is [this](https://github.com/liferay/clay/issues/4312) one, followed by [this](https://github.com/matuzalemsteles/clay/commit/d4b963022bd2c6bf0c4f45ed3f9789db22ecf79a) pull request.
where the arrows to reorder the list where moved to the "right" side.

**Comment by drakonux** [comment]
I think the component is not following the design because it's using a native list box:

![Chrome](https://user-images.githubusercontent.com/21216422/141979082-0e0e411c-2e5a-461b-82d1-d96a711b23d0.png)
Chrome (macOS Big Sur)

![Edge](https://user-images.githubusercontent.com/21216422/141979083-7bea55bc-1899-438a-8503-9e8dbc4571bd.png)
Edge (Windows 10)

**Comment by julien** [comment]
@drakonux oh I see what you mean, by List Box, do you mean ?

```html
<select multiple size="8">...</select>
```

**Comment by marcoscv-work** [comment]
just remember that this component are following the native select-multiple-options and there were some styling limitations. IMHO we should be keep using the native component even if we have some limitations, in this case.. Lexicon should be the one which adjust with clay

**Comment by matuzalemsteles** [comment]
This issue is related to the recent discussion about this component in #3970.

**Comment by pat270** [comment]
I spent the morning messing with this and I'm just going to implement the hack. Chrome and Firefox will have the correct styles (I hope Edge does too, but I need someone to test). Safari is a lost cause for now, can't change much.
