### ISSUE TITLE
Update the Management Toolbar examples to follow changes in New, Info Buttons

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4483]
Lexicon made some changes to some elements of the Management Toolbar, in theory, we already support this because the components are low-level and can be composed to follow these use cases, so we've only updated the examples we have in the Storybook and the documentation.

For some cases there are some changes to the responsive mode that we have to evaluate if any CSS changes will be necessary.

- [Change the View button with a button group](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/1937343082/LEXI-1252+Change+the+View+button+with+a+button+group)
- [Fix the info button to the right](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/1943077369/LEXI-1254+Fix+the+info+button+to+the+right)
- ["New" button and responsive](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/1942225402/LEXI-1261+New+button+and+responsive)

**Comment by julien** [comment]
@matuzalemsteles I thought we agreed (during the meeting we had on December 2 2021) to move the management toolbar to DXP - has this changed since then?

**Comment by pat270** [comment]
Change the view button: We can hide the current dropdown toggle in desktop and show 3 buttons in desktop using the `navbar-breakpoint-down` utilities?

Info Button: We don't have dividers for navbar, but we could add it.

The New Button can be done by updating the content inside.

```
<button class="nav-btn nav-btn-monospaced btn btn-monospaced btn-primary" type="button">
  <span class="mx-4 navbar-breakpoint-down-d-none">New</span>
  <svg class="d-none navbar-breakpoint-down-d-inline-block"></svg>
</button>
```

**Comment by matuzalemsteles** [comment]
@julien yeah, we're still going to move but we still need to coordinate this and probably know when we're going to prioritize, for now, these changes are still on our side and some of them look like team requests so we can update what we still have on our side and help the MT on the side DXP if needed.

> Change the view button: We can hide the current dropdown toggle in desktop and show 3 buttons in desktop using the navbar-breakpoint-down-d-* utilities?

We can probably do this with classes, but now view mode needs to behave like a radio group, so maybe we need to change the CSS side here or add some new classes, this is a case I've never seen in our framework.

**Comment by julien** [comment]
@matuzalemsteles there's a meeting today about these changes with a part of the DXP team, I'll point them to this thread as I think they could perfectly take care of it. There's no real reason to keep this component in Clay anymore so we'll need to move this at some point.

**Comment by matuzalemsteles** [comment]
@julien Sure, no problem if they agree to that, we can ignore these changes here, let me know the result. Thanks!

**Comment by julien** [comment]
@matuzalemsteles here's what we discussed with @brunofernandezg, @carloslancha, @tinycarol and @drakonux:

- @tinycarol will work on analyzing the current changes and also check if it makes sense doing these changes here (or in DXP, for the moment, it seems that most of the changes should happen in DXP, but there might be something to do here too).

- We also want to know if somehow, at some point; it would be possible to use `clay-toolbar` as the base component for the management toolbar component, because it would make sense and that's what Clay should provide (as opposed to the management toolbar - which is very coupled with DXP)

- After that, if possible, we'll move the management toolbar to DXP and Lexicon will remove it from it's Figma (Clay) library; but that also involves moving some CSS around so we have to figure out what's needed and possibly avoid duplication in DXP

Right now, the goal is to analyze what's possible and how to do it, so we need to help @tinycarol as much as we can in case she has doubts.

I've mentioned everyone else so they can chime in and add more information if needed.

**Comment by matuzalemsteles** [comment]
Perfect, it makes sense for me to get on with it! Yeah, I think we can move the CSS too because the generated classes are MT-specific, I guess that shouldn't be a problem.

Regarding using ClayToolbar as a base, I'm not sure if it would be possible, most Clay components have very unique and specific classes of each component, they are not very reusable among each other. @pat270 can tell you more about this.

**Comment by julien** [comment]
@matuzalemsteles thanks for the additional information - when I mentioned using ClayToolbar, this is something that we're planning for the future - and if we need to deprecate some of our existing components along the way that's what we'll do, at the moment we're just analyzing what our options are in order to allow developers to build their "custom toolbars".

**Comment by matuzalemsteles** [comment]
Of course, @pat270 has been working on DX for navbars (SASS), so maybe we can get a better approximation of markup and element reuse over time without needing to have multiple specific components, we did the same with `ClayUpperToolbar`, we deprecated in favor of using `ClayToolbar`, maybe we can get that later for others like NavigationBar, Navbar...

**Comment by carloslancha** [comment]
Hey folks, just to add more information / clarification:

- Toolbar is just a responsive "box of stuff" where you can place things in certain points (summarizing)
- As @julien said, since DXP Management Toolbar is actually implemented in `frontend-taglib-clay`, using ClayManagementToolbar, most of the new features requested will be implemented in DXP. Only in the case something can't be accomplish with the current ClayManagementToolbar specs/API it will be included here.
- Management Toolbar is just an extension of a Toolbar to cover a DXP use case. That's what @drakonux clarified today.
- In [Clayui's Management Toolbar docs](https://clayui.com/docs/components/management-toolbar.html) we say that is an extension of Toolbar, but we're not using that component in Management Toolbar. This is what we think we need to work in: building the MT on top of the Toolbar. But we'll do it after adding the new features

**Comment by matuzalemsteles** [comment]
Yeah I agree, we can work on that, I think we've managed to reuse most of the stuff, but we still have some redundancy on the CSS side, for example, `tbar-nav` vs `navbar`...

Perhaps the navbar that is most part of MT would not need to be moved to DXP.

**Comment by pat270** [comment]
In terms of code, MT is an extension of navbar. If / when we update to Toolbar, we will need to add features to tbar.

If we move MT CSS to DXP, it should be able to stand alone even without Clay. We can cherry pick the navbar styles that are needed into MT. We can just move the whole thing after that.

**Comment by matuzalemsteles** [comment]
I'm closing this because these changes are getting into the work that Carlos and Carol are doing to bring MT to DXP, also officially this component has gone into a deprecated state on the Clay side and removed from the Lexicon core.
