### ISSUE TITLE
[ClayAlert] Alerts of variant stripe don't follow Lexicon's specifications.

### ISSUE THREAD

**Issue by rodrigopaulino** [liferay/clay#4524]
According to [Lexicon's definition](https://liferay.design/lexicon/core-components/alerts/) of an alert, independently of its variant, the icon and message should start 16px from its edge.

Here's an example of the `ClayAlert` React component (**_stripe variant_**) being used on Liferay DXP:
<img width="1792" alt="Screen Shot 2021-12-22 at 17 14 50" src="https://user-images.githubusercontent.com/11450348/147150677-20d50d30-f0d4-424f-98f1-329908075255.png">

Here's an example of the clay taglib `clay:stripe` on DXP as well:
<img width="1920" alt="Screen Shot 2021-12-22 at 17 15 52" src="https://user-images.githubusercontent.com/11450348/147150773-76c7a23b-53e6-401e-8b95-e5d56f7dfe09.png">

I assume both must have the same markup.

**Comment by pat270** [comment]
@rodrigopaulino the padding on the container looks like it's `1rem`. Where would the edge be in the screenshots?
![alert-fluid](https://user-images.githubusercontent.com/788266/147158074-f4426703-0912-43be-aa0b-6077ff8b3502.jpg)

**Comment by rodrigopaulino** [comment]
Hi, @pat270. Thanks for answering. To my understanding of the Lexicon's specification, the edge of the stripe should like this:
<img width="1920" alt="Screen Shot 2021-12-22 at 17 15 52" src="https://user-images.githubusercontent.com/11450348/147245977-978138e4-6764-488f-85a5-909f7ba58d97.png">

**Comment by pat270** [comment]
There is an undocumented rule that says the content should be capped at 1248px and centered for larger screens. @drakonux can confirm or deny.

**Comment by drakonux** [comment]
@pat270 is right. Currently, in DXP follows the [grid](https://liferay.design/lexicon/foundations/grid/) with a breakpoint at 1248px.  

However, @rodrigopaulino is right too, the design of the component is to behave fluid within the container placed.  

Said this, I think the best approach now @rodrigopaulino is to follow what other teams are doing. You can ask @victorvalle about it because he is the principal designer responsible for the common UX in DXP, and he is also pushing an [initiative ](https://issues.liferay.com/browse/LEXI-1158)to break those breakpoints and go to fluid (we helped him with that work).

**Comment by rodrigopaulino** [comment]
Thanks for clarifying, @drakonux! That said, I think we can close this for now, then. I'll let our team's designer know about this.

Once again, thank you both.
