### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by julien** [liferay/clay#4561]
In https://github.com/liferay/clay/commit/f8d477d8275538bdc7a6b256d880863b80aa6feb we added information about testing clay packages in DXP, 
however I found out that this sometimes works and sometimes doesn't, 
so it might be better to remove that section.

To be clear, today we have no way of testing clay packages in portal, 
which makes development quite hard.

I see this as another reason to move Clay into DXP as discussed in #3849

**Comment by matuzalemsteles** [comment]
I think we can test Ivan's CLI which was created for the same purpose as the `liferay-frontend-projects` packages. I will test this next week.

I think it doesn't work with `yarn link` and it has to do with our build systems in DXP and the module dependencies that sometimes you need to add in another module and run the build in two different places. I don't see this as a reason to move to DXP because we rarely need to do that.

**Comment by julien** [comment]
> I think we can test Ivan's CLI which was created for the same purpose as the liferay-frontend-projects packages. I will test this next week.

No thanks, it requires additional dependencies.

I'll repeat myself, but seeing how much time we lose with this, it's about time we move Clay into DXP, whether some like it or not.

**Comment by matuzalemsteles** [comment]
Closing this, we are using `verdaccio` to locally test Clay changes in DXP. See https://github.com/liferay/clay/blob/master/CONTRIBUTING.md#testing-local-changes-in-liferay-portal for more information.
