### ISSUE TITLE
@clayui/color-picker should persist current color when opening gradient selector.

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#4580]
https://storybook.clayui.com/?path=/story/components-claycolorpicker--custom-colors

# Steps to Reproduce:

1. Navigate to https://storybook.clayui.com/?path=/story/components-claycolorpicker--custom-colors
2. Paste or type a new color into the input. 
3. Click on the color swatch to open the picker.
4. Click the color droplet to open the gradient selector.

# Expected Result:

- The gradient selector displays the color added in step 2.

# Actual Result:

- The gradient selector displays the first custom color.

For reference here are 2 gifs. One shows Clay's behavior the other show the Chrome dev tools color picker behavior.

![claycolorpicker](https://user-images.githubusercontent.com/1609196/149730544-c9bc4561-a9fa-4e40-939e-7f88412d4179.gif)
![chromecolorpicker](https://user-images.githubusercontent.com/1609196/149730523-4bd21c6b-80e7-431d-a866-90b11829c5af.gif)

**Comment by ethib137** [comment]
Hey @matuzalemsteles thanks for your response... I really think this behavior is incorrect for custom colors as well, though. In fact, I think only changing the behavior when there are not custom color palettes will add additional inconsistencies between the color picker variants.

> The color typed in the field is never saved among custom colors. The color must be only reflected in the color square.

This should remain true, but can be handled by deselecting a custom color when the color picker input changes. I think this should always be the case that if you change the color picker input value, it should deselect the custom color. Otherwise you end up with strange inconsistent views like this. Also, where is this documentation? I couldn't find this line [here](https://liferay.design/lexicon/core-components/forms/picker-color/#gatsby-focus-wrapper)

![inconsistentInputwithSelectedCustomColor](https://user-images.githubusercontent.com/1609196/153138265-19773a91-04b5-4cf2-84e5-c3a8ffd6ba3d.png)

When you find yourself in the situation pictured above, you can still click on the  already selected custom color in order to apply it to the input, but I think this is unhelpful behavior. It would make more sense if the custom color was not selected, thus implying it is clickable.

Also, even when chrome dev tools includes custom colors, they still always maintain consistency between the current value and the value reflected in the color picker overlay. 

![ChromeColorPickerCustomColors](https://user-images.githubusercontent.com/1609196/153139618-967201fb-541d-476e-9f0f-09e3185ce038.gif)

Also one other thing, even with the [color picker custom w/o palette](https://storybook.clayui.com/?path=/story/components-claycolorpicker--custom-w-o-palette) the hue slider is not correctly positioned, even without changing the input value.

![HueSlider](https://user-images.githubusercontent.com/1609196/153140546-03bcfa18-f11d-4602-9d32-2322bb44a32b.gif)

@matuzalemsteles I'm wondering if it would be helpful/quicker to do a quick call in order to make sure we fully understand one another's points. If so, we have a bit of overlap at the end of my day and the start of yours.

**Comment by julien** [comment]
@ethib137, I reviewed the corresponding pull request (https://github.com/liferay/clay/pull/4649) and the behavior seemed correct to me: pasting a hex value, updates the value in the palette. 

If you don't mind, when you don't agree with the change, could you rather comment on the pull request directly or simply "request changes" in order to avoid this? Commenting on the issue itself is good, but it doesn't "reflect" that you are requesting more changes - it's not ideal but unfortunately that's how GitHub "works".

Feel free to revert the merged change in any case.

Thanks

**Comment by julien** [comment]
@ethib137 I've re opened the issue.

**Comment by ethib137** [comment]
Thanks @julien, I will certainly do that in the future. In this case, I think this change still brings a closer to the desired behavior so I don't see any issue with it being merged. I'm just hoping we can agree on additional changes as well. :)

**Comment by julien** [comment]
Thanks @ethib137 - I agree - Let's work on those additional changes to make sure everyone's needs are covered.

**Comment by matuzalemsteles** [comment]
Hey @ethib137, just answering some of your questions.

> Also, where is this documentation?

Implementation details you can find on google drive https://docs.google.com/document/d/1IUGl5VOWh6lqRa1baRoshVcytc8XbqVMkk30vRW4SM8/edit#heading=h.hd7lz9t31yrv, I think anyone who is logged in with the Liferay account on the Lexicon website can access the link to the document.


> Also one other thing, even with the [color picker custom w/o palette](https://storybook.clayui.com/?path=/story/components-claycolorpicker--custom-w-o-palette) the hue slider is not correctly positioned, even without changing the input value.

Hmm this really is a component bug, I'll send a PR to fix this, thanks.

---

Regarding the other implementation details, this makes sense to me too, and I agree with you, maybe opening Color Picker and it's already selected is causing this confusion. I also agree that when a custom color is not selected the editor should be consistent with what the user is typing, really this is much better. I'm fine with going with it.

Hey @drakonux just pinging you because I think this might impact the Lexicon spec a little bit, also I think we didn't have that very clear so this might be an improvement but let me know what you think of this behavior.

**Comment by emiliano-cicero** [comment]
Hey guys, David told me to look into this.

I think it makes sense to include this case and update our documentation. 

The way I see it, in case there is a manual color in the input, the color picker should: 
- open the panel without the previous custom color selected because the color has changed
- the manual color should be shown in the spectrum but not yet included in the custom colors
- with the panel is open and the manual color is shown: if the user clicks on an empty custom color, it can replace it with the selected color 

This should be enough for the cases we have, but if you need more advanced interactions we can always review the component or help with some customization.

**Comment by ethib137** [comment]
Thanks for the additional comments everyone... I agree with everything that has been said. Do we need an additional issue created for these changes?

**Comment by julien** [comment]
@ethib137 no we don't, thanks; but we do need to prioritize this somewhere. Which is something we can talk about with @dsanz.

**Comment by sergiojimcos** [comment]
Hi @julien @matuzalemsteles! I'm going to start this issue!

**Comment by matuzalemsteles** [comment]
Closing this, this was fixed by PR #4691 and included in v3.49.0!
