### ISSUE TITLE
Document Netlify deploy process

### ISSUE THREAD

**Issue by julien** [liferay/clay#4583]
We have a github action that deploy the storybook to Netlify, which has been failing 
for a couple of months now. There's nothing documented about this and most members of 
the Clay squad team don't have access to this account, so it would be nice to document this.

Additionally, if relying on other services means we depend on other departments to fix
these issues we should probably stop doing that since it's not practical.

**Comment by matuzalemsteles** [comment]
Things related to the site have nothing to do with Github Action, I also don't know if it's necessary to document this because I didn't really have to do any extra configuration on the Netlify side, probably if something broke it's on our side or we're reaching the usage limit of the platform.

In Netlify we just ask to run the `storybook:build` command the rest is the storybook CLI with the usual settings in the `.storybook` folder and the storybook documentation about it.

If something is failing, you can click Details in Cheks on Github PR to see the build failure log on Netlify, no membership is required. We depend on another department because charges are made to the Liferay account.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles one thing we might want to do is create a generic "frontend-infra" user for netlify and add that to our team's 1password vault, that way we can update config if needed and that way it isn't tied to a single user.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus Good idea, I think we can do that, it would be much better for sure. I think I can use our Frontend Infra email to create the account, it shouldn't be a problem, I'll do that tomorrow and open a ticket to replace the user with this new account.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles perfect!

**Comment by julien** [comment]
@matuzalemsteles, if we don't document this, how do you expect me to understand what's going on when something goes wrong and you are on PTO for a long time?
