### ISSUE TITLE
TreeView: Styles are only in cadmin

### ISSUE THREAD

**Issue by julien** [liferay/clay#4588]
I was wondering why the `treeview` related styles are only in 
the [`cadmin`](https://github.com/liferay/clay/blob/bc208f3afc08cd55f7eb2344938851feac762abb/packages/clay-css/src/scss/cadmin/components/_treeview.scss) "theme" (I don't even know if this is a theme).

I'm asking because when integrating the `TreeView` in DXP, a lot of "applications" don't use 
`cadmin` and that causes the `TreeView` to look "broken", for example:

![](https://user-images.githubusercontent.com/5572/150111630-d180d7b5-2f2f-42ed-8aab-5167e83b1d3d.png)

**Comment by pat270** [comment]
I thought this was going to be an admin only component. I don't think I researched all the uses of treeview enough. We can port it over to Clay.

**Comment by julien** [comment]
That would be great.

**Comment by matuzalemsteles** [comment]
@pat270 but isn't this just for the Admin? maybe some part of the DXP is missing the admin scope? Maybe we have some scoping issue here, as far as I know, all parts of the administration should be cadmin. It would be good to investigate why.

But anyway it's great to have the TreeView next to Clay CSS, I don't really like the idea of having specific components for a "theme".

**Comment by julien** [comment]
>  @pat270 but isn't this just for the Admin?

No. @matuzalemsteles as you'll remember from your treeview analysis task, that component isn't only used in "admin" sections.

**Comment by pat270** [comment]
If we use treeview inside a portlet that renders for a user not logged in, it wouldn't have access to cadmin styles.

**Comment by julien** [comment]
@pat270 yes, and on top of that some "applications" open modal windows that load "iframes" that don't include "cadmin" in their `<body>` element. In any case, I don't see why this would need to be an "admin" only component.

**Comment by pat270** [comment]
@julien modals and iframes are tricky, but cadmin should be loaded. Can you point me to where the modal is? Maybe we can add the cadmin class to the body or to the treeview?

**Comment by pat270** [comment]
Cadmin isn't very elegant, but I think is better than web componenting (new verb) our modules. Cadmin has two purposes:

1) Make some component CSS hard to overwrite
2) Reduce the footprint of Clay CSS

Treeview as cadmin only reduces about 5kb. It's not very much, but as it seems like we won't stop adding components; this adds up.

**Comment by matuzalemsteles** [comment]
@pat270 yeah, I agree we have to try to reduce the CSS this really has a very negative impact on DXP performance, as customers are looking at this more let's keep thinking of ways to get around this, maybe CSS being lazy-loaded according to component usage can reduce the CSS vendor for critical first rendering.

This can be a very considerable solution to optimize, not necessarily using CSS-in-JS, I had some tests with the Forms team to load the CSS on demand according to the component to split into chunks, it seems to have been a good solution.

**Comment by matuzalemsteles** [comment]
> No. @matuzalemsteles as you'll remember from your treeview analysis task, that component isn't only used in "admin" sections.

Which analysis? we only had the performance analysis as far as I know.

**Comment by matuzalemsteles** [comment]
> modals and iframes are tricky, but cadmin should be loaded. Maybe we can add the cadmin class to the body or to the treeview?

@pat270 In the demos, we added the `<Provider theme="cadmin">` to add the scope, this solves it but because it is an iframe it is necessary for the iframe to load the cadmin CSS, adding in the iframe body also works but not in the Modal that is loading the iframe due to security scope.

The problem is when the user is not logged in if the client loads a custom CSS it will probably change the component's look. Maybe for these cases, we can load cadmin CSS if it's always being inside an iframe, at least it won't be loaded in the first render to the non-logged user page only when opening the modal. I'm thinking more about the problems that can happen with the other components, would that be expected in these cases? in theory, a modal loading a TreeView should not be impacted by a client's custom CSS. If that's not a problem it seems ok to me, just to say I'm not against moving the TreeView to the usual Clay just that maybe we have a bug with cadmin.

It also seems that if you put the `cadmin` class together with the component classes it breaks the whole component, this is expected @pat270, right? just to confirm, in the ClayProvider we created an extra div to just add the `cadmin` class.

**Comment by julien** [comment]
> @pat270 In the demos, we added the <Provider theme="cadmin"> to add the scope, this solves it but because it is an iframe it is necessary for the iframe to load the cadmin CSS, adding in the iframe body also works but not in the Modal that is loading the iframe due to security scope.

@matuzalemsteles unfortunately, last time I checked this doesn't work in DXP - what I mean is that if you copy code from the storybook they usually don't work in DXP icons don't show up, etc... This confuses our users a lot.

**Comment by matuzalemsteles** [comment]
> @matuzalemsteles unfortunately, last time I checked this doesn't work in DXP - what I mean is that if you copy code from the storybook they usually don't work in DXP icons don't show up, etc... This confuses our users a lot.

Yeah, probably because we're not loading cadmin CSS inside the iframe 😕.

Hey @pat270 if you need help with this, please send me a message.

**Comment by brunofernandezg** [comment]
Comment to force sync. Ignore
