### ISSUE TITLE
Let's review how we write React components with TypeScript

### ISSUE THREAD

**Issue by julien** [liferay/clay#4655]
This is something that we've discussed with @matuzalemsteles on Slack,
but I think it's a good idea to create an issue to have it on our radar.

I propose we stop using React.FC in for all components. The main reasons behind
this idea, can be read in this [issue](https://github.com/facebook/create-react-app/pull/8177), and can be summarized in a few words (quoting the author of the original issue)

> React.FC is unnecessary: it provides next to no benefits and has a few downsides.

I'm also concerned about some "patterns" we use, so I'd like us to review a few things

- Is it really necessary to have [hooks](https://github.com/liferay/clay/blob/2fe162aa670d59206b561b0b4deeba5872ac9b99/packages/clay-core/src/tree-view/useItem.tsx#L225-L227) that "just" make use of `useContext`?
(There might be other occurrences of this in other packages)

- One of our goal is increasing collaboration (from the community and other teams in our organization), and in that sense, making sure there's no complexity in our codebase when it's not needed is important, to make Clay more "attractive"

I know we have other priorities, but we all know that keeping technical debt around isn't
great either, and I think this could be achieved pretty quickly if we're well organized.

**Comment by matuzalemsteles** [comment]
> I propose we stop using React.FC in for all components. The main reasons behind
this idea, can be read in this https://github.com/facebook/create-react-app/pull/8177, and can be summarized in a few words (quoting the author of the original issue)

To me this makes sense, we normally use `React.FunctionComponent` but this has become a problem due to the use of generic types now with JSX.

> Is it really necessary to have [hooks](https://github.com/liferay/clay/blob/2fe162aa670d59206b561b0b4deeba5872ac9b99/packages/clay-core/src/tree-view/useItem.tsx#L225-L227) that "just" make use of useContext?

Well, I don't have a lot of strong opinions about this but it's just a preference to avoid that the components have a direct link with the Context, since the Context can be a Provider and Consumer, I think this way it's explicit that it's read-only ... I've seen some cases like this in DXP and I see some cases in the React community but I don't see a problem with removing it.

> One of our goal is increasing collaboration (from the community and other teams in our organization), and in that sense, making sure there's no complexity in our codebase when it's not needed is important, to make Clay more "attractive"

Yeah, it makes sense. Usually, things about TypeScript we don't have something 100% agreed on all the standards, usually we just agree with some standards and others not very official, but I remember mentioning at times trying to use some TypeScript cheatsheet to adopt and modify or improve if necessary, we could probably involve the other squads to have an agreement between everyone.

- [React+TypeScript Cheatsheets](https://github.com/typescript-cheatsheets/react)

**Comment by julien** [comment]
@matuzalemsteles glad to see we're on the same page. 
Concerning the use of React.FC, this is probably something I can work on in the future with @sergiojimcos.

Concerning the "hook" pattern I mentioned, and your reply 

> Well, I don't have a lot of strong opinions about this but it's just a preference to avoid that the components have a direct link with the Context, since the Context can be a Provider and Consumer, I think this way it's explicit that it's read-only ... I've seen some cases like this in DXP and I see some cases in the React community but I don't see a problem with removing it.

If the context is exported and available "outside" of Clay, then using this patterns to avoid problems doesn't seem like a bad idea, but if the context is only used "internally" by Clay I think it's just adding a layer of indirection and it makes it just a bit more "complex" - to be clear I really think it's not needed.

In any case, I agree that using the React+TypeScript Cheatsheets is our best option to standardize everything.

**Comment by julien** [comment]
Thanks for the feedback @matuzalemsteles; as I said, this might be an interesting task for me to pair on with @sergiojimcos in parallel while working on other tasks. I'll let you know shortly.
