### ISSUE TITLE
@clayui/multi-select: Multi Select doesn't add tag/value after changing the focus

### ISSUE THREAD

**Issue by rebsilva** [liferay/clay#4656]
## What is your question?

Hi guys! I want to ask about a behaviour of the Multi Select component: when we are writing something inside the input and change the focus, shouldn't the text we were typing before transform into a tag (the same behaviour if we pressed enter or a comma in the keyboard)? We have a bug related to that on the Forms team side as you can see [here](https://issues.liferay.com/browse/LPS-147079). Also you can see a video of this behaviour [here](https://drive.google.com/file/d/1XzUdtO4CBsDG2DM-2Gf7IYzhtqND8rie/view?usp=sharing).

I just wanted to know if this is the expected behaviour and if it is, would be possible to change it or not? Thanks in advance!

**Comment by matuzalemsteles** [comment]
Hey @rebsilva, I don't know if I understand correctly the behavior of changing the focus, does the text turn into a label after the focus changes?

The behavior for the text to become a label is when pressing the comma key or pressing enter, this behavior cannot be changed but you can choose whether or not to save this value as a label, for example controlling the component using `onItemsChange` and `items`, in this necessary, you can take care of the validation.

What would be the behavior you are trying to reproduce? I didn't quite understand the ticket but if Lexicon doesn't predict this behavior I think it wouldn't be a bug, if the designer thinks it's a valid behavior it would be interesting to open a request for Lexicon to reevaluate this behavior so that Lexicon can study if this makes sense or is good for UX.

**Comment by rebsilva** [comment]
Sorry, the text was indeed a little confusing, but what I wanted to ask is if when we change the focus from the field after writing and don't press enter or comma, the text should be transformed into a label (this is not happening at the moment, but the team thought it should, that's why there is a bug opened for this).

From what I saw in the documentation you sent me the expected behaviour is that the text will only turn into a label if we press enter or a comma, so our bug isn't really a bug; I will talk with the team about this, thanks for your help!

**Comment by matuzalemsteles** [comment]
@rebsilva Oh, I see, thanks for clarifying!
