### ISSUE TITLE
TreeView: setItems has no effect without onItemsChange

### ISSUE THREAD

**Issue by julien** [liferay/clay#4662]
## Is there an example you can provide via codesandbox.com?

Sure, [here](https://codesandbox.io/s/beautiful-river-w2wqk?file=/src/index.js) you go

## What are the steps to reproduce?

Use `TreeView` and try to set the items to another value at some point

## What is the expected result?

The items should be updated, i.e. the component should be re-rendered

**Comment by matuzalemsteles** [comment]
Hey @julien I was thinking about this after we had a conversation about this behavior, and on further reflection, I think this behavior makes sense for us to keep it as a desired behavior to avoid problems. My reasoning is a little tied to the idea of ​​[controlled](https://reactjs.org/docs/forms.html#controlled-components) versus an [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html#gatsby-focus-wrapper) component, very much related to React's default behavior for `input` for example.

When you want to control the component state to handle or know more updates, having only the `items` declared can go against the source of truth, firstly because the TreeView in some scenarios can update the `items` state if the ` onItemsChange` is not passed we will have information conflicts, as the state is coming from the TreeView's parent component it will lose the changes that the component is making.

This case is similar to the behavior of having the component controlled, that is, if you want to control the state of an `input` it is mandatory to pass `value` and `onChange`, if you only pass the `value` React throws an error stating that the component is changing to the uncontrolled and controlled component, in that case, it recommends using `defaultValue` but if you update the state it will throw again an error saying `defaultValue` cannot be updated because the component is not acting as controlled, this is because there will be problems with the synchronization of the state of what is being typed and what is being done internally in the component and without a single source of truth.

I think this is a way to keep this inconsistency of behavior that can eventually exist if `onItemsChange` and `items` are not declared together when you also change the state of items, in the scenario where you don't, items will operate as initial state and being internally controlled. What do you think?

**Comment by julien** [comment]
Hey @matuzalemsteles, 
I agree with you about controller & uncontrolled components and understand that in this case, it's not really a problem . I opened the issue to discuss about it, to see if we could do something and also because @victorg1991 wanted more information about this. If it's clear that the TreeView works this way, then I don't think it's really a "blocker" ... in any case, I'll still look to see if we can do something about it.

**Comment by julien** [comment]
@matuzalemsteles I'm not sure if [this](https://github.com/liferay/clay/pull/4665), is a valid fix, but I thought I'd send regardless to see what you think (. Another option we've discussed with @victorg1991 is doing something along these lines

```jsx
const [items, setItems] = React.useState([
	{
		children: [{name: 'Blogs'}, {name: 'Documents and Media'}],
		name: 'Liferay Drive',
	},
	// More stuff...
]);

// Later...

<TreeView onItemsChange={setItems}>
	{(item) => (
		<TreeView.Item>
			<TreeView.ItemStack>
				<Icon symbol="folder" />
				{item.name}
			</TreeView.ItemStack>
			<TreeView.Group items={item.children}>
				{(item) => (
					<TreeView.Item>{item.name}</TreeView.Item>
				)}
			</TreeView.Group>
		</TreeView.Item>
	)}
</TreeView>
```

Let me know what you think when you can.

**Comment by matuzalemsteles** [comment]
Hey @julien yeah, I think we could leave this behavior as the default, and add instructions about it in the document, maybe in some specific section outside the TreeView document because this behavior is totally tied to our `useInternalState` hook and it replicates for all our components that use it. Maybe create a new document to talk about this specifically and in the components that use it, we add in each document referring to the component the link to that document of the behavior.

It makes sense if you update `items`, pass `items`, and `onItemsChange` together instead of just passing `items`.

**Comment by julien** [comment]
@matuzalemsteles thanks for the feedback ... I just have a doubt, are you saying we should discard https://github.com/liferay/clay/pull/4665 and just use what I posted in [my previous comment](https://github.com/liferay/clay/issues/4662#issuecomment-1038939483)?

**Comment by matuzalemsteles** [comment]
@julien yes, I think what would come out of here would be the documentation part to make this clearer.

**Comment by julien** [comment]
@matuzalemsteles perfect, seems good to me, I'll close #4665 :)

**Comment by julien** [comment]
:facepalm: I guess I could have closed this issue as well :rofl:

**Comment by julien** [comment]
Hey @matu

**Comment by matuzalemsteles** [comment]
@julien yeah this happens for all our components that use `useInternalState` with the intention of changing the state ownership to internal or external, well I don't know if it makes sense to do it that way because it can cause more problems than good, maybe we can add warning when this is done so people understand the behavior, I imagine people must be used to it because it's the same form state control behavior in React, we can throw warning just like React does.

> Additionally, could you please explain why https://github.com/liferay/clay/pull/4665 wasn't a valid fix.

The problem with allowing the developer to pass just the value instead of passing the callback together is that it creates an inconsistency of where the state is, the TreeView also handles the state of `items`, `expanded`, `selected`, if pass only the `expandedKeys`, `selectedKeys` and `items` for example, if the user interacts with the TreeView, either by selecting an item, expanding, moving... this will not be reflected in the UI because the TreeView will be manipulating the state that is not the source of truth, in which case he doesn't know who to ask for an update.

For example, if you want to keep an `expandedKeys` controlled, i.e. passing an initial value and updating on its own as well, this breaks the component because they both want to control the state, this is just a matter of [single source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth). I would also add here the same reason I commented in the comment https://github.com/liferay/clay/issues/4662#issuecomment-1036949639

Let me know if anything is unclear!

**Comment by julien** [comment]
Thanks @matuzalemsteles I think that this sentence resumes it well.

> this breaks the component because they both want to control the state

I was trying to explain this to @beltranrengifo, @claraizquierdo and also previously to @victorg1991; which is why I'm mentioning them here just in case they have more questions

**Comment by julien** [comment]
I think I'll add some warnings in case `items` is passed without `onItemsChanged`, and do something similar for the `expandeKeys` and `onExpandedChange`

**Comment by victorg1991** [comment]
Can we have something like  `initialItems` ? and then `items/onItemsChanged` this way we can differentiate when the items are supposed to be static and when they may change 🤔

**Comment by julien** [comment]
> Can we have something like initialItems ?

I personally don't like prefixing props with "initial" but that's just my own preference

**Comment by julien** [comment]
That would introduce a breaking change since this component is already published and used, sorry @victorg1991 ;)

**Comment by julien** [comment]
Well to be fair @victorg1991 since TreeView is only used in a few places we might be still on time to change that. What do you think @matuzalemsteles?

**Comment by matuzalemsteles** [comment]
It makes sense to me, I agree that `default*` is closer to the React standard and I think it would be a nice addition here.

**Comment by beltranrengifo** [comment]
> Thanks @matuzalemsteles I think that this sentence resumes it well.
> 
> > this breaks the component because they both want to control the state
> 
> I was trying to explain this to @beltranrengifo, @claraizquierdo and also previously to @victorg1991; which is why I'm mentioning them here just in case they have more questions

Thank you all for the inputs and explanations.
It seemed to me kind of strange and unintuitive the use of this props for the callbacks. The most common/expected behaviour for a component is to react to props changes. I think it could be a good idea to throw a warn and document well the usage and the why of this props.

**Comment by matuzalemsteles** [comment]
> It seemed to me kind of strange and unintuitive the use of this props for the callbacks. The most common/expected behaviour for a component is to react to props changes. I think it could be a good idea to throw a warn and document well the usage and the why of this props.

Well, partially this is quite common where you want to control the component state and not a configuration prop, as I said this is similar to the default [controlled](https://reactjs.org/docs/forms.html#controlled-components) and [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html#gatsby-focus-wrapper) component behavior for inputs when the intent here becomes different from configuring a component.

For example, if you pass a value only to `items` props, the property will behave like a `defaultItems` if you update the state again of items the intent has changed so we can't use that information because the component is acting like a [uncontrolled component](https://reactjs.org/docs/uncontrolled-components.html#gatsby-focus-wrapper) because both want to update state and the user is interacting with the component, if he moves, deletes, renames, expands, selects... the component will update internally when you change the prop intent it starts to become a [controlled component](https://reactjs.org/docs/forms.html#controlled-components), in this case, we always use the strategy of keeping an `on*`  props as well as the `value` and `onChange` for the input, we follow the same line of reasoning here.
