### ISSUE TITLE
Date picker in web content doesn't have correct styles

### ISSUE THREAD

**Issue by DiegoHu97** [liferay/clay#4715]
## Problem's describe
The date picker in Web Content does not have the correct styles:
<img width="222" alt="Screenshot 2022-03-03 at 15 07 53" src="https://user-images.githubusercontent.com/91208451/156580743-1db61e0e-5267-4553-8a18-dd6e015e0c0d.png">
## What are the steps to reproduce?
1. Create a Web content
2. Open the "schedule" section in the sidebar
3. Click in the date field
## What is the expected result? 
![Screenshot 2022-03-03 at 15 01 13](https://user-images.githubusercontent.com/91208451/156579656-16942aca-d85f-4d70-8a9a-25b9653998e4.png)
This is how looks like in 7.3 version (expected result), which has the following CSS:
_.popover-body, .popover-content {
      border-bottom-right-radius: calc(0.25rem - 1px);
      border-bottom-left-radius: calc(0.25rem - 1px);
      color: #6b6c7e;
      padding: 0.75rem 1rem;
}_

## Possible solution
A possible solution could be to add a new class **.popover-content** with the right padding (like in section 3) as in 7.4 version it does not have **.popover-content** styles for the date picker.
## Environment
Liferay 7.4

**Comment by julien** [comment]
Hey @DiegoHu97 thanks for reporting this. 
I'll ping @pat270 and @edalgrin just in case they are aware of anything that's changed in Web Content lately.

**Comment by pat270** [comment]
@DiegoHu97 this is the [Alloy UI Datepicker](https://alloyui.com/examples/datepicker/index.html) and `popover-content` is a class from Bootstrap 3. The padding is probably gone from `popover-content` because 7.4 removed the Bootstrap 3 compatibility layer.

The correct fix is to convert the Date Picker in Web Content to use the one provided by Clay in my opinion. I'm guessing that is too much work. The padding should be added in the Web Content module or in styled theme.

**Comment by DiegoHu97** [comment]
I have sent this pull: https://github.com/liferay-frontend/liferay-portal/pull/1987
