### ISSUE TITLE
@clayui/drop-down Drop-down is not showing all items

### ISSUE THREAD

**Issue by leticia-maciel** [liferay/clay#4720]
Hi guys, we're using **drop-down with items** on Forms component, but it was noticed that when it's near the bottom page, the items are being cut. As you can see on the image below, there are more dates fields after Date 6, but they are not able to be selected.

![image](https://user-images.githubusercontent.com/77082869/157100286-39764111-9bd9-4688-8598-c91387f0deba.png)

We think it occurs because the max-height is set to 500px for dropdown-menu class so the overflow attribute will not work for our case. It was also noticed that there's a media-query for max-width: 991.98px in which the max-height changes and the overflow works showing all the items. 

![image](https://user-images.githubusercontent.com/77082869/157101636-243150a3-72aa-428e-90a0-cdbaf1b53b86.png)

With all that in mind, my question is if this is something we have to adapt on our side or it's possible to make the dropdown height more responsible for cases like this. 

Thanks in advance :smile:

**Comment by pat270** [comment]
I thought `@clayui/dropdown` had a feature where it would reposition to fit in the window if it overflowed. I might be getting it confused with other dropdowns in Portal. We can add more height utilities (only auto is available right now) if it is useful.

**Comment by matuzalemsteles** [comment]
Hey @pat270 in fact, the DropDown component does exactly that if the element overflowed, probably in this case here it is breaking due to the container that has a scroll or it could be some edge case that I don't know about but that was supposed to happen. @leticia-maciel is this already in the DXP master? how can I reproduce this use case?

**Comment by miltonmc** [comment]
I think the problem here is because the sidebar has it own scroll, so sometimes the container  has space enough to render the dropdown list but not into the viewport. Ideally the component should check if it fits into the viewport. Something like this:
- [example](https://www.javascripttutorial.net/sample/dom/event/visible-viewport/index.html)
- [tutorial](https://www.javascripttutorial.net/dom/css/check-if-an-element-is-visible-in-the-viewport/#:~:text=Use%20the%20getBoundingClientRect()%20method%20to%20get%20the%20size%20of,in%20the%20viewport%20or%20not.)

**Comment by matuzalemsteles** [comment]
Hey @miltonmc yeah, the component does just that but with a more complex implementation using `dom-align` which handles the repositioning of the Menu when it overflows outside the viewport.

I'll try to reproduce this in an example outside of DXP to understand what's going on.

**Comment by rebsilva** [comment]
If you need more info about the matter @matuzalemsteles this is the bug we opened on our side, hope this can be helpful to you: https://issues.liferay.com/browse/LPS-146714

**Comment by matuzalemsteles** [comment]
Well, I investigated this more today, and apparently, this is because aligned is not considering the viewport, for example, it considers the entire content of the screen, in this case, it only adjusts when your scroll is at the end of the page, in which case it will adjust.

Well for some use cases this makes sense but as this is a case where having two containers can be a problem, what we can do here is add an API to consider only the viewport, this API is already available in `dom-align ` so let's add an API to set this property for DropDown, I'll probably add it for other components that use it too, this is similar to what we have with `autoBestAlign`.

I'll convert this issue to a bug.
