### ISSUE TITLE
Avoid naming properties with the same name of DOM Attributes

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#4783]
## What is your proposal?

This discussion cames from https://github.com/liferay/clay/pull/4779 where we have a property called `title` and we needed to omit the default `title` DOM attr and consider it as a React Prop using `Omit<...`.

**The idea here is to add a guideline on Clay components for avoiding naming properties with names like DOM attrs.**

## Why would adopting this proposal be beneficial?

More consistency and if users would use a desired DOM attr, they will be able to do it

## What are the alternatives to this proposal?

Add an eslint rule? It should be investigated

**Comment by sergiojimcos** [comment]
Hey @matuzalemsteles! I'm going to start investigating this issue

**Comment by sergiojimcos** [comment]
Hey @matuzalemsteles! I've made a research about the proposal made by @diegonvs. I think that the most useful way to prevent using React props naming the same way as DOM attributes is using an `eslint` rule called:[ `react/forbid-component-props`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md). This rule only applies to Components and not DOM nodes. In order to select which properties you want to avoid, you have to costumize this rule using a list like in this example:

```
'react/forbid-component-props': [
	'error', {
		forbid: ['title'],
	},
],
```

In the array of `forbid` you have to indicate all the props that you want to avoid. Besides, you can also customize the array specifying the property name, an optional custom message, and a component whitelist:

```
{
  "propName": "someProp",
  "allowedFor": [SomeComponent, AnotherComponent],
  "message": "Avoid using someProp"
}
```
However, there is not any `eslint` rule that can avoid props naming all the DOM attributes without specified them in the array

**Comment by matuzalemsteles** [comment]
Cool, this seems like a good way to help avoid this, as we talked in slack I think a good thing now is to try to understand what the alternatives would be for existing components, how this will affect them, and how we can migrate them, so the doc do RFC can help us to understand more deeply what this can cause side effect and how we can avoid it.
