### ISSUE TITLE
Incorrect styles for disabled item in the management toolbar

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#4792]
I've opened this here since it seems that the css that is causing this behaviour comes from clay

In the portal, when selecting several items in a search container, some of the options may be disabled. Currently the quickaction items doesn't show this state correctly:

Actual behaviour:
![Screenshot 2022-04-05 at 10 56 57](https://user-images.githubusercontent.com/11654230/161731383-b205cde0-6fba-4e0c-be4a-236ff73508a4.png)

Expected behaviour (confirmed with @drakonux):
![Screenshot 2022-04-05 at 10 57 39](https://user-images.githubusercontent.com/11654230/161731446-47df326b-9cd6-4741-8009-8b9c2727eb62.png)

This seems to be the offending css:

![Screenshot 2022-04-05 at 12 10 18](https://user-images.githubusercontent.com/11654230/161731595-d704245f-1103-4a0b-90aa-6a94f6159f6f.png)

**Comment by matuzalemsteles** [comment]
Hey @victorg1991 maybe this is not something related to CSS but the logic of the Management Toolbar which is adding the `disabled` property to the button. How can I reproduce this? I tested it on Documents and Media but I couldn't get this scenario.

cc @carloslancha @tinycarol I'm not sure if it's related to the recent changes to the Management Toolbar, the last time I saw it still hadn't been replaced by the new implementation.

**Comment by pat270** [comment]
Yeah it has always been `opacity: 1`. We used `color: #a7a9bc` to style the disabled state.

**Comment by tinycarol** [comment]
Hey @matuzalemsteles! I managed to replicate this on Documents and Media by adding a folder and selecting it. 

[We are using](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/ActionControls.js#L84-L85) a `ClayButton` with unstyled displayType and disabled mode, which applies the styles `color: #6b6c7e; opacity: 1;`. If I remove the `btn-unstyled` class, opacity changes to 0.4, which results in this:

<img width="286" alt="imagen" src="https://user-images.githubusercontent.com/6642927/161925406-987456c4-b400-4b17-a512-f27a5a6ddb93.png">

This fixes the disabled state, but it doesn't work for us because it sets the font-size to 1rem (16px) and [in the last MT changes there's a text label in the button with a smaller font size (14px)](https://www.figma.com/file/TwkWwYdduQB7YDkCyo862h/lexi-1151-management-toolbar?node-id=315%3A60672). You can see this by enabling a feature flag [by downloading this file](https://issues.liferay.com/secure/attachment/436739/com.liferay.frontend.taglib.clay.internal.configuration.FFManagementToolbarConfiguration.config) in your `bundles/osgi/configs` folder and relaunching the portal.

**Comment by victorg1991** [comment]
> This fixes the disabled state, but it doesn't work for us because it sets the font-size to 1rem (16px) and [in the last MT changes there's a text label in the button with a smaller font size (14px)](https://www.figma.com/file/TwkWwYdduQB7YDkCyo862h/lexi-1151-management-toolbar?node-id=315%3A60672). You can see this by enabling a feature flag [by downloading this file](https://issues.liferay.com/secure/attachment/436739/com.liferay.frontend.taglib.clay.internal.configuration.FFManagementToolbarConfiguration.config) in your bundles/osgi/configs folder and relaunching the portal.

Got it, has this change introduced recently? This seems to be the cause of the bug. Can we use some of the font size clases and remove the btn-unstyled in that case? @tinycarol If so, I can create an LPS to fix this directly into the portal

**Comment by pat270** [comment]
I just checked and I made a mistake with the key names in the disabled state for management-bar-primary when I was converting it to the new variable pattern. It should work without changing any of your markup (I hope). You can disregard the markup should be thing.

**Comment by matuzalemsteles** [comment]
Oh thanks guys for the investigation I also didn't understand the relationship with `disabled`, but it's still a bit strange that we have `disabled` property to the element and it should have `opacity: 1` apparently this is the desired behavior for this case? I can't find this information in the documentation, it seems strange to say that it can be clicked but it is not possible.

**Comment by drakonux** [comment]
Just for the record @matuzalemsteles an element can be `disabled `with `opacity: 1` and, using a dull color, look like that has less opacity than 1. 

Besides talking about accessible buttons, as far as I know (cc\ @marcoscv-work ) we could be using `aria-disabled` instead of `disabled `because `aria-disabled` allows disabled buttons to be focused, but we should review in deep the case. Thus it is more usable than disabled because we can set a button tooltip explaining why the UI element that has the focus is disabled and how to enable it. But I think it doesn't prevent the click. 

In my opinion, Lexicon should review the disabling actions pattern in the management toolbar.

**Comment by matuzalemsteles** [comment]
@drakonux Yeah I see, I was just confused because the opacity was 1 and I hadn't created the color relationship to be used to set a different color for this, so it's ok. But it would be good to keep the same pattern that we have for the other components in the case of the Button for example using opacity instead of color, I think it doesn't affect accessibility I was talking more about this because I wasn't seeing the color issue in action on here.

**Comment by pat270** [comment]
@drakonux I'm commenting on disabled buttons in general. Should they be focusable and what does focusable mean? Disabled inputs and `<button>` aren't focusable when navigating the page using the TAB key. This is the default behavior implemented by the browsers. Should we be overwriting the default functionality?

When using a screen reader, I'm using Voice Over on mac, they are focusable when navigating the page (CTRL + OPTION + ARROW KEY). Isn't this how it should be?

**Comment by drakonux** [comment]
> Should they be focusable and what does focusable mean?

My comment intended to point out that using `disable `makes an element accessible but "sometimes" using it gives a bad user experience for impaired users and Lexicon should review that pattern.

Because they can miss that the button ever exists, it is often caused by a lousy UI design using a disabled element -> Why the machine is providing an element that can't be used, or at least why it doesn't explain how to enable it?

IMO a focusable element means that the element can receive the focus. Thus, disabled elements can't receive the focus, BUT they should be reachable by a screen reader application, as you explained below.

> Should we be overwriting the default functionality?
Definitely not, I just wanted to start a discussion about its use cc\ @marcoscv-work 

> When using a screen reader, I'm using Voice Over on mac, they are focusable when navigating the page (CTRL + OPTION + ARROW KEY). Isn't this how it should be?

You are right, that's perfect. 

cc\ @liferay-lexicon
