### ISSUE TITLE
Adjust button size for TreeView

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4861]
This is a request coming from some document requirements https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/1970078399/LEXI-1257+Clarify+behavior+for+DXP+Trees, the Button small component has a smaller size when used in the TreeView.

**Comment by pat270** [comment]
There are some issues with content breaking to newline when the treeview container is small. We have no guidelines on how to handle it. Should everything be on one line? Should it break to new line?

Not related to this issue, but one thing I'd like to change is the quick actions on hover overlaying the content instead of pushing it over, similar to what we are doing in tables https://clayui.com/docs/components/table/markup.html.

**Comment by matuzalemsteles** [comment]
> There are some issues with content breaking to newline when the treeview container is small. We have no guidelines on how to handle it. Should everything be on one line? Should it break to new line?

Well, that's a good question I think the @liferay-lexicon team can help us here.

> Not related to this issue, but one thing I'd like to change is the quick actions on hover overlaying the content instead of pushing it over, similar to what we are doing in tables

Makes sense to me!

**Comment by matuzalemsteles** [comment]
Hey @pat270 it seems that this button also only appears when the mouse hovers over the node or the node is focused, maybe for that, we can create an extra class just to handle this? we can also let the DXP teams handle this because this is not at the core of Lexicon for now.

**Comment by pat270** [comment]
@matuzalemsteles sure we can create a utility for it, that would make it more composable.

**Comment by emiliano-cicero** [comment]
Hey guys, I just want to add my thought on this which is similar to what @matuzalemsteles has written in his last post. The button shouldn't be covered by Lexicon/Clay. As part of the System, we should only provide the component and its extension points. 
For this specific case I'd say we provide the simple Tree View, and then a side extension point where teams can add what they need (Buttons, Badges, Actions, etc) and is not for us to define. 

**Here's an example:** 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/27729173/169273802-870dced4-2b08-4c4f-b629-fd84ab7947d3.png">

As you can see I haven't even added a margin because badge components might need to be closer to the text, that margin should also come from the teams.

**Comment by pat270** [comment]
@emiliano-cicero are you ok if we add a button size for treeview? It will be scoped specifically for treeview, we don't need to add a new button definition to Lexicon.
