### ISSUE TITLE
[Tree View] Incorrect indeterminate behavior

### ISSUE THREAD

**Issue by ugeortiz** [liferay/clay#4897]
## What are the steps to reproduce?
1. By clicking a child node of a tree view, the parent checkbox becomes to `indeterminate `state. 
2. Then, by clicking the parent it selects all the child items instead of deselecting them. 

## Current result 
The `indeterminate` state enables all child items by clicking on it. I enclose a video showing the comparison between two different checkbox components. 

https://user-images.githubusercontent.com/98747059/171824847-0912a1a3-0001-43bd-bdf8-a86825870f70.mp4

## What is the expected result?
The `indeterminate` state should deselect the child items. 
In order to create consistency between other checkbox components in DXP, we should ensure that the behavior is the same in all of them. The proposed pattern is following the standard behavior used for many other sites and is known by a lot of users. 
I enclose a little video showing the expected behavior of a Tree View prototype. 

https://user-images.githubusercontent.com/98747059/171824667-313b38fa-0049-424a-ab7c-2d1a401e3610.mov

Thanks in advance,

cc @liferay-lexicon @susanavr

**Comment by matuzalemsteles** [comment]
Hmm interesting, well this seems pretty counter-intuitive for me to click in an intermediate state not to select all items, if I'm selecting some child items of my node and clicking on the parent, I would say that I don't want to deselect all items but select all the items, from what I've seen this seems very interpretive and depends on each scenario where it is used, some references such as the documentation of the intermediate state or the native state of the checkbox, clicking will make it select instead of deselecting.

- https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate
- https://css-tricks.com/indeterminate-checkboxes/

I like to think that the best behavior we can follow is to see how operating systems do is where the user is most familiar. I'm on Mac, so checkbox selection behavior in TreeView also follows the same behavior.

https://user-images.githubusercontent.com/13750819/171883273-8befc6d3-b88d-49c5-bd8f-10c7f0bd045d.mp4

It also seems to be a default behavior for years on Windows, this sentence is quite interesting for this behavior: "symbolically meaning partially checked, or as indicators that a user has acted on a control"

- https://ux.stackexchange.com/questions/44646/is-the-indeterminate-checkbox-state-a-microsoft-ui-pattern-only

We can see this behavior in other places as well, I think the positive point here would be to maintain consistency but it would be good to understand if this is the behavior and we are going with the user's intuition before moving in a perhaps wrong direction. If we are just thinking about consistency and against the user's intuition, in my view this is not a bug and we should fix it everywhere in the DXP that has the three checkbox states.

**Comment by ugeortiz** [comment]
Thanks, @matuzalemsteles for your reply. I think you have good points there :) 

Seen from a usability point of view we have to take into account different factors: 

**Affordance**
Not all users need to know the behavior that exists in operating systems, and from the point of view of new users a "-" sign in an `indeterminate` state does not show the action that will follow. 

**Mental patterns** 
I agree with you that there are several examples of this behavior where the indeterminate state selects the children. But there are also many other examples where it happens the opposite. 

See Gmail

https://user-images.githubusercontent.com/98747059/172142914-594d72c3-0e42-4e97-9b84-d93f0a92532e.mov

See Dropbox

https://user-images.githubusercontent.com/98747059/172142869-5ca67fc0-a7ef-4ffd-9e5d-bb8f2f020bbb.mov

**Consistency with the system** 
IF we respect the heuristics of the rest of the site, ideally this behavior should respond in the same way. One of the most important heuristics is precisely consistency. 

**Efficiency of use and flexibility** 
Any time the user needs to deselect a large number of parents in an `indeterminate` state, it will take two clicks to do so.

Example

https://user-images.githubusercontent.com/98747059/172143827-4f5064e6-982a-45f2-ba56-9fc4e9da5288.mov

I agree with you that this is not a bug. It is just a design decision. So we need to have into account: 

- We are seeking consistency 
- There is no a "real" source of truth 
- Users are used to other components on DXP working as the opposite. 

From the UX perspective, everything points out that we should change it.

Thanks!

**Comment by matuzalemsteles** [comment]
@ugeortiz thanks for bringing more insights and use cases that help us make that decision. I fully agree that this should be consistent across all components, I think I'm fine with that, I also think it will help in the future in case anyone asks about this again.
