### ISSUE TITLE
ClayMultiSelect doesn't have correct styles when it is embeded in a Form Group with the small property

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#4911]
ClayMultiSelect doesn't have correct styles when it is embeded in a Form Group with the small property. A normal text input have 32px height but the multiselect have like ~40

## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/brave-wave-2c32c3?file=/src/index.js

## What is the expected result?

I believe the size should be similar to a text input with the small property

**Comment by pat270** [comment]
@liferay-lexicon Do we have specs on MultiSelect in small size?

**Comment by emiliano-cicero** [comment]
Hey guys, sorry something weird is happening because I'm not getting notifications via email from Github. 

Anyway, yes: it would be possible to have a smaller version of the Multiselect, I'm adding a list of the components to build it.

### Multiselect Small - Components
**Input Small** - the height should be 32px but allowed to grow the same way as the Multiselect Regular
**Label Regular** - since this label will allow interactions, it's recommended to use the Regular size instead of the small, also the small label doesn't allow to include of lower-case text and since this case is for CSS classes, it's better to use the Regular size to represent the classes better.
**Clear button** - Lexicon should evaluate whether include a new small button fo 24px in the system, for this case this button should be an exception of 24px and have the same behavior as the Regular version of the Multiselect.

I prepared an image to represent this visually and also included some specs:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/27729173/173612481-a905dcab-1635-4cf2-aebd-f5c0173df66b.png">

**Comment by emiliano-cicero** [comment]
Ignore this message: just mentioning @liferay-lexicon to see if we can get notifications.
