### ISSUE TITLE
Spritemap cdn link in documentation links to blank spritemap

### ISSUE THREAD

**Issue by toadslop** [liferay/clay#5021]
On this [page](https://clayui.com/docs/get-started/how-to-use-clay.html) in the documentation, there is a link to the spritemap cdn.

```
// You will use this to move to some components
// that need Clay icons, you can host your own
// set of icons in your application, we are using
// CDN to make it easier.
const spritemap =
  "https://cdn.jsdelivr.net/npm/@clayui/css/lib/images/icons/icons.svg";
```

This spritemap is blank.

Check this code sandbox for evidence: https://codesandbox.io/s/quick-start-clay-forked-s5wxie?file=/src/index.js

**Comment by matuzalemsteles** [comment]
Hey @toadslop actually the spritemap is rendered blank when you access it from the browser but the content is still there, that's because the spritemap is a collection of svgs and the browser doesn't render it as just a svg from a single file.

I'm going to update the codesandbox to use the spritemap in place because the problem that happens if you try to use this spritemap is that the browser won't allow it because it's an unsafe request.

**Comment by matuzalemsteles** [comment]
I fixed this, added the latest `icons.svg` file in the public folder so we were able to add the spritemap in the components, for example:

```jsx
<ClayIcon symbol="add-cell" spritemap="icons.svg" />
```

**Comment by pat270** [comment]
> the browser won't allow it because it's an unsafe request

I want to expand a bit on this. It's due to [Cross-origin resource sharing (CORS)](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). It needs to be enabled on your web server or set on the cdn, which as a third party user are unable to on codesandbox or jsdelivr.

You can get the example to work by using an ajax request and pasting the sprite directly on the page. I believe it defeats the purpose of having an svg sprite because ajax requests aren't cached by the browser. I could be wrong though.


```
import React, { useState } from "react";
import ReactDOM from "react-dom";
import ClayIcon from "@clayui/icon";

// Imports the @clayui/css package CSS
import "@clayui/css/lib/css/atlas.css";

// You will use this to move to some components
// that need Clay icons, you can host your own
// set of icons in your application, we are using
// CDN to make it easier.
// const spritemap =
//   "https://cdn.jsdelivr.net/npm/@clayui/css/lib/images/icons/icons.svg";
var ajax = new XMLHttpRequest();
ajax.open("GET", "https://cdn.jsdelivr.net/npm/@clayui/css/lib/images/icons/icons.svg", true);
ajax.send();
ajax.onload = function(e) {
  e.ondata = (chunk) => {
    console.log(chunk);
  }
  var div = document.createElement("div");
  div.innerHTML = ajax.responseText;
  document.body.insertBefore(div, document.body.childNodes[0]);
}

function App() {
  return (
    <div className="container">
      <div className="sheet">
        <div className="sheet-header">
          <h2 className="sheet-title">Clay</h2>
          <div className="sheet-text">Experiment Clay components!</div>
        </div>
        <div className="sheet-section">{/** Add components here */}</div>
        <ClayIcon
          style={{ border: "1px solid black", backgroundColor: "pink" }}
          symbol="heart"
          spritemap=""
        />
      </div>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by matuzalemsteles** [comment]
Hey @pat270 I think that both `fetch` and `XMLHttpRequest` follow the cross-origin policy, you can make the request to this cdn endpoint using both, the problem is that who makes the request in this scenario is the browser itself with `<use xlinkHref ={} />` which makes the request unsafe as it is not a safe sandbox like adding any URL in the `iframe`.

**Comment by toadslop** [comment]
Thanks for all the suggestions guys. Unfortunately, these don't solve my problem. When I load the file, I don't run into any CORS issues -- the SVG spritemap loads fine. It's just that all the SVGs are blank. To illustrate this, I downloaded the spritemap and ran it from my PC and I have the same result -- all of the icons are blank.

**Comment by toadslop** [comment]
FYI, I downloaded the spritemap from here: https://github.com/liferay/clay/blob/master/clayui.com/static/images/icons/icons.svg

**Comment by toadslop** [comment]
![スクリーンショット 2022-08-06 10 36 26](https://user-images.githubusercontent.com/31160338/183228557-0be1c00b-df93-43bf-a9f4-590ad12de09c.png)

**Comment by toadslop** [comment]
I think I may have found the issue: the underlying icon component acquires the svg using the deprecated xlink:href tag (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href). I believe it may be that my browser no longer supports this tag. When I downloaded the sourcecode of the icon component and replaced xlink:href with simply href, the component worked.

**Comment by matuzalemsteles** [comment]
@toadslop yeah, that's exactly what I was trying to say, sorry if this wasn't clear, the cross origin problem happens when the request is made by the `xlink:href` attribute this won't happen with fetch... and the browser too doesn't render this symbol collection format that's why I was saying that the content is there because that's not the purpose of spritemaps, we get the icon using markup:

```html
<svg
  class="lexicon-icon"
  role="presentation"
>
  <use xlink:href="icons.svg#symbol_name" />
</svg>
```

If you want to use the icons separately, you can find them in the `@clayui/css` package
