### ISSUE TITLE
Add Select-Only Combobox Component

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#5181]
## What is your proposal?

Clay should provide a version of the Drop Down component that meets the accessibility requirements of a [Select-Only Combobox](https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html). 

It would be best if this was incorporated into the current drop down as a configuration, since it is very similar to the existing dropdown. When someone needs to use a select-only combobox they are likely to first look to the drop down component.  

## Why would adopting this proposal be beneficial?

Currently, we have two Clay components that are similar to this. A Drop Down and a Select. The dropdown allows for additional markup in the trigger and the items menu, but it does not have an accessible way to indicate the selected item. A Select has the opposite problem. It is able to indicate the selected item, but does not allow for custom markup.

A select-only combo box provides the ability to indicate a selected item and include custom markup in the trigger and the items. This is necessary for many components that are currently implemented in Liferay. This component would need to be flexible enough to handle the following types of uses.

![Screen Shot 2022-11-07 at 10 26 57 AM](https://user-images.githubusercontent.com/1609196/200241986-a31f1bc5-0caa-4b7d-b521-6f85e71e852b.png)
![Screen Shot 2022-11-07 at 10 27 09 AM](https://user-images.githubusercontent.com/1609196/200241992-8a316e01-0d83-4b96-932d-fdcdb97b7c5f.png)
![Screen Shot 2022-11-07 at 10 26 44 AM](https://user-images.githubusercontent.com/1609196/200242001-6b02e1a1-ba1e-4eca-bb55-a5441d00c5dd.png)

## What are the alternatives to this proposal?

The alternative to this, is to use the drop down component and include an aria-label with the form `{label}: {currentValue}`. This communicates more of the information we need, but it is not ideal.

**Comment by matuzalemsteles** [comment]
Hey @ethib137 I think this is a good proposal but I think this should first go to lexicon @drakonux @emiliano-cicero before implementing something related to this in Clay, also not sure but i think this should be a component instead of being a configuration, I think this is more of a Select component and if I'm not mistaken we have other custom select use cases in DXP that the Lexicon team was already eyeing, so this could be other use cases for the DXP Select component.

Well in theory developers can implement this behavior using DropDown but they would only have to define the necessary `roles` and add the logic of selected to the trigger, the big problem here is that I see that these cases above are all different visually, for example it doesn't have a trigger pattern or menu items for example.

```jsx
const [selected, setSelected] = useState('');

<ClayDropDown trigger={<Trigger selected={selected} />}>
  <ClayDropDown.ItemList role="listbox" items={['one', 'two', 'three', 'four']}>
    {(item) => (
      <ClayDropDown.Item key={item} roleItem="option">{item}</ClayDropDown.Item>
    )}
  </ClayDropDown.ItemList>
</ClayDropDown>
```

This example above would be an example of that, I don't see any other way now how we could add more features because visually and also behaviorally they are quite different, so anyway the developer would still have to configure something. Accessibility behaviors are very similar to DropDown so it would not be "necessary to implement anything else", of course DropDown interactions today still lack some use cases to be implemented, we have an issue to review this.

**Comment by pat270** [comment]
I agree this should be a select component, but shouldn't use html `select`, `optgroup`, `option` markup. Those are notoriously hard to style. I briefly experimented trying to make a HTML/CSS only demo, similar to custom checkboxes, but text and other html markup is invalid inside `select`.

**Comment by matuzalemsteles** [comment]
Yeah, I also think that we shouldn't use native select because we can't achieve the level of customization that would be necessary to support all use cases. This could also become a Combobox/Picker component anyway with resources more focused on that.

The point for me here is that we don't have a very clear standard for trying to provide OOTB features, for example the trigger won't be an input for every use case, the menu might be different. For example there is select in Forms that the input is not editable and uses the DropDown Menu to list the options and with a search inside the Menu.

**Comment by ethib137** [comment]
Fantastic points! Thanks for the insight. I had forgotten about the additional work that was done considering other "Select" like components: https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1908867695/IFI-2702+Custom+Select+and+themability

I'll start a discussion around how we can move forward with this in our channel on Slack. We can probably close this for now or table it, depending on what workflow you would normally follow.

**Comment by marcoscv-work** [comment]
I think component will be pretty pretty close to dropdown so make more sense for me a variation, and we could re-use all hard work with keys.

I think visually probably will be just some adjustments:
![image](https://user-images.githubusercontent.com/7963804/200593204-b393d1fe-fe8f-47b0-a869-38055c12312d.png)
(I can't ensure this, but I see no reason to stray from this example)

**Comment by marcoscv-work** [comment]
Check icons will be in the opposite side:
https://clayui.com/docs/components/drop-down/markup.html#css-end

**Comment by ethib137** [comment]
I've created a [Design ticket](https://issues.liferay.com/browse/DESIGN-4801) to provide designs for us to implement.
