### ISSUE TITLE
ClayModal: should it have aria-modal="true" attribute?

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5199]
## What is your question?
My question is related to [this bug](https://issues.liferay.com/browse/LPS-167056). After a meeting with @marcoscv we decided to apply the following pattern for Applications Menu modal: https://www.w3.org/WAI/ARIA/apg/example-index/dialog-modal/dialog

Here comes my question, following this pattern:
<img width="500" alt="roles" src="https://user-images.githubusercontent.com/9701095/201892705-1f337fc2-b407-4f95-87ac-5143da305c60.png">

Could the `aria-modal="true"` attribute be added to the Clay Modal?

**Comment by matuzalemsteles** [comment]
Hey @veroglez I think that wouldn't be the problem but maybe we don't need it because we're using the technique of using `aria-hidden` for all other elements that aren't in Modal, so it ends up having the same effect. This was recently added #5188.

**Comment by marcoscv-work** [comment]
Hey @matuzalemsteles Not totally agree about closing this one:

- The way we apply aria-hidden is not totally friendly, we are applying aria-hidding even for scripts
<img width="748" alt="image" src="https://user-images.githubusercontent.com/7963804/203313198-53e9754a-57f3-408d-953a-d9b9757afff9.png">
- It generates a lot of validation errors when a modal is opened
<img width="990" alt="image" src="https://user-images.githubusercontent.com/7963804/203325061-bb50ca31-7249-43dd-b90c-3815cacc6e86.png">


- It is not working fine with JAWS rotor and you can go for some buttons, or list them and see them:
<img width="990" alt="image" src="https://user-images.githubusercontent.com/7963804/203313665-05481f4c-7e40-402b-8ddb-463827d75e5a.png">

- VoiceOver rotor also make random differences.

Since is difficult to test everything in all devices and all screen readers I would prefer to add an standard aria to make it works fine and if there is something is not homogeneous it will depending on the browsers/screen readers implementation of the standards.

The curious thing is that I've tested all of this with clay [Examples](https://clayui.com/docs/components/modal.html) and [Markup](https://clayui.com/docs/components/modal/markup.html) . Since Markup examples have aria-modal.

I'm fine with keeping the aria-hidden pattern but let's implement `aria-modal`. it's just a simple attribute at the `role="dialog"` level and in a close future will save time with non-expected differences difficult to explain and defend with the client

**Comment by matuzalemsteles** [comment]
@marcoscv-work thanks for all the details, hmm this is interesting still escaping the Modal even having `aria-hidden`, maybe it's the focus mechanism that is not keeping the focus locked inside the modal... I see no problem in adding and yes it is something very simple in this case... but I'm still curious why `aria-hidden` is generating so many errors...
