### ISSUE TITLE
The autocomplete dropdown menu of multi select is not always fully visible

### ISSUE THREAD

**Issue by Tim-Cao** [liferay/clay#5250]
## How to reproduce?

1. Navigate to the https://clayui.com/docs/components/multi-select.html
2. Decrease the window size and scroll up to make the Autocomplete selector next to the bottom of window
3. Type content to trigger dropdown menu

**Actual Results**
The dropdown menu is overlay by window.
![image](https://user-images.githubusercontent.com/52661397/207542330-338f6114-012d-4e9b-8c40-472e1a1021e3.png)

## What is your proposal?
When the select field next to the bottom of window, place the dropdown menu above instead of below

## Why would adopting this proposal be beneficial?
This is a bad user experience. The user have to scroll down to see the dropdown menu.

**Comment by matuzalemsteles** [comment]
@Tim-Cao Thanks for the proposal, I think this is valid, another option here would also be to move the scroll if the menu is not visible in the viewport.

**Comment by marcoscv-work** [comment]
Moving scroll is not something we could recommend:

WCAG 2.1: Success Criterion 2.2.2: Pause, Stop, Hide
https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html

More context here:
https://www.w3.org/WAI/WCAG21/Techniques/css/C39#description

So I would go to show the menu on top of the trigger

**Comment by matuzalemsteles** [comment]
Hmm I think I got this wrong, I'm thinking more that when the user is interacting with the menu by pressing tab or via arrow keys it moves the scroll but actually this is already the native behavior 😅. 

https://user-images.githubusercontent.com/13750819/208994627-a61ea420-2a54-41e8-9139-d2a1533cf84b.mov

Well, actually we already have this feature but it needs to be enabled because it depends on each use case in the DXP, you need to enable the `alignmentByViewport` property the MultiSelect doesn't have this property yet but all the other components related to the Menu already exist, I will use this issue to add this property to multi select.

See the example with Autocomplete. Ah ignore the scroll blinks my mouse has a scroll bug 😬

https://user-images.githubusercontent.com/13750819/208996114-73a2cf15-0e1e-40ad-b80b-2b5d64915186.mov
