### ISSUE TITLE
Uses the new Autocomplete component in MultiSelect

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#5266]
The MultiSelect component is getting more accessibility improvements, this starting with the grid pattern for the labels with issue #5194 but we still need to apply the combobox pattern to the input. Before starting work on this issue we first need #5203 to be resolved.

Try to use the new Autocomplete component if possible otherwise we can use the hooks that deal with navigation and positioning and the Overlay component so it will be easier to apply the combobox pattern to the input without having to modify something in the public API for MultiSelect since it has a different composition.

**Comment by marcoscv-work** [comment]
@matuzalemsteles probably we can priorize this issue since there is a DXP issue related:
https://issues.liferay.com/browse/LPS-168537

Personally aria-autocomplete pattern don't like much, it is not announcing there is a list of results to the SR, so probably and like improvements we could add a role="alert/status" with the number of items in the list and how to get to the list

**Comment by matuzalemsteles** [comment]
> Personally aria-autocomplete pattern don't like much, it is not announcing there is a list of results to the SR, so probably and like improvements we could add a [role="alert/status"](https://codepen.io/marcoscv/full/VwdygYM) with the number of items in the list and how to get to the list

Makes sense, I think we can use the LiveAnnouncer I ended up making for Picker #5322

**Comment by matuzalemsteles** [comment]
That depends on #5203 first.
