### ISSUE TITLE
Picker component doesn't allow configuring cadmin in the dropdown

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#5271]
Picker component doesn't allow configuring cadmin in the dropdown, I believe it should be a prop that allows to configure this. Otherwise there is no way to enable cadmin for it

**Comment by matuzalemsteles** [comment]
Hey @victorg1991 just one question do you have access to ClayProvider? as a solution you can configure `cadmin` for all components by defining `cadmin` there, I really want to avoid adding APIs that do this for each component and move the whole implementation to the Provider.

https://clayui.com/docs/components/provider.html#theme

**Comment by victorg1991** [comment]
Didn't know about that, I'll try that out, thanks!!

**Comment by victorg1991** [comment]
Mmm it doesn't seem to work in portal, but It does work in codesandbox, do you know if there are something missing there? @matuzalemsteles  I bumped the dependencies in the portal

**Comment by victorg1991** [comment]
it is weird because it is adding a <div> in the same place you put the Provider, and you normally doesn't want that

**Comment by matuzalemsteles** [comment]
Oh this is weird, what error specifically are you facing? maybe it's because you have to update all DXP dependencies equally in all modules so that everyone has the same version, unfortunately if you only update in the module you will have problems conflicting dependency not exactly the version plus `@clayui/provider` or `@clayui/portal` using different contexts and since context in React is reference based it breaks.

The PR of the Release should go in today but it's still in the CI, I think it needs to do a test that needed to be updated https://github.com/liferay-frontend/liferay-portal/pull/2919 🤞, in case you want to use PR to test this, since it updates everything.

**Comment by victorg1991** [comment]
The cadmin cadmin is not added to the dropdown that the Picker component creates 🤔  I have sent you a pr here: https://github.com/matuzalemsteles/liferay-portal/pull/61 it doesn't seems to have anything wrong, maybe some dependencies are off. Could you give it a try? Here is the specific commit where I use the component: https://github.com/matuzalemsteles/liferay-portal/pull/61/commits/6d08d4dc90095a752c10dd5ae8e39508b27a4980

**Comment by matuzalemsteles** [comment]
Actually it shouldn't be necessary because all the `React.Portal` we use in Clay is the `ClayPortal` component that consumes directly from the Provider https://github.com/liferay/clay/blob/master/packages/clay-shared/src/Portal.tsx#L63 🤔

**Comment by matuzalemsteles** [comment]
I did a test with your PR and my assumption is that it could be something with the bundler maybe version conflict within the DXP due to other modules that are not built together with the DXP like site-initializers for example may have a different version of shared and provider maybe.

Looking at the network in devtools it looks like the `@clayui/core` package wraps the dependency on provider and `@clayui/shared` as well, so it could be that there are two Provider references where ClayPortal is consuming a different dependency of `@clayui/core`.

I think this might be some bundler issue because we are re-exporting the `@clayui/provider` package from `@clayui/core` and the `@clayui/shared` consumes the `@clayui/provider` just to not have problems of circular dependency 🥲

I think instead of consuming the `Provider` component of `@clayui/core` try consuming directly from the `@clayui/provider` package.

**Comment by matuzalemsteles** [comment]
> This doesn't seem to work in the portal 🥲 Could we make a the menuAttrs API like in other components, or maybe allow setting a className for the menu, otherwise I am not sure how to set the cadmin class to it

🥲 Yeah, let's go with that and add an API to configure for now, I'll look into Frontend Infra if this could be a problem with bundler if we can solve it.
