### ISSUE TITLE
ClayMultiSelect - Is it possible to allow the `,` (comma) inside the Input field?

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#5313]
Raised in this [Commerce "bug" report](https://issues.liferay.com/browse/COMMERCE-10474).

**Comment by matuzalemsteles** [comment]
Hi @kresimir-coko, the problem is that allowing the comma we are no longer able to determine when the user wants to convert the text into a label. Can commerce case names have comma in product title?

cc @emiliano-cicero @drakonux I think this is a good edge case for us to understand if we should provide another alternative or just allow to disable the use of the comma and let just press Enter to create the label.

Another issue is that maybe we need to review the MultiSelect behaviors for the commerce cases, it seems they use the MultiSelect otherwise and this ends up having to ignore component behaviors, related issue #5303, #5308 (allow duplicate labels). Maybe this is not the ideal component for their behavior?

**Comment by kresimir-coko** [comment]
> Can commerce case names have comma in product title?

Yes @matuzalemsteles , and they don't use the default functionality of comma/enter delimiters, they want to pick from a list.

So maybe just a boolean prop that disables the whole comma/enter functionality, or an `onComma` and `onEnter` props so that they can individually be manipulated.

**Comment by emiliano-cicero** [comment]
Hey @matuzalemsteles and @kresimir-coko, 
For me, this is at max a customization (or feature request) that should be considered an extension of the component, this shouldn't come OOTB but they should be allowed to add it if necessary (or change some settings to enable it). Thus, this can't be a bug. 

The multiple select uses the comma intentionally to add labels to the same input but is not meant as a search bar. If they need a search bar with results, I think the multiple select is not the correct component to use. Even if it has a similar behaviour, the interaction details are very different. They should probably use a different search bar with a panel for results.

**Comment by matuzalemsteles** [comment]
Thanks @emiliano-cicero for the details.
