### ISSUE TITLE
ClayEmptyState: No margin between image and description

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5325]
I'm working on unifying all the empty states of the portal using the ClayEmptyState component. Many of these empty states only have a description (as shown in the image on the left).

|||
| ----- | ---- |
| <img width="400" alt="Screen Shot 2023-01-26 at 3 17 20 PM" src="https://user-images.githubusercontent.com/9701095/214858834-01e89433-d831-4313-9f31-85366273f3a8.png"> | <img width="400" alt="Screen Shot 2023-01-26 at 3 17 08 PM" src="https://user-images.githubusercontent.com/9701095/214859026-28125cda-a764-4158-bcd0-57c8a5f19f03.png"> | 

When it is updated with the ClayEmptyState component it shows as in the image on the right. As you can see there is no margin between the image and the description. Looking at Lexicon's [Empty State](https://liferay.design/lexicon/core-components/empty-states/), I understand that between the image and the text (either title or description) there should be a margin of 40px, right?

<img width="400" alt="Screen Shot 2023-01-26 at 3 00 45 PM" src="https://user-images.githubusercontent.com/9701095/214859443-3e028b94-b122-4cee-b563-6fb5c7cc150e.png">

Thank you so much guys!

**Comment by ethib137** [comment]
Hey @veroglez thanks for bringing this to our attention. We discussed this with the lexicon designers and what we would like to recommend would be to make the title (No documents yet) required and the description (Fortunately, it is very easy to add new ones.) This I believe would end up fixing your issue since the margin is added to title not the description. 

This wasn't clearly documented on Lexicon, so we will be updating the docs there as well.

Additionally, @matuzalemsteles do you think it would make sense to use this ticket to update the props to make the title required to match our Lexicon requirement?

Please let me know if you see any issues with this approach. Thanks again!

**Comment by pat270** [comment]
We can take advantage of margin collapse in CSS to make the spacing between image and text be larger by adding `margin-bottom` on the image if there is no title. I forgot why I made `c-empty-state` `display: flex`. I want to say it's `display: flex` because everything would be centered. If there is only one image allowed in `c-empty-state` then we could apply this.

**Comment by matuzalemsteles** [comment]
@ethib137 That makes sense, we can use that same ticket to do that. My only concern would be that making this change causes many build errors in DXP by making the title required where the title is not being added, so we will have to add the title for these teams or ask for their help to decide which text we should put.

**Comment by veroglez** [comment]
Hi guys!! Currently, the default title is "No results found". However, the title can be removed if title props = `null` or an empty string. Perhaps, instead of setting it as required and generating the DXP build errors that @matuzalemsteles comments, it could be taken into account in the code and in these cases the default title always appears. I mean, the title couldn't be erased in any way. This is just an idea, what do you think?

**Comment by matuzalemsteles** [comment]
I noticed that there are 89 use cases for the component, the vast majority render a title and I saw that in some cases there is no title but it is a small minority, there is also a use case that only exists the image and does not render the title and description.

It seems safe to always render the default title with "No results found" even if the title property is set to null or an empty string.
