### ISSUE TITLE
Clay Breadcrumb is breaking when the items array is empty

### ISSUE THREAD

**Issue by kevenleone** [liferay/clay#5402]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/elastic-davinci-nt3l1k?file=/src/index.js

## What are the steps to reproduce?
* Use the Component 
```
import ClayBreadcrumb from '@clayui/breadcrumb';

<ClayBreadcrumb items={[]} />
```

Passing an empty array is enough to break the component.

## What is the expected result?]

Not brake

## Environment

| Tech  | Version |
| ----- | ------- |
| @clayui/breadcrumb| v3.89.0  |
| React |     v16.8.4    |

**Comment by kevenleone** [comment]
It can be reproduced here: https://clayui.com/docs/components/breadcrumb.html

https://user-images.githubusercontent.com/22279592/223140433-d44decc7-7252-4094-a4f3-4a7c66b937a4.mov

**Comment by matuzalemsteles** [comment]
I think this case would be not rendering the breadcrumb but this should be done outside the component with the conditional instead of handling it internally in the component.

**Comment by kevenleone** [comment]
Ok, I did it @matuzalemsteles.

I was thinking it as a bug, you can close the issue then 😄

**Comment by matuzalemsteles** [comment]
It doesn't make much sense to make Breadcrumb not render anything when there is nothing in the list, for example if you do a conditional inside the component we still have to declare the component in the React tree and also the hooks, this creates an unnecessary load to render a component that will render `null` as well as start creating conditionals on parts of the component to avoid doing certain computations because it won't render anything, so as common practice it's best to do the conditional outside the component to avoid creating unnecessary complexity.
