### ISSUE TITLE
Drag&Drop in TreeView is activated whenever other element (like dropdown) is focused outside the component 

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#5430]
## Is there an example you can provide via codesandbox.com?
There are two examples in Liferay Portal, see issue https://issues.liferay.com/browse/LPS-178730 
It happens in _Knowledge Base_ (activate FF `feature.flag.LPS-156421=true`) and in _Pages Tree_ component

## What are the steps to reproduce?

In knowledge Base: 

1. Open the Folders and Articles section
2. Click on the kebab menu near Home folder, or try to change view from list to table, or open the info panel ("i" icon in the Management toolbar)

In Pages Tree: 
1. Click on the "+" icon near the selector

## What is the expected result?
The Drag&Drop option must be activated only by keyboard (I guess...)

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | current version in master |
| React |         |

**Comment by matuzalemsteles** [comment]
Hey @ambrinchaudhary I'm not sure if I understand very well, drag and drop is enabled and the icon is visible even when interacting via the mouse, right?

**Comment by ethib137** [comment]
Here's an example on codesandbox: https://codesandbox.io/s/ecstatic-bird-lsqoy6 You can reproduce simply by clicking on the button to open the dropdown.

I think the problem is that the drag handles are only shown when navigating with the keyboard, but opening a dropdown manually moves focus to the popup which is interpreted as navigating with the keyboard. So when you open a dropdown the drag handles are displayed.

Personally, I would want to fix this by always showing the drag handles. I don't find the UX very intuitive that we hide this from mouse users. But I'm not sure what our reasoning was for this behavior when it was implemented, so it would be good to understand that first.

**Comment by ethib137** [comment]
@ambrinchaudhary , is my explanation above a correct understanding of this issue?

**Comment by ambrinchaudhary** [comment]
@ethib137 you are correct!

**Comment by matuzalemsteles** [comment]
> I think the problem is that the drag handles are only shown when navigating with the keyboard, but opening a dropdown manually moves focus to the popup which is interpreted as navigating with the keyboard.

Makes sense, it could be a problem with the `useFocusVisible` mechanism.

> Personally, I would want to fix this by always showing the drag handles. I don't find the UX very intuitive that we hide this from mouse users. But I'm not sure what our reasoning was for this behavior when it was implemented, so it would be good to understand that first.

The idea is that the drag via mouse is done via the item instead of showing the icon that works as a handler to start the drag, so it only serves for navigation via keyboard or SR. Even though we don't use it anymore we still have to fix this problem in this hook because we use it for other functionality.
