### ISSUE TITLE
Vertical Nav overlaps items with long nested list

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#5513]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/dazzling-antonelli-pklh9h?file=/src/items.js

## What are the steps to reproduce?
1. Navigate to the code sandbox
2. Expand `User` at the bottom.
3. Expand `Site and Asset Library Administration`.
4. Expand `Applications`.

## What is the expected result?
The items should not overlap.

**Actual Result:**
The Application and user items overlap one another.

**Comment by ethib137** [comment]
![Screenshot 2023-05-09 at 2 14 09 PM](https://github.com/liferay/clay/assets/1609196/cdf26bd5-907f-469a-b1ad-ebb4536dd4eb)

**Comment by pat270** [comment]
The bug seems to be due to setting a fixed height on a parent container. If the parent container height is shorter than the child's then we will see this issue. We need to set the height programmatically to properly animate the collapsing panel. It should be removed after the transition has completed.
