### ISSUE TITLE
Vertical Nav add negative margin on mobile view with menubar-vertical-expand-lg class

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#5521]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/vertical-nav-margin-issues-g9uex8?file=/src/index.js

## What are the steps to reproduce?
1. Go to https://codesandbox.io/s/vertical-nav-margin-issues-g9uex8?file=/src/index.js
2. Make sure the window is small enough to display the mobile view.

## What is the expected result?
The menu and trigger should fit inside the window.

Actual Result:
The menu and trigger have negative margin and are overlapped by the window.

![Screenshot 2023-05-10 at 4 30 10 PM](https://github.com/liferay/clay/assets/1609196/efe1551a-ddbd-4439-9ead-a752dcd2bb98)

**Comment by pat270** [comment]
@ethib137 There are issues with negative margin, but I think we need to have a discussion with @drakonux, @emiliano-cicero and @marcoscv-work about how the vertical nav should be positioned in mobile especially with other items like a search input. In the current state, it's supposed to be another navigation like bar in mobile.

![menubar](https://github.com/liferay/clay/assets/788266/e8f1be58-b440-455b-8746-023770e8a817)

**Comment by ethib137** [comment]
@emiliano-cicero , has this already been discussed how this should look on small screens / mobile?

**Comment by emiliano-cicero** [comment]
I don't think it was discussed directly but we probably assumed having a default margin given by the container. The example for the vertical-nav on mobile has no-margin because it's aligned to the form and as @pat270 says, I think it's probably the 12px gutter (although visually it seems more like 16px so there might be something else). 
![image](https://github.com/liferay/clay/assets/27729173/faf15273-f56d-41c5-83f9-d47d9de22bca)

If it's placed without a container then it should respect the margins from both sides. 

Regarding the position, I don't know if I understood correctly but I'll try to answer: the vertical nav should be considered almost as part of the content since the interaction is directly connected with the content on the left/bottom, the search bar would go on top as is part of the management toolbar (with its mobile version).
