### ISSUE TITLE
ClayTreeView dnd improvements

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#5591]
Hi guys! We have a usage of `ClayTreeView` in which we are using our own drag and drop logic instead of the one implemented in the component, and I'm working now on a task about removing our own drag and drop logic and use `ClayTreeView`'s one.

During my work, I've found some improvements I think we could do for us to be able to migrate our drag and drop without losing functionality 😄

## `onItemHover` to return a boolean so we can "cancel" hover

Just as we do with `onItemMove`, I think we could allow returning a boolean on `onItemHover` to stop the hover. This would allow us to prevent an item from hovering an incorrect target (we can't use `draggable: false` in that target because it can be dragged as well). @matuzalemsteles we already discussed this in https://github.com/liferay/clay/issues/5141.
I also think we should avoid the drop when returning `false` in the hover. Matu, I sent you a PoC here so you can take a look on what I mean: https://github.com/matuzalemsteles/clay/pull/12. Please tell me what you think!

## Keyboard dnd to use `onItemHover` and `onItemMove`

I've seen that currently, we are not using these callbacks for the keyboard dnd. Is there any reason for that? Without that, we are not able to trigger our logic when hovering and dropping.
I think a good approach (considering we implement what I suggested in the first point) would be:
- When pressing arrows to move, execute `onItemHover` to calculate if next target is valid. If it returns `true`, set the target, and if it returns `false`, try with the next one.
- When pressing Enter to place the item, execute `onItemMove`. If it returns `true`, do the movement, and if it returns `false`, don't do the movement (and maybe keep the drag active and don't cancel it so the user can try with another target).

## Fix drag preview alignment

I've seen that in our tree, the drag preview is not being aligned properly with the cursor. However, I saw that in other usages in portal it is well aligned, so I don't know if there is some difference. You can see it disaligned as well in the first Clay doc example: https://clayui.com/docs/components/treeview.html.

If you guys prefer I open different issues for each thing, please let me know. Thanks!

**Comment by matuzalemsteles** [comment]
Hi @sandrodw3 thanks for reporting these use cases again I think they are valid, I will look at your PoC, feel free to send it directly to Clay's repo next time no problem even if it is an initial idea or just a PoC.

> onItemHover to return a boolean so we can "cancel" hover

Yeah, I think it's a good strategy and it makes sense to go with it.

> Keyboard dnd to use onItemHover and onItemMove

There really wasn't any reason for that, I think we missed that implementation when we were implementing that. But yes, it makes sense to try to adapt this regardless of whether it is keyboard or via mouse.

> [...]don't do the movement (and maybe keep the drag active and don't cancel it so the user can try with another target).

Hmm that's an interesting question, I think if we take into account the behavior of DnD via mouse, in theory when the user releases on an item that is not droppable the move would be canceled and no action would be taken. If we bring this to the keyboard I think it would make sense to maintain the same interaction parity when trying to drop on a non-droppable element the movement would be canceled but there is a different behavior here that I think this case would not exist, if we consider that the item does not is droppable it would not have the focus because the onItemHover call would not be valid so moving the item would only be on droppable items. What do you think, does it make sense?

If we thinking more about it, this new case of `onItemHover` it basically nullifies the call of `onItemMove` 🤔

> Fix drag preview alignment

I think this one could be another issue, I think the others above are well related so ok we use this issue here.

**Comment by sandrodw3** [comment]
Hey @matuzalemsteles! Thanks a lot for your feedback 😄

> Hi @sandrodw3 thanks for reporting these use cases again I think they are valid, I will look at your PoC, feel free to send it directly to Clay's repo next time no problem even if it is an initial idea or just a PoC.

Ok! I'll do it next time, I didn't send it there just because it was a PoC, but if you say that, I'll send it next time!

> Hmm that's an interesting question, I think if we take into account the behavior of DnD via mouse, in theory when the user releases on an item that is not droppable the move would be canceled and no action would be taken. If we bring this to the keyboard I think it would make sense to maintain the same interaction parity when trying to drop on a non-droppable element the movement would be canceled but there is a different behavior here that I think this case would not exist, if we consider that the item does not is droppable it would not have the focus because the onItemHover call would not be valid so moving the item would only be on droppable items. What do you think, does it make sense?
> 
> If we thinking more about it, this new case of `onItemHover` it basically nullifies the call of `onItemMove` thinking

Um, that's right, I didn't think it well yesterday. It's true that this new approach of `onItemHover` would avoid a call of `onItemMove` in a wrong target, so yeah, I agree with you 😄
> 
> I think this one could be another issue, I think the others above are well related so ok we use this issue here.

Cool! Thanks Matu, please tell me if I can help in any way during the development!
