### ISSUE TITLE
@clayui/vertical-nav active property doesn't work

### ISSUE THREAD

**Issue by edalgrin** [liferay/clay#5595]
The `active` property of the ClayVerticalNav is not working, I've tried it online on https://clayui.com/docs/components/vertical-nav.html and locally, if you change the `active` property value on the code, the output ui won't change.

![verticalnavplus1](https://github.com/liferay/clay/assets/46778114/d1ac1bdd-779f-4197-b8d9-ca745c09c005)
<img width="670" alt="image" src="https://github.com/liferay/clay/assets/46778114/7dadb76d-c1c7-44e5-ad02-7a3cd71d1612">
<img width="868" alt="image" src="https://github.com/liferay/clay/assets/46778114/de238262-4dc7-4d53-8119-6e7a80ea9034">

**Comment by matuzalemsteles** [comment]
In fact what is happening is that internally the `key` which is a type `number` is being converted to a `string` that's why it is not working correctly, so this only happens if the `id` of the items are of type `number`.

**Comment by pat270** [comment]
@matuzalemsteles I got the example to work by using `active="1"`.

**Comment by matuzalemsteles** [comment]
@pat270 actually we should respect the type of the property defined in the `key` key instead of converting to string, I think this must be an internal problem of the collection implementation, I have to investigate this further.

**Comment by pat270** [comment]
@matuzalemsteles I took a look and the `collection` returns keys as a string. The problem is we are passing it in as a number and the collection methods can't find them.

**Comment by pedro-michel** [comment]
Jira ticket: https://liferay.atlassian.net/browse/LPS-188434

**Comment by matuzalemsteles** [comment]
@pat270 yeah, I investigated this a bit more today and unfortunately we won't be able to change that because this is internal to React.js, it will always convert the value to a string https://github.com/facebook/react/blob/70e998a1064cc1e8e8f9103e0c00d37fbbcf71c1/packages/react/src/jsx/ReactJSXElement.js#L296-L307.

@edalgrin I think from our end we can't do anything here, what we can do now is change all our examples so that the `key` is a string to avoid future problems and recommend that people always use `string` instead of a type `number`.
