### ISSUE TITLE
An element's tooltip remains visible when navigating its inner elements

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5607]
Hi guys! From the Echo team we are working on improving the accessibility of the Navigation Menus. And we want to add a tooltip to each of the following cards, indicating that when they are clicked, the panel on the right is opened.

<img width="500" alt="imgTooltip" src="https://github.com/liferay/clay/assets/9701095/acb60e19-35df-430c-9e59-b7ae9d4f46b4">

When the tooltip is added to the card and navigated within it, the following happens: The tooltip of the card appears and remains visible. No other tooltip of the other buttons is shown (see the attached video).

https://github.com/liferay/clay/assets/9701095/f54418b7-7069-4855-ad65-ed7df1f8047d

Is this an expected behavior? Thanks in advance

**Comment by matuzalemsteles** [comment]
Hey @veroglez this looks like a bug, I think it could be that since the card's container has a tooltip and the elements inside it also the tooltip engine maybe not knowing whether to hide the card's tooltip since it still has focus. In the case where the other tooltips are being shown is because the focus is coming from the inside out it probably doesn't reproduce, can you show an example so I can reproduce this in a separate environment?

What we can improve in the mechanism is if we focus on an element that contains a tooltip we continue with the hidden of the current tooltip to try to show the next tooltip, as the [mechanism is based on the hierarchy of the DOM structure](https://github.com/liferay/clay/blob/master/packages/clay-tooltip/src/useClosestTitle.ts#L102-L107) to check if the tooltip should be shown or not maybe it has some challenges but i think that should be enough.

**Comment by veroglez** [comment]
Hi @matuzalemsteles
> What we can improve in the mechanism is if we focus on an element that contains a tooltip we continue with the hidden of the current tooltip to try to show the next tooltip, as the [mechanism is based on the hierarchy of the DOM structure](https://github.com/liferay/clay/blob/master/packages/clay-tooltip/src/useClosestTitle.ts#L102-L107) to check if the tooltip should be shown or not maybe it has some challenges but i think that should be enough.

It would be fantastic!


I just tried it on Clay's own page with this example:

```
import ClayButton from '@clayui/button';
import ClayCard from '@clayui/card';

const Component = () => {
  return (
    <div className="col-md-5">
      <ClayCard tabindex="0" title="This is a Card">
        <ClayCard.Body>
          <ClayCard.Description displayType="title">
            {"Card Title"}
          </ClayCard.Description>
          <ClayCard.Description truncate={false} displayType="text">
            {
              "Some quick example text to build on the card title."
            }
          </ClayCard.Description>
          <ClayButton title="Go somewhere 1">{"Go somewhere 1"}</ClayButton>
          <ClayButton className="ml-2" title="Go somewhere 2">{"Go somewhere 2"}</ClayButton>
        </ClayCard.Body>
      </ClayCard>
    </div>
  );
};

render(<Component />);
```
And the result is the following:


https://github.com/liferay/clay/assets/9701095/7fb7513d-847b-4277-acbd-11007565d27a

**Comment by matuzalemsteles** [comment]
Thank you @veroglez for reproducing this, it will help a lot.
