### ISSUE TITLE
@clayui/empty-state: Append _reduced_motion to the imgSrc url by default

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5638]
@matuzalemsteles I was taking a look at https://liferay.atlassian.net/browse/LPS-168263 and wanted to fix the reduced motion images, but it looks like we are using `ClayEmptyState` individually in each component. I assumed we had a tag that each module was calling. What do you think about appending `_reduced_motion` to the `imgSrc` when `imgSrcReducedMotion` isn't defined?

**Comment by matuzalemsteles** [comment]
@pat270 it might be a good idea. Can we validate that the link is not broken so we don't render a broken image? For example if the `imgSrcReducedMotion` is not defined we add the suffix and check if it is a valid link otherwise we continue rendering the image with animation. As a support for the developer we can throw a warning in the console so that the team can fix this. What do you think?

**Comment by pat270** [comment]
@matuzalemsteles Sounds good, how do we go about validating it exists?

**Comment by matuzalemsteles** [comment]
@pat270 I think we can add an `onError` callback to the image, if it returns a network error when trying to load the image we can change the state and render the image with animation.

**Comment by pat270** [comment]
@matuzalemsteles Thanks, I'll send a pr for it.

**Comment by matuzalemsteles** [comment]
Just to say that by doing this we can also fix the ticket with this [LPS-190149](https://liferay.atlassian.net/browse/LPS-190149) and other use cases that we don't know yet.

**Comment by pat270** [comment]
@matuzalemsteles Do we still need to provide a warning message if the browser outputs:

```
GET http://localhost:8888/static/media/packages/clay-css/src/images/images/success_state_reduced_motion1.gif 404 (Not Found)
```
