### ISSUE TITLE
Support data attributes in links (and maybe everywhere?)

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#700]
To keep compatibility with the old non clay links in portal, we need to be able to add data attributes.

We need something like this:

```jsp
<%
Map<String, String> data = new HashMap<>();
data.put("customProperty", "customValue");
%>

<clay:link data="<%= data %>" href="#" label="link text" />
```

Expecting:

```html
<a data-customproperty="customValue" href="#">Link text</a>
```

Thanks!

**Comment by matuzalemsteles** [comment]
Hey @4lejandrito, We have a specific API for this in some components. We have created the [ClayComponent](https://github.com/liferay/clay/blob/master/packages/clay-component/src/ClayComponent.js) to have this kind of generalist option and maybe we will add more things in the future to he.

You can use the `data` API that is present in **ClayLink** and **ClayButton** for now. @carloslancha can say more about this if it is present in Taglibs.

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

Thanks for your response. I did not know this was already supported in clay js. The problem must be somewhere inside the taglibs then. I will talk to @carloslancha about it. 

Please feel free to close this if you want.

**Comment by carloslancha** [comment]
@4lejandrito  @matuzalemsteles  Unfortunately you will never have the data attribute rendered in the DOM due to soy limitations. What we did is a workaround that overwrites the `getAttribute` method of the component element and returns the value of the attribute you're looking for. That attribute is not in the DOM but in a storage managed by metal.

In the end the use for the developer should be the same, the only difference is that you won't see the data-attribute rendered in the element.

**Comment by 4lejandrito** [comment]
Thanks @carloslancha.

You can close this then 😢.

**Comment by jbalsas** [comment]
I was thinking that maybe we could complement our current solution by pushing the `data` collected elements to the `element` container on every `rendered` lifecycle. That way, it could also be reflected in DOM.

**Comment by carloslancha** [comment]
That could work @jbalsas
