### ISSUE TITLE
Failed to exec soy script

### ISSUE THREAD

**Issue by oliosien** [liferay/clay#802]
I have executed `npm run build`, but I get this error (see attached file).

[npm-debug.log](https://github.com/liferay/clay/files/1918768/npm-debug.log)

**Comment by jbalsas** [comment]
Hi @oliosien, sorry you hit this... the first thing that comes to mind was, that you might not have Java installed, but I think I can see it in your PATH...

Can you confirm what OS are you running and what jdk version?

**Comment by oliosien** [comment]
Hi @jbalsas, I have installed `java version "1.8.0_151"` and I work on **Windows 10** station.

**Comment by kino90** [comment]
Hi @oliosien @jbalsas ,
I was having the same issues when trying to exec `npm run build` on my workspace (which is a **Windows10** machine, with **Node 8.0.0** and **Java 1.8.0_141**

It looks like Window can't handle RegExp as CLI arguments, so this line is failing:

`metalsoy --soyDeps '../../node_modules/clay-+(button|icon)/src/**/*.soy'`

The `(button|icon)` isn't getting parsed as a regExp by Windows system, resulting in the bash calling `icon)` as a command itself, and then returning an error like `icon) is not a valid program`

I solved building the project in a Linux VM, even if I'd rather this problem to be fixed soon to go back working on my workspace, instead of a vm

**Comment by jbalsas** [comment]
Hey @kino90, thanks so much for that tip! That helps narrowing this down a lot! We'll take a look at this soon!

**Comment by kino90** [comment]
Also, I had to install Java on my VM, which isn't written anywhere.. I took a while to guess it (until I read this issue) :wink:

**Comment by jbalsas** [comment]
Yeah, I checked because I thought we mentioned that somewhere, but I couldn't find it, so I'll make sure we add a clear warning with this. Sorry for the trouble!

**Comment by oliosien** [comment]
Thx to all.

**Comment by carloslancha** [comment]
@jbalsas @kino90 @oliosien is this still happening?

**Comment by matuzalemsteles** [comment]
Hey guys, I'm closing this so we can track this down in question #1056 that is related.
