### ISSUE TITLE
Clay Component Navigation Bar should remove inline style `height` on transition end

### ISSUE THREAD

**Issue by pat270** [liferay/clay#806]
Opening the nav in mobile then resizing the browser to desktop causes `navigation-bar` to be too tall.

<img width="991" alt="navigation-bar" src="https://user-images.githubusercontent.com/788266/38902088-d18380b4-4253-11e8-98d3-efabe34b4230.png">

**Comment by matuzalemsteles** [comment]
Hey @pat270 I've been looking at this now and since we were talking offline, I had an idea. Let me know if it's the ideal.

We can change in the `.collapsing` class the `height: 0` attribute to `max-height: 0` and add to 
`.navbar-collapse`:

```css
transition: max-height 0.25s ease-in;
```

Or we can add this to `.collapsing`. This will trigger the `.transitionend` event so that I can set `max-height: ${heightCollapse}`, so we would not have this problem when doing resize. What do you think?
