### ISSUE TITLE
Management Toolbar on small screens

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#815]
Currently, there are 2 apparent issues with the management toolbar on small screens:
1. The add button disappears under some conditions
2. The collapsible search can't be dismissed once it's been activated

See attached screenshot from the ManagementToolbar demo page

![management_toolbar_mobile](https://user-images.githubusercontent.com/905006/38929318-2cd9193e-430c-11e8-9140-c9ebd114157f.gif)

**Comment by carloslancha** [comment]
1. This happens beacause add button has the class `navbar-breakpoint-down-d-none`.

2. This happens because close button has the class `d-none`.

@pat270 this is not correct right? Add button should be always visible and search close button should be only visible in small screens (replacing `d-none` with `navbar-breakpoint-d-none` solves it). Can you confirma this and update it in the examples if it's ok?

Thx!

**Comment by pat270** [comment]
@carloslancha I was told by @victorvalle that the plus button should always be visible. I would say it's safe to remove any `d-none` class on the plus button.

**Comment by pat270** [comment]
@carloslancha can we just push in the changes to Clay Management Toolbar? @victorvalle said it was very urgent and I'm doing commerce at the moment. I'll find some time this week to send changes to the clayui site.

**Comment by victorvalle** [comment]
@pat270 @carloslancha  For me is urgent so QA does not open many bugs. Do it as you prefer as it is under control and the change seems easy.

**Comment by jbalsas** [comment]
We are planning a release for wednesday, so we just need to make sure this is in by then. We can definitely just fix the managementtoolbar for now and update the examples throughout the week, as I'll be working on the demos for the webinar.

**Comment by carloslancha** [comment]
Sure @pat270
